numaproj/numaflow

.github/workflows/ci.yaml
Makefile
test/manifests/e2e-api-pod.yaml

ci: add ci jobs

---

docs/USER_DEFINED_FUNCTIONS.md
docs/USER_DEFINED_SINKS.md
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/isb/jetstream/writer_test.go

feat: expose more envs in udf and udsink

---

config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
go.mod
go.sum

chore: switch to Limits retention policy by default

---

README.md
docs/DEVELOPMENT.md
docs/QUICK_START.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>

docs: Update README and DEVELOPMENT

---

Makefile
docs/RELEASES.md
docs/RELEASING.md

chore: Release script

---

.github/workflows/changelog.yml
hack/changelog.sh

ci: changelog automation

---

README.md
examples/1-simple-pipeline.yaml
examples/2-http-pipeline.yaml
examples/3-pipeline-filter.yaml
examples/4-udsink-pipeline.yaml
examples/5-auto-scaling.yaml
examples/README.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>
Using the name input to name the input vertex is confusing since we also want to use the work input to describe the input :-)

docs: update examples

---

docs/sources/HTTP.md

docs: refine http source docs

---

README.md
pkg/sources/generator/tickgen.go
pkg/udf/udf.go

Default value for `NUMAFLOW_WATERMARK_ON` is `"false"` and we need to make sure only `"true"` turns on watermark

turn on watermark only if ENV value is true

---

config/base/controller-manager/numaflow-controller-config.yaml
config/base/crds/numaflow.numaproj.io_interstepbufferservices.yaml
config/install.yaml
controllers/isbsvc/installer/installer_test.go
docs/APIs.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/isbsvc/interface.go
pkg/isbsvc/jetstream_service.go

feat: controller to create buckets

---

config/base/crds/numaflow.numaproj.io_interstepbufferservices.yaml
config/install.yaml
controllers/pipeline/validate.go
docs/APIs.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/isb/redis/read.go
pkg/isb/redis/write.go
pkg/sources/kafka/metrics.go

fix spelling errors

---

pkg/isb/jetstream/metrics.go
pkg/isb/jetstream/writer.go
pkg/isb/jetstream/writer_test.go

chore: switch JetStream sync writing to async

---

pkg/daemon/server/daemon_server.go
pkg/isb/interfaces.go
pkg/isb/jetstream/options.go
pkg/isb/jetstream/reader.go
pkg/isb/jetstream/types.go
pkg/isb/jetstream/writer.go
pkg/isb/redis/read.go
pkg/isb/simplebuffer/buffer.go
pkg/shared/queue/overflow_queue.go
pkg/shared/queue/overflow_queue_test.go
pkg/sources/generator/tickgen.go
pkg/sources/http/http.go
pkg/sources/kafka/reader.go

This is the first part of the code changes for auto-scaling feature.
1. An `Ratable` interface is introduced in this PR, which will be implemented in the ISB reader and writer to measure the processing rate. For ISB reader, the `Rate()` returns the acknowledge rate, in ISB writer, it returns the writing rate.
2. An `Pending()` function is also introduced into `Reader` interface, which is intended for the ISB Reader and sources to implement.

feat: auto-scaling (part 1)

---

SECURITY.md
docs/STATIC_CODE_ANALYSIS.md

docs: security related docs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
Makefile
docs/DEVELOPMENT.md
hack/git/hooks/commit-msg
hack/git/hooks/pre-push

chore: github templates and git hooks

---

README.md

chore: opensff best pratices

---

cmd/commands/controller.go
cmd/commands/root.go
cmd/commands/server.go
controllers/cmd/start.go
server/cmd/start.go
server/routes/routes_test.go

chore: ux server combined into unified binary

---

.github/pull_request_template.md
.github/workflows/ci.yaml
Makefile
test/e2e/functional_test.go
test/fixtures/e2e_suite.go
test/fixtures/util.go
test/http-e2e/http_test.go
test/http-e2e/testdata/http-auth-fake-secret.yaml
test/http-e2e/testdata/http-source-with-auth.yaml
test/http-e2e/testdata/http-source.yaml

test: http source e2e test

---

test/e2e/functional_test.go
test/e2e/testdata/even-odd.yaml

test: conditional forwarding e2e test case

---

test/e2e/functional_test.go
test/e2e/testdata/even-odd.yaml
test/e2e/testdata/flatmap.yaml
test/fixtures/e2e_suite.go

test: test case for flatmap udf

---

pkg/sources/generator/watermark.go
pkg/sources/source.go
pkg/udf/udf.go
pkg/watermark/fetch/edge.go
pkg/watermark/fetch/edge_test.go
pkg/watermark/fetch/processor.go
pkg/watermark/fetch/vertex.go
pkg/watermark/fetch/vertex_test.go
pkg/watermark/progress/generic.go
pkg/watermark/publish/publisher.go
pkg/watermark/publish/publisher_test.go
pkg/watermark/store/interface.go
pkg/watermark/store/jetstream/kv_store.go
pkg/watermark/store/jetstream/kv_watch.go

Integration of the fetch/publisher KV interface for watermarks

Integration of generic fetch interface 

---

pkg/daemon/server/service/isbs_query_service.go

Signed-off-by: Krithika Vijayakumar <krithika_vijayakumar@intuit.com>

feat: Added the right way to decipher from and to vertex in daemon service

---

Dockerfile
pkg/isb/interfaces.go
pkg/isb/jetstream/options.go
pkg/isb/jetstream/reader.go
pkg/isb/jetstream/writer.go
pkg/metrics/metrics.go
pkg/sinks/sink.go
pkg/sources/source.go
pkg/udf/udf.go

Expose pending messages and processing rate in the past 1/5/15 minutes which can be used for UI display, and `default` for auto scaling (based on configurable lookback seconds)
```
vertex_pending_messages{period="15m",pipeline="simple-pipeline",vertex="p1"} 0
vertex_pending_messages{period="1m",pipeline="simple-pipeline",vertex="p1"} 0
vertex_pending_messages{period="5m",pipeline="simple-pipeline",vertex="p1"} 0
vertex_pending_messages{period="default",pipeline="simple-pipeline",vertex="p1"} 0
vertex_processing_rate{period="15m",pipeline="simple-pipeline",vertex="p1"} 23.47826086956522
vertex_processing_rate{period="1m",pipeline="simple-pipeline",vertex="p1"} 25.714285714285715
vertex_processing_rate{period="5m",pipeline="simple-pipeline",verte …
```

chore: Expose pending and rate metrics in 1/5/15 mins

---

pkg/udf/udf.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/publisher.go

Refactored the UDF to accept generic fetcher and publisher interface for watermarking progression.

chore: Refactor UDF watermark to accept interface

---

pkg/isb/forward/forward.go
pkg/isb/forward/forward_test.go
pkg/isb/forward/shutdown_test.go
pkg/isb/jetstream/writer_test.go
pkg/isb/redis/read_test.go
pkg/isb/redis/write_test.go
pkg/shared/util/watermark.go
pkg/sinks/kafka/kafka.go
pkg/sinks/kafka/kafka_test.go
pkg/sinks/logger/log.go
pkg/sinks/logger/log_test.go
pkg/sinks/udsink/sink.go
pkg/sources/generator/tickgen.go
pkg/sources/http/http.go
pkg/sources/kafka/reader.go
pkg/udf/udf.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/generic.go
pkg/watermark/generic/publisher.go

Refactor UDF to use publisher and fetcher interface for watermark

chore: Refactor UDF to use publisher and fetcher interface for watermark

---

pkg/watermark/store/noop/kv_store.go
pkg/watermark/store/noop/kv_watch.go

Implements a no op keyvalue store.

feat: add no-op KV Store

---

pkg/sources/generator/tickgen.go
pkg/sources/generator/tickgen_test.go
pkg/sources/generator/watermark.go
pkg/sources/generator/watermark_test.go
pkg/sources/source.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/generic.go
pkg/watermark/generic/publisher.go
pkg/watermark/generic/utils.go
pkg/watermark/publish/publisher.go
pkg/watermark/store/jetstream/kv_store.go
pkg/watermark/store/noop/kv_store.go

chore: refactor source watermark

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
README.md
SECURITY.md
docs/AUTOSCALING.md
docs/DEVELOPMENT.md
docs/QUICK_START.md
docs/README.md
docs/RELEASES.md
docs/builtin-functions/README.md
docs/metrics/METRICS.md
examples/README.md
ui/README.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>
Removed camel case from project names in docs.
FYI, there are a few files I didn't change since I wasn't sure if there may be external references to those names.
If there isn't, I can change those as well.

docs: Remove camel case from project names in docs

---

hack/build-ui.sh
ui/tsconfig.json

Signed-off-by: Krithika Vijayakumar <krithika_vijayakumar@intuit.com>

chore: removed unnecessary file and CI

---

pkg/sources/generator/watermark.go
pkg/watermark/fetch/edge.go
pkg/watermark/fetch/edge_test.go
pkg/watermark/fetch/processor_to_fetch.go
pkg/watermark/fetch/processor_to_fetch_test.go
pkg/watermark/fetch/vertex.go
pkg/watermark/generic/generic.go
pkg/watermark/generic/publisher.go
pkg/watermark/processor/entity.go
pkg/watermark/processor/entity_test.go
pkg/watermark/publish/publisher.go
pkg/watermark/publish/publisher_test.go

Remove publishKeyspace from processor entity and publisher signature.

chore: Remove publishKeyspace

---

pkg/watermark/fetch/edge_test.go
pkg/watermark/fetch/vertex.go
pkg/watermark/fetch/vertex_test.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/generic.go

remove fetchKeyspace from fetcher signature.

chore: remove fetchKeyspace

---

config/base/numaflow-server/numaflow-server-service.yaml
config/install.yaml
test/manifests/kustomization.yaml

1. Fix the imagePullPolicy for local testing;
2. Rename numaflow-server service name.

fix: imagepullpocily for local testing

---

pkg/isb/forward/forward.go
pkg/watermark/fetch/edge.go
pkg/watermark/fetch/edge_test.go
pkg/watermark/fetch/offset_timeline.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/noop.go

Enables getting watermark from the head offset.

feat: watermark for headoffset

---

controllers/vertex/controller.go
controllers/vertex/scaling/options.go
controllers/vertex/scaling/scaling.go
docs/quick-start.md
go.mod
go.sum
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/pipeline_types_test.go
pkg/daemon/server/service/pipeline_watermark_query.go
test/e2e/functional_test.go

Consider back pressure factor into autoscaling.
1. Back pressure calculation is based on `avg-pending/available-buffer-length > threshold`, threshold defaults to 90%, available-buffer-length = buffer-length * buffer-limit;
2. When calculating desired replicas, if it's more than current replicas:
a. If there's back pressure from directly connected vertices, instead of increasing the replicas, decrease by 1;
b. If the back pressure is from downstream not directly connected vertices, no scaling up or down will happen.

feat: autoscaling with back pressure factor

---

pkg/sinks/kafka/kafka.go
pkg/sinks/logger/log.go
pkg/sinks/logger/log_test.go
test/e2e/functional_test.go
test/e2e/testdata/watermark.yaml

Add e2e functional test for checking watermark correctness.
Signed-off-by: Sidhant Kohli <sidhant.kohli@gmail.com>

test: add e2e test for watermark

---

docs/CNAME

CNAME file in Github pages is erased every time there's a new main branch commit, add this file to fix it.

chore: CNAME file for github pages

---

pkg/daemon/server/service/pipeline_metrics_query.go
ui/src/components/pipeline/Pipeline.tsx

Fixes: https://github.com/numaproj/numaflow/issues/130

fix: pipeline UI broken when vertex scaling down to 0

---

pkg/isb/forward/forward.go
pkg/isb/forward/forward_test.go
pkg/isb/forward/shutdown_test.go
pkg/isb/jetstream/writer_test.go
pkg/isb/redis/read_test.go
pkg/isb/redis/write_test.go
pkg/sinks/kafka/kafka_test.go
pkg/sinks/logger/log_test.go
pkg/sinks/sink.go
pkg/sources/generator/tickgen_test.go
pkg/sources/source.go
pkg/udf/udf.go
pkg/watermark/fetch/offset_timeline.go
pkg/watermark/generic/jetstream/generic.go
pkg/watermark/generic/noop.go
pkg/watermark/store/noop/kv_watch.go

Fixes #88 
Signed-off-by: Sidhant Kohli <sidhant.kohli@gmail.com>

chore: fix #88

---

pkg/isb/forward/forward.go

add back nil check in forwarder because sources are still passing `nil` for WM fetchers and publishers

bug: watermark needs nil check

---

ui/src/components/pods/Pods.tsx

Signed-off-by: Krithika Vijayakumar <krithika_vijayakumar@intuit.com>
Fixes https://github.com/numaproj/numaflow/issues/135

fix: Fixed JS bug

---

docs/advanced-start.md
docs/inter-step-buffer-service.md
docs/quick-start.md

docs: update current docs

---

pkg/isb/format.go
pkg/isb/forward/forward_test.go
pkg/isb/forward/interfaces.go
pkg/isb/forward/shutdown_test.go
pkg/isb/jetstream/reader.go
pkg/isb/jetstream/writer_test.go
pkg/isb/redis/read_test.go
pkg/isb/redis/write_test.go
pkg/isb/testutils/udf.go
pkg/sinks/kafka/kafka_test.go
pkg/sources/kafka/handler_test.go
pkg/sources/kafka/reader.go
pkg/udf/applier/uds_http.go
pkg/udf/udf.go

chore: use string as the type of key

---

config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
pkg/daemon/server/service/pipeline_watermark_query.go
pkg/isb/forward/forward.go
pkg/sinks/sink.go
pkg/sources/generator/tickgen.go
pkg/sources/generator/tickgen_test.go
pkg/sources/generator/watermark_test.go
pkg/sources/source.go
pkg/udf/udf.go
pkg/watermark/fetch/edge.go
pkg/watermark/fetch/edge_test.go
pkg/watermark/fetch/offset_timeline.go
pkg/watermark/fetch/processor_to_fetch.go
pkg/watermark/fetch/utils.go
pkg/watermark/fetch/vertex.go
pkg/watermark/fetch/vertex_test.go
pkg/watermark/generic/fetcher.go
pkg/watermark/generic/jetstream/generic.go
pkg/watermark/generic/publisher.go
pkg/watermark/publish/publisher.go
pkg/watermark/publish/publisher_test.go
pkg/watermark/store/interface.go
pkg/watermark/store/jetstream/kv_store.go
pkg/watermark/store/jetstream/kv_watch.go
pkg/watermark/store/noop/kv_store.go
pkg/watermark/store/noop/kv_watch.go

refactor: some refactor on watermark

---

pkg/window/strategy/sliding/sliding.go
pkg/window/strategy/sliding/sliding_test.go

sliding window changes and tests.

fix: sliding window fixes

---

pkg/metrics/metrics.go
pkg/udf/applier/uds_grpc.go
pkg/udf/udf.go

feat: check if udf is running in liveness probe 

---

docs/quick-start.md

fix: broken path in doc

---

pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/apis/numaflow/v1alpha1/vertex_types_test.go

fix: use scale.max if it is set

---

docs/quick-start.md
docs/user-defined-functions.md

**Fix numaflow golang udf example and the `Golang` link**
**Fix docs**
Before:
Now:

fix: numaflow-go udf example & docs

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
go.mod
go.sum

chore: enable jetstream 2.9.0

---

docs/README.md
ui/README.md

fix(docs): readme for UI development

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
controllers/config.go
controllers/vertex/controller.go
controllers/vertex/controller_test.go
docs/APIs.md
docs/controller-configmap.md
pkg/apis/numaflow/v1alpha1/const.go

chore: clean up code of http protocol udf and udsink

---

pkg/metrics/metrics.go
pkg/sinks/sink.go
pkg/sinks/udsink/sink.go

chore: probe udsink healthiness

---

pkg/pbq/pbq.go
pkg/pbq/pbq_test.go
pkg/pbq/pbqmanager.go
pkg/pbq/pbqmanager_test.go
pkg/pbq/store/memory/store.go
pkg/pbq/store/memory/store_test.go
pkg/reduce/pandf/processandforward.go
pkg/reduce/pandf/processandforward_test.go
pkg/reduce/readloop/ordered.go
pkg/reduce/readloop/ordered_test.go
pkg/reduce/readloop/readloop.go
pkg/window/keyed/keyed.go
pkg/window/keyed/keyed_test.go

bug: not working commit for changing partitionID as a composite type

---

examples/0-isbsvc-jetstream.yaml
ui/package.json
ui/yarn.lock

chore: fix security alert

---

docs/builtin-functions/README.md
docs/builtin-functions/filter.md
docs/installation.md
docs/user-defined-functions.md
docs/watermarks.md
examples/1-simple-pipeline.yaml
examples/2-http-pipeline.yaml
examples/5-auto-scaling.yaml
examples/README.md
mkdocs.yml
pkg/apis/numaflow/v1alpha1/udf.go
pkg/apis/numaflow/v1alpha1/udf_test.go

docs: add and refine some docs.

---

docs/metrics/metrics.md
pkg/isb/forward/forward.go
pkg/isb/forward/metrics.go

chore: add read and written bytes counter

---

.github/workflows/gh-pages.yaml
docs/CNAME

chore: move CNAME to GH action

---

pkg/isb/stores/jetstream/reader.go

fix(autoscaling): Ack pending should be included in total pending calculation

---

pkg/reduce/readloop/ordered.go

perf: avoid busy loop

---

USERS.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>
Add USERS.md file with Intuit as a user.

Add USERS.md

---

pkg/pbq/pbq.go
pkg/pbq/pbqmanager.go
pkg/pbq/store/memory/store.go
pkg/pbq/util/min.go
pkg/reduce/pnf/processandforward.go
pkg/reduce/readloop/ordered.go
pkg/reduce/readloop/ordered_test.go
pkg/reduce/readloop/readloop.go
pkg/window/keyed/keyed.go

chore: refactor and documentation

---

docs/sources/generator.md

Signed-off-by: @si3nloong  [sianloong90@gmail.com](mailto:sianloong90@gmail.com)
Fix typos in documentation.

fix(docs): fix a typo

---

pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service_test.go
pkg/apis/numaflow/v1alpha1/redis_buffer_service_test.go

Fixes: #253
Fixes container resources on jetstream isbsvc sts.

fix: container resource for jetstream isbsvc. Fixes #253

---

docs/inter-step-buffer-service.md

* how to bring in external Redis
* how to use Redis cluster

docs: update ISB redis doc

---

.github/workflows/ci.yaml
test/fixtures/expect.go
test/fixtures/port_forward.go
test/fixtures/util.go
test/fixtures/when.go
test/sdks-e2e/README.md

This change partially resolves #210. By adding retrying logic on pod log stream initialization and port forwarding, I was able to resolve two kinds of EOF errors, which are two of the most frequent causes of E2E test failure.
More investigation notes in https://github.com/numaproj/numaflow/issues/210#issuecomment-1293627883
Error 1
```
Watching POD: simple-pipeline-watermark-cat3-0-np6xu
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-cat3-0-np6xu/main?follow=true": EOF    functional_test.go:180: Expected vertex pod log contains "Start processing udf messages"
```
and Error 2
```
functional_test.go:39: Vertex POD name: simple-pipeline-input-0-fpizv
panic: error upgrading connection: error dialing backend: EOF
```
The following E2E test runs …

fix: retry when getting EOF error at E2E test

---

SECURITY.md

fix: hyperlink for security doc

---

ui/yarn.lock

chore: upgrade xmldom to address security concerns

---

README.md
docs/README.md

It is good to call out some use cases so users can relate to some of their problems that can be solved via Numaflow.

doc: add few use cases

---

.github/workflows/ci.yaml
config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
go.mod
go.sum

chore: use github action services and upgrade Jetstream

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
docs/inter-step-buffer-service.md
docs/numaflow-controller-config.yaml
pkg/isbsvc/jetstream_service.go

feat: configurable jetstream storage
tested:

feat: configurable jetstream storage

---

Makefile
docs/development.md

chore: fix broken development doc and remove incorrect make cmds

---

pkg/reduce/readloop/readloop.go
pkg/watermark/ot/ot.go
pkg/watermark/ot/ot_test.go
pkg/window/keyed/keyed.go
pkg/window/keyed/keyed_test.go
pkg/window/strategy/fixed/fixed.go
pkg/window/strategy/fixed/fixed_test.go
pkg/window/windower.go

chore: minor window refactor

---

pkg/apis/numaflow/v1alpha1/pipeline_types.go

fix(controller): vertex nil check for edge listing. Fixes #352

---

pkg/pbq/pbqmanager.go
pkg/reduce/readloop/ordered.go
pkg/reduce/readloop/readloop.go
pkg/reduce/reduce.go

context handling to ensure that all the read messages are successfully written and acked.

fix: context handling for persistence and ack

---

pkg/pbq/store/wal/bootstrap.go
pkg/pbq/store/wal/options.go
pkg/pbq/store/wal/segment.go
pkg/pbq/store/wal/segment_test.go
pkg/pbq/store/wal/stores.go
pkg/udf/reduce_udf.go

feat: added batch sync for WAL

feat: added batch sync for WAL

---

pkg/reduce/readloop/readloop.go
pkg/watermark/publish/publisher.go

Fixes: #371 
Process all the successful entries returned by the previous step in the subsequent steps.

fix: best effort processing during SIGTERM. Closes #371

---

pkg/isb/forward/forward.go
pkg/reduce/readloop/readloop.go

chore: concurrent acks inside readloop

---

pkg/sources/generator/tickgen.go

Since tickgen ID is based on time, during load tests, we are seeing duplicates

chore: make tickgen ID unique

---

docs/specifications/overview.md
docs/user-guide/user-defined-functions.md
docs/user-guide/watermarks.md
pkg/sources/generator/tickgen_test.go

chore(docs): update docs

---

pkg/pbq/pbq.go
pkg/pbq/pbqmanager.go
pkg/pbq/pbqmanager_test.go
pkg/pbq/store/interfaces.go
pkg/pbq/store/memory/store.go
pkg/pbq/store/memory/stores.go
pkg/pbq/store/memory/stores_test.go
pkg/pbq/store/noop/store.go
pkg/pbq/store/noop/stores.go
pkg/pbq/store/wal/metrics.go
pkg/pbq/store/wal/segment.go
pkg/pbq/store/wal/stores.go
pkg/pbq/store/wal/stores_test.go

- removing GC from the Store interface
- adding DeleteStore to StoreProvider
- tests for StoreProvider

chore: adding DeleteStore method to store provider interface

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/reduce/reduce.go
pkg/reduce/reduce_test.go
pkg/sinks/logger/log.go
pkg/udf/reduce_udf.go

chore:non keyed stream support for reduce

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/apis/numaflow/v1alpha1/vertex_types_test.go
pkg/reconciler/vertex/controller.go

chore: default logs to user defined containers if there are. Close #283

---

pkg/reconciler/pipeline/validate.go
pkg/reconciler/pipeline/validate_test.go

chore: add pipeline and vertex name validation. Closes #342

---

Makefile

fix(test): e2e-api-pod can not start on M1 mac

---

pkg/reduce/readloop/readloop.go
pkg/reduce/readloop/readloop_test.go
pkg/window/strategy/fixed/fixed.go
pkg/window/strategy/fixed/fixed_test.go
pkg/window/windower.go

chore: Windower interface refactor

---

.github/workflows/ci.yaml
Makefile
pkg/daemon/server/daemon_server.go
pkg/isb/stores/jetstream/reader.go
pkg/isb/stores/jetstream/reader_test.go
pkg/isb/stores/jetstream/writer.go
pkg/isb/stores/jetstream/writer_test.go
pkg/isbsvc/jetstream_service.go
pkg/shared/clients/nats/default_jetstream_client.go
pkg/shared/clients/nats/doc.go
pkg/shared/clients/nats/in_cluster_jetstream_client.go
pkg/shared/clients/nats/interface.go
pkg/shared/clients/nats/jetstream_context.go
pkg/shared/clients/nats/nats_conn.go
pkg/shared/clients/nats/options.go
pkg/shared/clients/nats/test/client.go
pkg/shared/clients/nats/test/server.go
pkg/sinks/sink.go
pkg/sources/nats/nats_test.go
pkg/sources/source.go
pkg/udf/common.go
pkg/watermark/fetch/offset_timeline_test.go
pkg/watermark/fetch/processor_heartbeat_test.go
pkg/watermark/fetch/processor_manager_test.go
pkg/watermark/fetch/processor_to_fetch_test.go
pkg/watermark/generic/jetstream/generic.go
pkg/watermark/publish/publisher_test.go
pkg/watermark/store/jetstream/kv_store.go
pkg/watermark/store/jetstream/kv_watch.go

refactor: nats/jetstream testing

---

pkg/pbq/store/wal/metrics.go
pkg/pbq/store/wal/segment.go

Signed-off-by: Hao Hao <xdevxhao@gmail.com>
Update the WAL metrics `entriesBytesCount` to track throughput, and adding WAL message encoding latency metric.

chore: update PBQ WAL metrics

---

pkg/reduce/readloop/ordered.go
pkg/reduce/readloop/ordered_test.go
pkg/reduce/readloop/readloop.go
pkg/reduce/readloop/readloop_test.go
pkg/reduce/reduce.go
pkg/reduce/reduce_test.go
pkg/udf/reduce_udf.go

The context passed to `forwardAChunk` will never be canceled in an error loop scenario

chore: refactor reduce ctx

---

pkg/sources/nats/nats_test.go

chore: flaky test Test_Multiple

---

pkg/reduce/readloop/ordered.go
pkg/reduce/readloop/ordered_test.go
pkg/reduce/readloop/readloop.go

optimization to the ordered loop so that queueing and dequeuing continues to stay at O(1). 
we can delay the enqueuing of the task until the close of the book as the desired order is guaranteed.

chore: optimizing ordered loop

---

.github/workflows/ci.yaml
test/fixtures/http_expect.go
test/reduce-e2e/reduce_test.go
test/reduce-e2e/testdata/simple-keyed-reduce-pipeline.yaml

chore: flaky reduce e2e tests

---

test/e2e-api/http.go
test/e2e-api/redis.go
test/e2e/functional_test.go
test/e2e/testdata/filtering.yaml
test/fixtures/e2e_suite.go
test/fixtures/http_send.go
test/fixtures/when.go
test/http-e2e/http_test.go
test/http-e2e/testdata/http-source-with-auth.yaml
test/http-e2e/testdata/http-source.yaml
test/nats-e2e/nats_test.go
test/nats-e2e/testdata/nats-source-pipeline.yaml
test/reduce-e2e/reduce_test.go
test/sdks-e2e/sdks_test.go

* Enable specifying headers when sending messages in e2e tests.
* Apply new e2e testing approach to more existing test cases.

chore: apply new e2e testing approach to more existing test cases

---

test/e2e/functional_test.go
test/fixtures/e2e_suite.go
test/http-e2e/http_test.go
test/nats-e2e/nats_test.go
test/reduce-e2e/reduce_test.go

Signed-off-by: Keran Yang <yangkr920208@gmail.com>

refactor: move redis sink resources creation to E2ESuite

---

docs/specifications/edges-and-buffers.md
mkdocs.yml

docs: edges and buffers

---

test/e2e/functional_test.go
test/fixtures/http_send.go
test/http-e2e/http_test.go
test/reduce-e2e/reduce_test.go
test/sdks-e2e/sdks_test.go

refactor: simplify http request construction in test cases

---

docs/user-guide/user-defined-functions/reduce/windowing/fixed.md
docs/user-guide/user-defined-functions/reduce/windowing/sliding.md
docs/user-guide/user-defined-functions/reduce/windowing/windowing.md

docs: revise on windowing docs

---

.github/workflows/release.yml
Makefile

[Software bill of materials (SBOM)](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom)
This PR implements container images and SBOM to be signed using `sigstore/cosign`. 
https://docs.sigstore.dev/cosign/git_support
1. [Install Cosign](https://docs.sigstore.dev/cosign/installation) on your local. Run the command `cosign version` to verify it has been installed correctly.
2. Create or have a valid GitHub PAT token available.
3. Export your PAT as the environment variable "GITHUB_TOKEN"
4. Execute `cosign generate-key-pair github://numaproj/numaflow` This will start the process of creating the GitHub Secrets automatically for you, and prompt you to enter a password.  This Password will be stored as the Github secret `COSIGN_PASSWORD`. A well respected password …

chore: sign container images and assets (sbom)

---

Dockerfile
Makefile
docs/development/debugging.md

chore: use alpine for dev image

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/window/keyed/keyed.go

chore: set DefaultPBQChannelBufferSize to 100 from 10,000

---

docs/user-guide/user-defined-functions/reduce/windowing/sliding.md
pkg/reduce/readloop/readloop.go
pkg/window/strategy/sliding/sliding.go
pkg/window/strategy/sliding/sliding_test.go

chore: fix sliding start strategy and minor optimizations

---

docs/development/debugging.md
pkg/apis/numaflow/v1alpha1/const.go
pkg/metrics/metrics.go

chore: enable pprof independently of debug flag

---

pkg/reduce/readloop/readloop.go
pkg/window/strategy/fixed/fixed.go
pkg/window/strategy/fixed/fixed_test.go
pkg/window/strategy/sliding/sliding.go
pkg/window/strategy/sliding/sliding_benchmark_test.go
pkg/window/strategy/sliding/sliding_test.go

chore: optimise remove windows, adding test

---

pkg/reduce/pbq/partition/partition.go
pkg/reduce/pbq/pbq_test.go
pkg/reduce/pbq/pbqmanager_test.go
pkg/reduce/pbq/store/memory/store_test.go
pkg/reduce/pbq/store/memory/stores_test.go
pkg/reduce/pbq/store/wal/bootstrap.go
pkg/reduce/pbq/store/wal/segment.go
pkg/reduce/pbq/store/wal/segment_test.go
pkg/reduce/pbq/store/wal/stores.go
pkg/reduce/pbq/store/wal/stores_test.go
pkg/reduce/pnf/processandforward.go
pkg/reduce/pnf/processandforward_test.go
pkg/reduce/readloop/readloop.go
pkg/reduce/readloop/readloop_test.go
pkg/udf/function/uds_grpc.go
pkg/udf/function/uds_grpc_test.go
pkg/window/keyed/keyed.go
pkg/window/keyed/keyed_test.go
pkg/window/windower.go
test/fixtures/when.go

chore: key to slot for managing hash range of keys

---

test/sdks-e2e/sdks_test.go
test/sdks-e2e/testdata/transformer/event-time-filter-go.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-java.yaml

Signed-off-by: Keran Yang <yangkr920208@gmail.com>

chore: add an e2e test case for source transformer java sdk

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/sinks/sink.go
pkg/sources/source.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go

Added an environment variable to disable health check on the user defined containers. Not publishing any doc about it, should revisit it later to see if we should officially support it.

chore: optional user defined container health check

---

go.mod
go.sum
pkg/apis/numaflow/v1alpha1/container_template.go
pkg/apis/numaflow/v1alpha1/container_template_test.go
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service_test.go
pkg/apis/numaflow/v1alpha1/pipeline_types_test.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/reconciler/pipeline/controller_test.go

fix: securityContext not applied to container templates

---

pkg/watermark/fetch/offset_timeline.go
pkg/watermark/fetch/offset_timeline_test.go
pkg/watermark/fetch/processor_manager.go

Add a separate put offset timeline function for assumed idle watermark

feat: Offset time idle watermark put

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/cluster-install/rbac/controller-manager/numaflow-cluster-role.yaml
config/install.yaml
config/namespace-install.yaml
config/namespace-install/rbac/controller-manager/numaflow-role.yaml
pkg/isb/stores/simplebuffer/options.go
pkg/metrics/health_checker.go
pkg/reconciler/cmd/start.go
pkg/reconciler/isbsvc/controller.go
pkg/reconciler/isbsvc/controller_test.go
pkg/reconciler/isbsvc/installer/installer.go
pkg/reconciler/isbsvc/installer/installer_test.go
pkg/reconciler/isbsvc/installer/jetstream.go
pkg/reconciler/isbsvc/installer/jetstream_test.go
pkg/reconciler/isbsvc/installer/native_redis.go
pkg/reconciler/isbsvc/installer/native_redis_test.go
pkg/reduce/metrics.go
pkg/reduce/pbq/metrics.go
pkg/reduce/pbq/store/memory/stores_test.go
pkg/reduce/pbq/store/wal/stores_test.go
pkg/reduce/pnf/metrics.go
pkg/reduce/readloop/metrics.go
pkg/reduce/readloop/readloop_test.go
pkg/window/strategy/sliding/sliding_benchmark_test.go

Giving Secret watch privilege is kind of sensitive to some users, this PR remove the secret watch dependency from the controller.

feat: remove secret watch privilege dependency

---

config/advanced-install/numaflow-server.yaml
config/cluster-install/rbac/numaflow-server/numaflow-server-cluster-role.yaml
config/install.yaml
config/namespace-install.yaml
config/namespace-install/rbac/numaflow-server/numaflow-server-role.yaml
server/apis/v1/handler.go
server/cmd/start.go
server/routes/routes.go

chore: clean up unused routes and rbac

---

docs/development/debugging.md

Closes: https://github.com/numaproj/numaflow/issues/479

docs: debug with tracing

---

ui/src/components/pipeline/graph/CustomEdge.css
ui/src/components/pipeline/graph/CustomEdge.tsx

Fixing styling of edge label so as to get a consistent view across pipelines

chore: edge label

---

pkg/forward/forward_test.go
pkg/isb/message.go
pkg/isb/serde.go
pkg/isb/serde_test.go
pkg/isb/stores/jetstream/writer_test.go
pkg/isb/stores/redis/write_test.go
pkg/isb/testutils/rw.go
pkg/isb/testutils/udf.go
pkg/reduce/data_forward_test.go
pkg/reduce/pbq/store/wal/segment_test.go
pkg/reduce/pnf/processandforward_test.go
pkg/reduce/readloop/readloop_test.go
pkg/sinks/kafka/kafka_test.go
pkg/sources/generator/tickgen.go
pkg/sources/http/http.go
pkg/sources/kafka/reader.go
pkg/sources/nats/nats.go
pkg/sources/transformer/grpc_transformer.go
pkg/sources/transformer/grpc_transformer_test.go
pkg/udf/function/uds_grpc.go
pkg/udf/function/uds_grpc_test.go

Repurpose PaneInfo for other use cases.

chore: refactor PaneInfo and add MessageType

---

pkg/forward/forward.go
pkg/forward/forward_test.go
pkg/isb/message.go
pkg/isb/serde_test.go
pkg/reduce/data_forward_test.go
pkg/reduce/pnf/processandforward.go
pkg/reduce/pnf/processandforward_test.go
pkg/reduce/readloop/readloop.go
pkg/sources/generator/tickgen.go
pkg/sources/http/http.go
pkg/sources/kafka/reader.go
pkg/sources/nats/nats.go
pkg/watermark/fetch/edge_fetcher.go
pkg/watermark/fetch/edge_fetcher_test.go
pkg/watermark/fetch/interface.go
pkg/watermark/fetch/processor_manager.go
pkg/watermark/fetch/processor_manager_inmem_test.go
pkg/watermark/fetch/processor_manager_test.go
pkg/watermark/fetch/source_fetcher.go
pkg/watermark/generic/noop.go
pkg/watermark/processor/entity.go
pkg/watermark/processor/entity_test.go
pkg/watermark/publish/publisher.go
pkg/watermark/publish/publisher_inmem_test.go
pkg/watermark/publish/publisher_test.go
pkg/watermark/wmb/watermark.go
pkg/watermark/wmb/wmb.go
pkg/watermark/wmb/wmb_test.go

The current ot.Value has been refactored (rearranged) to look like a WMB.

chore: refactor current OT Value to Watermark Barrier.

---

pkg/reduce/data_forward_test.go
pkg/reduce/pbq/pbq.go

chore: fix data race in reduce tests

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/cluster-install/rbac/controller-manager/numaflow-cluster-role.yaml
config/install.yaml
config/namespace-install.yaml
config/namespace-install/rbac/controller-manager/numaflow-role.yaml
docs/operations/installation.md
pkg/apis/numaflow/v1alpha1/const.go
pkg/reconciler/cmd/start.go
pkg/reconciler/vertex/scaling/scaling.go
test/manifests/kustomization.yaml

feat: enable controller HA

---

pkg/shuffle/shuffle_test.go

* Refactor existing shuffle unit tests.
* Add some more unit tests for the recent change of using vertex name as the seed.

chore: update shuffle unit tests

---

Makefile
config/advanced-install/namespaced-controller-wo-crds.yaml
config/advanced-install/namespaced-numaflow-server.yaml
config/advanced-install/namespaced-numaflow-server/kustomization.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
go.mod
go.sum

Also upgraded nats client lib and enabled latest nats image.

chore: added namespaced installation manifests for UX server

---

pkg/reconciler/vertex/controller.go

Vertex controller updates `status.replicas` before the pod creation/deletion is done, which gives wrong information when pod operation fails, and it makes operations like autoscaling do incorrect judgement based on incorrect real pod numbers.

fix: do not update status.replicas until pod operation succeeds

---

examples/7-reduce-sliding-window.yaml
pkg/isb/stores/jetstream/reader.go

Fixes: #630
Pending messages for autoscaling calculation should exclude ack pending.

fix: exclude ack pending messages

---

pkg/forward/forward_test.go
pkg/isb/stores/simplebuffer/buffer.go

fix: IdleWatermark unit test

---

pkg/forward/forward_test.go
pkg/isb/stores/jetstream/writer.go
pkg/reconciler/cmd/start.go
pkg/reconciler/vertex/scaling/scaling.go
pkg/reconciler/vertex/scaling/scaling_test.go
pkg/reduce/pnf/metrics.go
pkg/reduce/pnf/processandforward.go
pkg/reduce/pnf/processandforward_test.go
pkg/reduce/readloop/ordered.go

* Enable BufferFullWritingStrategy for reduce data forwarder.
* Re-write BufferFullWritingStrategy unit tests for map data forwarder.
* Fix minor typos.
Closes #524

chore: enable BufferFullWritingStrategy for reduce data forwarder

---

docs/user-guide/sources/redis-source.md
mkdocs.yml
test/redis-source-e2e/testdata/redis-source-pipeline-from-beginning.yaml
test/redis-source-e2e/testdata/redis-source-pipeline-from-end.yaml

Add a doc for how to use Redis Streams Source.

docs: add Redis Streams Source doc

---

pkg/reduce/data_forward_test.go
pkg/watermark/store/inmem/kv_watch.go

fixes https://github.com/numaproj/numaflow/issues/652

fix: unit test

---

server/apis/interface.go
server/apis/v1/handler.go
server/routes/routes.go
ui/src/components/namespaces/Namespaces.tsx
ui/src/utils/fetchWrappers/namespaceListFetch.ts

Closes #606 
enhanced the namespace search bar to provide incremental search
provided a view of all available cluster namespaces on the search dropdown

feat: incremental search and namespace preview in search bar

---

pkg/metrics/metrics.go
pkg/reconciler/vertex/scaling/scaling.go
pkg/sources/kafka/reader.go

closes #642 
When source Kafka topic has multiple partitions and user is sending very few messages, there can be cases when some of the partitions are empty.
For partitions that are empty (let's call those idle partitions), `sarama.ClusterAdmin` `ListConsumerGroupOffsets` API returns us block offset of `-1` to indicate there is no offset associated with that specific partition. Meanwhile when we call `r.saramaClient.GetOffset(r.topic, partition, sarama.OffsetNewest)` to get the newest available offset for idle partitions, it returns us 0. Eventually when we calculate total pending messages using `totalPending += partitionOffset - block.Offset`, for idle partitions, we are always counting (0-(-1)=) 1 for each idle partitions.
Therefore even if we have no input messages at all, if input …

fix: skip empty Kafka partitions when calculating pending count

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
docs/APIs.md
docs/user-guide/kustomize/kustomize.md
docs/user-guide/user-defined-functions/reduce/reduce.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/apis/numaflow/v1alpha1/openapi_generated.go
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/metrics/metrics.go
pkg/shared/clients/nats/nats_conn.go
pkg/shared/queue/overflow_queue.go
pkg/sinks/kafka/kafka.go
pkg/sources/kafka/reader.go
pkg/watermark/publish/publisher.go

chore: fix typos and update Kafka reader pending count comments

---

docs/operations/metrics/metrics.md
docs/user-guide/sources/redis-source.md
pkg/isb/stores/redis/read.go
pkg/shared/clients/redis/redis_reader.go
pkg/sources/redisstreams/metrics.go
pkg/sources/redisstreams/redisstream.go
pkg/sources/redisstreams/redisstream_test.go
test/redis-streams-e2e/redis_streams_test.go

Fixes #662 
Also:
1. Use the incoming ID as the published Event Time. 
2. Document metrics

feat: Redis Streams source fixes

---

config/advanced-install/namespaced-numaflow-server.yaml
config/advanced-install/numaflow-server.yaml
config/base/numaflow-server/numaflow-server-deployment.yaml
config/install.yaml
config/namespace-install.yaml
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/metrics/metrics.go
server/routes/routes.go
server/routes/routes_test.go
ui/src/utils/fetchWrappers/podsFetch.test.ts

Current liveness probe is too aggressive, update it to a more reasonable config.

chore: update liveness probe config for vertex pods

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/metrics/metrics.go
pkg/sinks/sink.go
pkg/sources/source.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go

Remove the health check from the `numa` container to udf/udsink containers as it does not work as expected.
If the liveness check on `numa` container fails, it only restarts the `numa` container, the udf container stays as is.

chore: remove health check to udf/udsink containers

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/apis/numaflow/v1alpha1/sink.go
pkg/apis/numaflow/v1alpha1/sink_test.go
pkg/apis/numaflow/v1alpha1/source.go
pkg/apis/numaflow/v1alpha1/source_test.go
pkg/apis/numaflow/v1alpha1/udf.go
pkg/apis/numaflow/v1alpha1/udf_test.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/metrics/metrics.go
pkg/sinks/sink.go
pkg/sources/source.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go

Closes: #675 
1. Expose a new endpoint through the `numa` container, which is dedicated for sidecar health check, and configure liveness probes for all the sidecars.
2. Original `numa` container liveness check simply tells its own status.

chore: enable liveness check for both numa and sidecar containers

---

Makefile
docs/development/releasing.md

chore: release script fix with bash

---

pkg/reduce/readloop/readloop.go

Even if a message is late, we can push it in as long as the window is open.

fix: allow late message as long as window is not closed

---

docs/user-guide/sources/transformer/overview.md
docs/user-guide/user-defined-functions/map/map.md
docs/user-guide/user-defined-functions/reduce/reduce.md
pkg/isb/stores/jetstream/reader.go

chore: update doc examples for map and mapT functions

---

config/apps/redis/redis-minimal.yaml
pkg/shared/clients/redis/redis_reader.go

chore: update Redis test image

---

Makefile

test: make Test* works for all e2e test cases

---

pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/daemon/server/service/pipeline_watermark_query.go
pkg/reconciler/pipeline/controller.go

chore: clean up legacy code for multi partitioned buckets

---

pkg/isb/serde.go
pkg/reduce/pbq/store/wal/segment_test.go

Fixes: https://github.com/numaproj/numaflow/issues/749

fix: use int32 for message length

---

pkg/forward/forward.go
pkg/forward/forward_test.go
pkg/forward/interfaces.go
pkg/forward/shutdown_test.go
pkg/isb/stores/jetstream/writer_test.go
pkg/isb/stores/redis/read_test.go
pkg/isb/stores/redis/write_test.go
pkg/reduce/data_forward.go
pkg/reduce/data_forward_test.go
pkg/reduce/pnf/ordered.go
pkg/reduce/pnf/ordered_test.go
pkg/reduce/pnf/processandforward.go
pkg/reduce/pnf/processandforward_test.go
pkg/shuffle/shuffle.go
pkg/sinks/blackhole/blackhole.go
pkg/sinks/blackhole/blackhole_test.go
pkg/sinks/kafka/kafka.go
pkg/sinks/kafka/kafka_test.go
pkg/sinks/logger/log.go
pkg/sinks/logger/log_test.go
pkg/sinks/udsink/sink.go
pkg/sources/generator/tickgen_test.go
pkg/sources/http/http_test.go
pkg/sources/kafka/handler_test.go
pkg/sources/nats/nats_test.go
pkg/sources/source.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go
pkg/watermark/publish/publisher.go

chore: some fixes

---

test/sdks-e2e/sdks_test.go
test/sdks-e2e/testdata/flatmap-stream.yaml

Closes https://github.com/numaproj/numaflow/issues/778

chore: enable map stream udf e2e test for python and java sdk

---

docs/user-guide/user-defined-functions/map/map.md

docs: map stream udf feature

---

pkg/sources/kafka/reader.go

fix: Intermittent failure from Kafka to get consumer offsets

---

pkg/udf/function/uds_grpc.go
pkg/udf/function/uds_grpc_test.go

Closes https://github.com/numaproj/numaflow/issues/745

chore: close the channel when context close in `ApplyReduce`

---

pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/reconciler/vertex/scaling/scaling.go

chore: partitions for source should always be 1

---

docs/specifications/edges-buffers-buckets.md
docs/user-guide/sources/transformer/builtin-transformers/README.md
docs/user-guide/sources/transformer/builtin-transformers/time-extraction-filter.md
docs/user-guide/sources/transformer/overview.md
docs/user-guide/user-defined-functions/reduce/examples.md
docs/user-guide/user-defined-functions/reduce/reduce.md
docs/user-guide/user-defined-functions/reduce/windowing/windowing.md
pkg/sources/transformer/builtin/time_extraction_filter/time_extraction_filter.go
pkg/sources/transformer/builtin/time_extraction_filter/time_extraction_filter_test.go
ui/src/utils/fetcherHooks/pipelineViewFetch.test.ts

 fix(docs): fixed some incorrect docs and renamed a timeExtractionFilter arg

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
docs/APIs.md
docs/core-concepts/inter-step-buffer-service.md
docs/operations/numaflow-controller-config.yaml
docs/user-guide/reference/configuration/max-message-size.md
mkdocs.yml
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/apis/numaflow/v1alpha1/openapi_generated.go
pkg/reconciler/isbsvc/installer/assets/jetstream/nats.conf
pkg/reconciler/isbsvc/installer/jetstream.go
pkg/sdkclient/sink/client/client.go
pkg/sdkclient/sink/client/options.go
pkg/sdkclient/udf/client/client.go
pkg/udf/builtin/builtin.go

TODO: update default gRPC max message size in sdks to 64 MB.

feat: capability to increase max message size

---

pkg/daemon/server/service/rater/helper.go
pkg/daemon/server/service/rater/helper_test.go
pkg/daemon/server/service/rater/rater.go
pkg/daemon/server/service/rater/timestamped_counts.go
pkg/daemon/server/service/rater/timestamped_counts_test.go

This PR does following cleanups.
1. Remove unused constants
2. Add more comments
3. Remove window-related codes
4. Remove some unit tests
Regarding 4, the reason of removing is that unit tests should focus on testing **what** instead of "how". Using `helper.go` as an example, within `helper.go`, `UpdateCount` and `CalculateRate` are **what** it does, while `getDeltaBetweenTimestampedCounts`, `calculatePartitionDelta` and `findStartIndex` are **how** it does. I removed all the unit tests that cover **how**.
Also closes #846 by removing the slope approach and keep using the delta aggregation approach to calculate rate.

chore: clean up for recent rater changes

---

pkg/reduce/data_forward.go
pkg/reduce/pbq/pbqmanager.go
pkg/reduce/pbq/pbqmanager_test.go
pkg/window/strategy/fixed/fixed.go
pkg/window/strategy/sliding/sliding.go
pkg/window/windower.go

fix: use windower to fetch next window yet to be closed

---

Makefile
config/extensions/webhook/kustomization.yaml

fix: release script for validating webhook

---

pkg/daemon/server/daemon_server.go

chore: enable pprof for daemon service

---

docs/user-guide/reference/multi-partition.md

doc: Update multi partition doc

---

docs/quick-start.md
docs/user-guide/reference/multi-partition.md
mkdocs.yml

- Improved the instructional language in the quick start guide.
- Corrected throughput limit upper bound in the multi-partitioned edges user guide reference.
- Included the multi-partitioned edges user guide reference in mkdocs.yml (so that it shows up on the left navigation).
Signed-off-by: Jason Zesheng Chen <jasonzeshengchen@gmail.com>

docs updates

---

pkg/shared/kvs/jetstream/kv_watch.go

fix: npe when the ctx is canceled inside kv watcher

---

docs/README.md
docs/core-concepts/inter-step-buffer-service.md
docs/core-concepts/inter-step-buffer.md
docs/core-concepts/pipeline.md
docs/core-concepts/vertex.md
docs/core-concepts/watermarks.md
docs/quick-start.md
docs/specifications/overview.md
docs/user-guide/use-cases/monitoring-and-observability.md
docs/user-guide/use-cases/overview.md
mkdocs.yml

- added a use case section with dedicated pages to different use cases
- rephrased ` Numaflow allows developers with basic knowledge of Kubernetes but without any special knowledge of data/stream processing to easily create massively parallel data/stream processing jobs using a programming language of their choice.` as `Numaflow allows developers without any special knowledge of data/stream processing to easily create massively parallel data/stream processing jobs using a programming language of their choice, with just basic knowledge of Kubernetes.`
- miscellaneous copy-edits (typos, grammar, etc)

docs: add a use case section

---

.github/workflows/ci.yaml
.github/workflows/gh-pages.yaml
.github/workflows/nightly-build.yml
.github/workflows/release.yml
Makefile
docs/development/development.md
go.mod
pkg/forward/forward.go
pkg/isbsvc/jetstream_service.go
pkg/reduce/data_forward.go
pkg/shared/clients/nats/nats_client.go
pkg/shared/kvs/jetstream/kv_store.go
pkg/shared/kvs/jetstream/kv_watch.go
pkg/sideinputs/initializer/initializer.go
pkg/sideinputs/synchronizer/synchronizer.go
pkg/watermark/generic/jetstream/generic.go
pkg/watermark/processor/processor_manager.go

1. go 1.20
2. Use `KV` for JetStream KV store, while bucket remains an internal concept.
3. Fixed some logging problem.

chore: go 1.20 and remove confusion between bucket and KV

---

pkg/sinks/udsink/sink.go

fix: send keys for udsink

---

pkg/watermark/store/jetstream/kv_watch.go

When no keys existing in the k/v, it throws errors.

fix: error when kv_watch with no keys

---

pkg/reduce/pbq/store/wal/bootstrap.go
pkg/reduce/pnf/ordered.go
pkg/shared/kvs/jetstream/kv_watch.go
pkg/sinks/udsink/udsink_grpc_test.go
pkg/sources/forward/data_forward.go
pkg/sources/generator/tickgen.go
pkg/sources/generator/tickgen_test.go
pkg/sources/http/http.go
pkg/sources/kafka/reader.go
pkg/sources/kafka/reader_test.go
pkg/sources/nats/nats.go
pkg/sources/redisstreams/redisstream.go
pkg/sources/source.go
pkg/sources/udsource/grpc_udsource_test.go
pkg/sources/udsource/user_defined_source.go
pkg/udf/rpc/grpc_map_test.go
pkg/udf/rpc/grpc_mapstream_test.go
pkg/udf/rpc/grpc_reduce_test.go

1. Remove retry on Ack.
For most of our existing sources, the Ack() functions return `return make([]error, len(offsets))`. The only exception is the RedisStream source, it uses `err := br.Client.XAck()` to batch acknowledge and populates the error array with the same err. Hence, for ALL sources, it's either ALL success or ALL failure and we don't need to retry acking.
2. Replace `err ==` with `errors.Is`.
3. Fix some typos and nit grammars as IntelliJ is giving me a lot of red lines :)
4. Remove some gRPC unit tests because I don't think they are necessary. The whole point of mocking a dependency is so that we don't worry about how the dependency constructs the returned value. Some of our gRPC unit tests are implementing the dependency and verifying the functionality of the …

chore: add some small refactors mainly for source

---

docs/user-guide/reference/configuration/pipeline-operations.md
mkdocs.yml

docs: how to pause/resume a pipeline

---

pkg/reconciler/vertex/controller.go

If any pod is under termination, make it faster to create a new one for replacement.

chore: ignore the ones being terminated when listing the vertex pods

---

Makefile
cmd/commands/daemon_server.go
cmd/commands/processor.go
cmd/commands/side_inputs_manager.go
server/cmd/start.go
version.go
webhook/cmd/start.go

fix: print version info when starting

---

test/sdks-e2e/sdks_test.go
test/sdks-e2e/testdata/flatmap-stream.yaml
test/sdks-e2e/testdata/flatmap.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-python.yaml

Enable e2e with new images supporting the SDK refactor

chore: enable python e2e

---

test/e2e-api/nats.go

chore: import packages only once

---

Makefile

fix(ci): Wrong test pod image tag used for running CI on release branch

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/cluster-install/rbac/controller-manager/numaflow-cluster-role.yaml
config/install.yaml
config/namespace-install.yaml
config/namespace-install/rbac/controller-manager/numaflow-role.yaml
pkg/reconciler/pipeline/controller.go
pkg/reconciler/pipeline/controller_test.go

chore: shorten job names to avoid being over limit

---

docs/user-guide/reference/configuration/istio.md
docs/user-guide/reference/pipeline-operations.md
docs/user-guide/sinks/user-defined-sinks.md
docs/user-guide/sources/transformer/overview.md
docs/user-guide/user-defined-functions/map/map.md
mkdocs.yml

docs: running on istio

---

server/apis/v1_1/handler.go
server/apis/v1_1/response_cluster_summary.go
server/apis/v1_1/response_isb_services.go
server/apis/v1_1/response_pipeline.go
server/routes/routes_v1_1.go

TODO: improvements and test for corner cases

feat: add api implementation

---

ui/src/App.tsx
ui/src/components/common/DebouncedSearchInput/index.tsx
ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Cluster/index.tsx
ui/src/components/pages/Cluster/partials/ClusterNamespaceListing/index.tsx
ui/src/components/pages/Cluster/partials/ClusterNamespaceListing/style.css
ui/src/utils/fetchWrappers/clusterSummaryFetch.ts

UI 1.0
- Debounced search input for reuse
- Update to SummaryPageLayout for dynamic content layout on summary size change
- Cluster namespace listing WIP (work in progress)

feat: namespace listing wip, debounced search input and summary dynamic layout updates

---

ui/src/setupProxy.js

Adding proxy for v1_1 APIs, to test UI changes locally without building the image

fix: adding proxy for v1_1 apis

---

server/apis/v1_1/handler.go
server/routes/routes_v1_1.go

@jy4096 @kohlisid, please separate health from Status string as we are doing today.

add health separately.

---

pkg/reconciler/pipeline/controller.go
pkg/reconciler/pipeline/controller_test.go

Fixes #991 
Currently if a user resumes a paused pipeline with a vertex that does not support autoscaling, the replica count for the vertex will always be 1 even if `spec.scale.min` is set greater than 1. This is because the work for scaling the vertex is expected to be done by an autoscaler. This is fixed by checking that a vertex is not scalable and has min set when resuming the pipeline to assure the correct replica count is set.

feat: set correct number of replices for some types of vertices after resuming pipeline

---

config/extensions/webhook/rbac/numaflow-webhook-cluster-role.yaml
config/validating-webhook-install.yaml

fix: wrong api group in webhook rbac settings

---

ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/SpecEditor/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx
ui/src/types/declarations/pipeline.d.ts
ui/src/utils/fetchWrappers/piplelineVertexMetricsFetch.ts

feat: vertex details sidebar processing rates

---

pkg/shared/util/kubeconfig.go
server/apis/v1/handler.go
test/fixtures/e2e_suite.go
webhook/cmd/start.go

refactor: shared kubeconfig util

---

ui/src/components/common/StatusIndicator/StatusIndicator.tsx
ui/src/components/pages/Namespace/index.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/types/declarations/namespace.d.ts
ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts

Pipelines page

---

ui/src/App.tsx
ui/src/components/common/SlidingSidebar/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/Buffers/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx
ui/src/utils/fetchWrappers/systemInfoFetch.ts
ui/src/utils/fetcherHooks/podsViewFetch.ts

- updated remaining api endpoints to v1_1
- added buffer info for non-source vertices

feat: add buffer info in vertex side panel

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/PipelinesTypes.ts
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/types/declarations/namespace.d.ts
ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts

fix: sorting and filtering fixes

---

ui/src/components/common/SlidingSidebar/partials/EdgeDetails/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx

node and edge sidebar data from graph

fix: node and edge sidebar data from graph

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

fix: styling and sorting fixes

---

ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/style.css

Pipeline icon and removed pill from isb type.

fix: pipeline icon and removed pill from isb type

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx

fix: pipeline sort button spacing

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx

Pipeline filters comparison fix.

fix: pipeline filters comparison fix

---

ui/src/components/pages/Pipeline/partials/PipelineISBStatus/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineStatus/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineSummaryStatus/index.tsx
ui/src/components/pages/Pipeline/style.css

- pipeline summary style fixes

fix(SERVER): apply style fixes to pipeline summary

---

Makefile
SECURITY.md

Fixes #1079 
Adds https://github.com/lycheeverse/lychee for markdown docs

feat: add doc link checker

---

.github/workflows/ci.yaml

chore: disable ui test

---

docs/core-concepts/watermarks.md
docs/development/development.md
docs/development/releasing.md
docs/operations/installation.md
docs/specifications/edges-buffers-buckets.md
docs/specifications/overview.md
docs/user-guide/reference/conditional-forwarding.md
docs/user-guide/reference/multi-partition.md
docs/user-guide/reference/side-inputs.md
docs/user-guide/sinks/overview.md
docs/user-guide/sinks/user-defined-sinks.md
docs/user-guide/sources/overview.md
docs/user-guide/sources/user-defined-sources.md
docs/user-guide/user-defined-functions/map/map.md
docs/user-guide/user-defined-functions/reduce/reduce.md
mkdocs.yml

docs: add documentations for udsource

---

ui/package.json
ui/src/components/common/SlidingSidebar/partials/Errors/index.tsx
ui/src/components/common/SlidingSidebar/partials/GeneratorDetails/index.tsx
ui/src/components/pages/Cluster/index.tsx
ui/src/components/pages/Namespace/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/SearchablePodsHeatMap/partials/PodsHeatMap/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineISBStatus/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineSummaryStatus/index.tsx
ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts
ui/src/utils/index.ts

- fix all summary to caps
- set width do max lag so that it wont change the layout when value changes
- fix unused variables warnings

fix(SERVER): remove unused vars and misc fixes

---

ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Pipeline/index.tsx

fix(SERVER): fix key warning

---

ui/src/App.tsx
ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineISBStatus/index.tsx
ui/src/components/pages/Pipeline/partials/PipelineStatus/index.tsx
ui/src/types/declarations/pipeline.d.ts
ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts
ui/src/utils/index.ts

- add UNKNOWN state when status section is not found in a spec
-

fix(SERVER): handle states when status is unknown

---

pkg/reconciler/vertex/scaling/scaling.go

fix: not considered as back pressured when onFull is discardLatest

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

fix: sorting issue fix and arrow icon for navigating to namespace

---

ui/src/components/common/DebouncedSearchInput/index.tsx
ui/src/components/common/SlidingSidebar/index.tsx
ui/src/components/common/SlidingSidebar/partials/ISBUpdate/index.tsx
ui/src/components/common/SlidingSidebar/partials/ISBUpdate/style.css
ui/src/components/common/SpecEditor/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

- ISB Update implemented
- Search input style update

feat: isb update implemented and search input styling

---

.github/workflows/ci.yaml
Makefile
docs/quick-start.md
docs/user-guide/sources/transformer/overview.md
examples/10-cycle-to-prev.yaml
examples/10-cycle-to-self.yaml
examples/11-join-on-reduce.yaml
examples/11-join-on-sink.yaml
examples/2-even-odd-pipeline.yaml
examples/6-reduce-fixed-window.yaml
examples/7-reduce-sliding-window.yaml
test/diamond-e2e/testdata/cycle-backward.yaml
test/diamond-e2e/testdata/cycle-to-self.yaml
test/diamond-e2e/testdata/join-on-sink.yaml
test/e2e/testdata/even-odd.yaml
test/reduce-e2e/testdata/complex-reduce-pipeline.yaml
test/reduce-e2e/testdata/complex-sliding-window-pipeline.yaml
test/reduce-e2e/testdata/join-on-map-pipeline.yaml
test/reduce-e2e/testdata/join-on-reduce-pipeline.yaml
test/reduce-e2e/testdata/simple-keyed-reduce-pipeline.yaml
test/reduce-e2e/testdata/simple-non-keyed-reduce-pipeline.yaml
test/reduce-e2e/testdata/simple-reduce-pipeline-wal.yaml
test/sdks-e2e/testdata/flatmap-stream.yaml
test/sdks-e2e/testdata/flatmap.yaml
test/sdks-e2e/testdata/simple-keyed-reduce-pipeline.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-go.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-java.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-python.yaml

* Also add a link checker to the CI.
* I chose to check the test folder because the developers uses the link, docs numaflow users.

chore: update broken links

---

docs/user-guide/reference/join-vertex.md

Fixes #1071
As part of Hactoberfest 2023 we are fixing the issue: https://github.com/numaproj/numaflow/issues/1071 to improve Documentation for Join-Vertex. Referring from this [blog](https://blog.numaproj.io/from-trees-to-directed-graphs-4e59f0463cfc) added more relevant information around Join Vertex and the latest changes as part of v0.10 update.

docs: update to add join vertex and v0.10 changes

---

docs/user-guide/reference/join-vertex.md

doc: minor clean up of JOIN doc

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx
ui/src/types/declarations/graph.d.ts
ui/src/utils/index.ts

Pipelines Page
List of pipelines page

Pause resume for pipelines

---

USERS.md

Adding BCubed to user list for Numaflows

added BCubed to the user list

---

ui/src/App.tsx
ui/src/components/common/ErrorDisplay/index.tsx
ui/src/components/common/ErrorDisplay/style.css
ui/src/components/common/SlidingSidebar/index.tsx
ui/src/components/common/SlidingSidebar/partials/CloseModal/index.tsx
ui/src/components/common/SlidingSidebar/partials/ISBCreate/index.tsx
ui/src/components/common/SlidingSidebar/partials/ISBUpdate/index.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineCreate/index.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineUpdate/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/VertexUpdate/index.tsx
ui/src/components/common/SpecEditor/index.tsx
ui/src/components/common/SpecEditor/style.css
ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Cluster/index.tsx
ui/src/components/pages/Namespace/index.tsx
ui/src/components/pages/Namespace/partials/DeleteModal/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/types/declarations/pipeline.d.ts
ui/src/utils/fetchWrappers/pipelineUpdateFetch.ts

- Updates spec CRUD with status/flow updates
- Adds consistent error and loading display

feat: crud updates and error/loading handling

---

docs/quick-start.md

chore: quick start format fix

---

ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx

https://github.com/numaproj/numaflow/assets/4667739/e35a888b-4abe-45cf-8fb1-366ba104e4fc

fix: fixed the timing issue on resume and pause

---

ui/src/components/pages/Pipeline/partials/Graph/index.tsx

fix: overridden changes re-merge

---

ui/src/components/common/StatusCounts/StatusCounts.tsx
ui/src/components/common/StatusCounts/style.css

fix: updated image styles to a class

---

ui/src/components/pages/Namespace/partials/PipelineCard/index.test.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

feat: added unit tests for PipelineCard component

---

ui/src/components/common/StatusCounts/StatusCounts.tsx

It adds a key for react to performantly edit an element rendered inside of a loop

Namespace card status bar changes 0.11

---

docs/user-guide/sinks/blackhole.md

docs: Update blackhole.md

---

server/cmd/start.go
ui/src/App.tsx
ui/src/components/pages/Login/index.tsx
ui/src/components/pages/Login/style.css

Login page skeleton

---

ui/src/App.tsx

fix: route fix

---

ui/src/App.tsx
ui/src/components/common/AccountMenu/index.tsx
ui/src/components/pages/Login/index.tsx
ui/src/types/declarations/app.d.ts

- base work for user context in app
- account menu added

feat: user info context and account menu

---

pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/side_inputs.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/vertex/controller.go

This is to make istio be able to pick a proper name to expose metrics.

chore: add app.kubernetes.io/name label

---

server/apis/v1/handler.go
server/routes/routes.go
ui/src/App.tsx
ui/src/components/common/AccountMenu/index.tsx
ui/src/components/pages/Login/index.tsx
ui/src/components/pages/Login/style.css

- login and callback integration with UI
- Logout API and UI integration
- AuthInfo API and UI integration

feat: callback handling in login

---

ui/src/App.tsx
ui/src/components/pages/Namespace/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/utils/index.ts

- Updates to support NS installation mode
- General cleanup

fix: clean up and ns installation fixes

---

ui/src/components/common/StatusCounts/StatusCounts.tsx
ui/src/components/common/StatusCounts/style.css

fix: updated div's with box and removed unwanted css

---

ui/src/components/pages/Login/index.tsx
ui/src/components/pages/Login/style.css

Div to box update ged

---

ui/src/components/pages/Namespace/partials/DeleteModal/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

- pipeline name clickable to load pipeline
- delete pipeline failure error msg update

fix: pipeline name click and delete error message

---

cmd/commands/server.go
server/apis/v1/handler.go
server/cmd/start.go
server/routes/routes.go

args for disableAuth, dexServerAddr, etc

---

ui/src/components/pages/Login/index.tsx
ui/src/components/pages/Login/style.css

fix: fixed the background height to suit smaller screens

---

ui/src/components/common/AccountMenu/index.tsx

Updates user icon in top right from initial to "log out".

fix: user info icon updated to display name

---

ui/src/components/pages/Pipeline/partials/Graph/Graph.test.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx

This PR is for adding unit tests for the graph page

Unit tests graph page

---

ui/src/components/common/SlidingSidebar/index.tsx
ui/src/components/pages/Namespace/partials/DeleteModal/index.tsx
ui/src/utils/fetchWrappers/fetch.ts
ui/src/utils/fetcherHooks/pipelineViewFetch.ts

- Try again button on delete pipeline/isb error
- 403 error message updates for GET calls

fix: try again for delete and updated 403 messages

---

server/apis/v1/handler.go
test/api-e2e/api_test.go

Update test cases for previous PR #1199

test: update isbsvc tests for getting current status

---

docs/operations/security.md
mkdocs.yml

High level security details on Numaflow controller and Data plane.

doc: Numaflow high level security

---

server/apis/v1/response.go
server/apis/v1/response_cluster_summary.go
server/apis/v1/response_isb_services.go
server/apis/v1/response_k8s_events.go
server/apis/v1/response_pipeline.go

chore: add header

---

ui/src/components/common/SlidingSidebar/partials/CloseModal/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/CloseModal/index.tsx
ui/src/components/common/SlidingSidebar/partials/EdgeDetails/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/Errors/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/GeneratorDetails/index.test.tsx

fix: more sidebar tests

---

ui/src/utils/gradient.test.ts

fix(SERVER): update gradient test

---

docs/user-guide/reference/autoscaling.md

fix(doc): hpa api version

---

ui/src/components/common/SlidingSidebar/partials/GeneratorDetails/partials/GeneratorUpdate/index.test.tsx

fix: generatorupdate unit test

---

Makefile

fix: incorrect image version for  namespaced numaflow-server

---

ui/src/components/common/SlidingSidebar/partials/K8sEvents/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/K8sEvents/index.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineCreate/index.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineUpdate/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/VertexUpdate/index.test.tsx

fix: more sidebar testing

---

ui/src/components/common/SlidingSidebar/partials/K8sEvents/index.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx
ui/src/components/pages/Cluster/partials/ClusterNamespaceListing/index.tsx
ui/src/components/pages/Cluster/partials/NamespaceCard/style.css
ui/src/components/pages/Namespace/index.tsx
ui/src/components/pages/Pipeline/index.tsx
ui/src/types/declarations/namespace.d.ts
ui/src/utils/fetchWrappers/namespaceK8sEventsFetch.ts

- Adds pipeline and vertex filtering to k8s events views

feat: k8s events filtering and cluster summary card fixes 

---

ui/src/components/pages/Pipeline/partials/Graph/index.tsx

This fixes the timer not clearing issue

fix: fixed the timer not clearing issue

---

pkg/daemon/server/service/pipeline_metrics_query.go
pkg/daemon/server/service/rater/doc.go
pkg/daemon/server/service/rater/helper.go
pkg/daemon/server/service/rater/helper_test.go
pkg/daemon/server/service/rater/options.go
pkg/daemon/server/service/rater/pod_tracker.go
pkg/daemon/server/service/rater/pod_tracker_test.go
pkg/daemon/server/service/rater/rater.go
pkg/daemon/server/service/rater/rater_test.go
pkg/daemon/server/service/rater/timestamped_counts.go
pkg/daemon/server/service/rater/timestamped_counts_test.go
pkg/daemon/server/service/rater/uniq_str_list.go
pkg/daemon/server/service/rater/uniq_str_list_test.go
pkg/forward/doc.go

* rename the package from server to rater.
* add doc.go
* let pod tracker own parsing the pod key to pod information, the rater doesn't need to know how to parse a key using separator

chore: update rater package name

---

config/advanced-install/numaflow-server.yaml
config/cluster-install/rbac/numaflow-server/numaflow-server-cluster-role.yaml
config/install.yaml
server/apis/v1/handler.go
server/apis/v1/response_cluster_summary.go
test/api-e2e/api_test.go

If a namespace is empty, meaning it has neither pipeline nor ISBSVC, we still include it in the cluster summary response.
This change also introduces a flag `isEmpty` to indicate so.
Sample Response to `https://localhost:8443/api/v1/cluster-summary`
{"data":[{"isEmpty":false,"namespace":"default","pipelineSummary":{"active":{"Healthy":1,"Warning":0,"Critical":0},"inactive":0},"isbServiceSummary":{"active":{"Healthy":1,"Warning":0,"Critical":0},"inactive":0}},{"isEmpty":true,"namespace":"local-path-storage","pipelineSummary":{"active":{"Healthy":0,"Warning":0,"Critical":0},"inactive":0},"isbServiceSummary":{"active":{"Healthy":0,"Warning":0,"Critical":0},"inactive":0}},{"isEmpty":true,"namespace":"numaflow-system","pipelineSummary":{"active":{"Healthy":0,"Warning":0,"Critical":0},"inactive" …

chore: include empty namespaces in cluster summary

---

cmd/commands/server.go
server/apis/v1/dexauthn.go
server/apis/v1/handler.go
server/apis/v1/noauthhandler.go
server/authn/user_id_info.go
server/cmd/start.go
server/common/consts.go
server/common/cookie.go
server/routes/routes.go

- Split cookie to meet the cookie length requirement
- Remove dex-proxy-addr

fix: Split cookie to meet the cookie length requirement

---

ui/src/components/common/AccountMenu/index.test.tsx
ui/src/components/common/AccountMenu/index.tsx
ui/src/components/common/Breadcrumbs/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/Errors/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/K8sEvents/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineCreate/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/PipelineUpdate/index.test.tsx

Also commented out some failing tests

chore: added ui unit tests

---

server/apis/v1/handler.go

fix: max lag

---

ui/src/components/common/DebouncedSearchInput/index.test.tsx
ui/src/components/common/DebouncedSearchInput/index.tsx
ui/src/components/common/ErrorDisplay/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/Buffers/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.test.tsx
ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx

chore: added unit tests for components

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx

https://github.com/numaproj/numaflow/assets/4667739/792dc11a-e6ae-4293-b336-6bda96a7f636
https://github.com/numaproj/numaflow/assets/4667739/c42ea627-8f9a-4f1c-9539-3a3c3ffc5d80

fix: create isb should move to isb tab

---

ui/src/components/common/SlidingSidebar/partials/ISBUpdate/index.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/ISBServiceCard/ISBServiceCard.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

Update ISB spec fixed to have whole spec editable

fix: full isb spec in edit

---

ui/src/components/common/SlidingSidebar/partials/PipelineUpdate/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

fix: block pipeline load post update

fix: block pipeline load post update

---

ui/src/components/common/DebouncedSearchInput/index.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/ISBServiceCard/ISBServiceCard.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx

- fix pagination issue where ISB and pipeline useEffects were resetting each other's variables
- fix pipeline and ISB card styling
- fix input filtering spacing for namespace page

fix(UI): namespace pagination and style fixes

---

Makefile
config/advanced-install/numaflow-dex-server.yaml
config/advanced-install/numaflow-dex-server/kustomization.yaml
config/base/dex/numaflow-dex-server-configmap.yaml
config/base/dex/numaflow-dex-server-deployment.yaml
config/base/numaflow-server/numaflow-server-cmd-params-config.yaml
config/install.yaml
config/namespace-install.yaml

chore: expose dex installation manifests

---

ui/src/components/pages/Namespace/partials/NamespacePipelineListing/ISBServiceCard/ISBServiceCard.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx

Descending order of Logs
Removed pointer cursor in legend
Changed the ISB services title and headers

fix: rc-4 bug bash bug fixes

---

ui/src/components/pages/Cluster/partials/ClusterNamespaceListing/index.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx
ui/src/utils/fetchWrappers/pipelineFetch.ts
ui/src/utils/index.tsx

- remove unknown filter from cluster view as it is not applicable in that context

fix(SERVER): remove unknown filter

---

ui/src/components/common/SpecEditor/index.test.tsx
ui/src/components/common/StatusBar/index.test.tsx
ui/src/components/common/StatusCounts/StatusCounts.test.tsx
ui/src/components/common/StatusIndicator/StatusIndicator.test.tsx
ui/src/components/common/StatusIndicator/StatusIndicator.tsx
ui/src/components/common/SummaryPageLayout/index.test.tsx
ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Namespace/partials/NamespacePipelineListing/ISBServiceCard/ISBServiceCard.test.tsx
ui/src/components/pages/Pipeline/partials/PipelineISBStatus/index.test.tsx

Unit tests UI

---

USERS.md

Add Atlan into USERS.md

---

ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/pages/Pipeline/index.test.tsx
ui/src/components/pages/Pipeline/index.tsx

chore: unit test for pipeline component

---

README.md
docs/README.md

chore: new demo video

---

test/sdks-e2e/testdata/flatmap-stream.yaml
test/sdks-e2e/testdata/flatmap.yaml
test/sdks-e2e/testdata/simple-keyed-reduce-pipeline.yaml
test/sdks-e2e/testdata/transformer/event-time-filter-java.yaml

chore: update java e2e test images

---

pkg/reconciler/isbsvc/controller.go
pkg/reconciler/isbsvc/controller_test.go
pkg/reconciler/isbsvc/validate.go
pkg/reconciler/isbsvc/validate_test.go
server/apis/v1/handler.go
test/api-e2e/api_test.go
webhook/validator/isbsvc.go
webhook/validator/isbsvc_test.go
webhook/validator/mock_isb_client.go
webhook/validator/pipeline.go
webhook/validator/test_utils.go
webhook/validator/validator.go
webhook/validator/validator_test.go
webhook/webhook.go

1. Use IsDNS1053Label to validate the ISBSVC name.
2. Replace gin ShouldBindJson with the json decoder to decode the request body to the spec object. json decoder supports disallowing unknown fields. This catches typos such as `replica`.
3. Disallow updating ISBSVC name and namespace from UI.

fix: add more checks to isbsvc validation

---

server/apis/v1/handler.go
webhook/webhook.go

chore: treat vertex update as pipeline update

---

docs/operations/ui-access-path.md

docs: access path config

---

pkg/apis/proto/map/v1/map.proto
pkg/apis/proto/mapstream/v1/mapstream.proto
pkg/apis/proto/reduce/v1/reduce.proto
pkg/apis/proto/sideinput/v1/sideinput.proto
pkg/apis/proto/sink/v1/sink.proto
pkg/apis/proto/source/v1/source.proto
pkg/apis/proto/sourcetransform/v1/transform.proto

chore: centralize proto files for sdks

---

README.md
docs/README.md
server/common/consts.go

fix: configmap const name

---

docs/core-concepts/watermarks.md

doc: idle source

---

docs/user-guide/reference/configuration/pipeline-customization.md

docs: customize side inputs manager pods resources

---

pkg/reduce/applier/reducer.go
pkg/reduce/data_forward.go
pkg/reduce/pbq/partition/partition.go
pkg/reduce/pnf/processandforward.go
pkg/window/sorted_window_endtime.go
pkg/window/strategy/fixed/fixed.go
pkg/window/strategy/session/session.go
pkg/window/strategy/sliding/sliding.go
pkg/window/windower.go
test/reduce-e2e/reduce_test.go

Make some small updates on comments and fix some typos while I learn how reduce works.

chore: update some comments for reduce

---

pkg/sdkclient/const.go
pkg/sdkclient/mapper/client.go
pkg/sdkclient/mapstreamer/client.go
pkg/sdkclient/options.go
pkg/sdkclient/reducer/client.go
pkg/sdkclient/sdkserverinfo.go
pkg/sdkclient/sessionreducer/client.go
pkg/sdkclient/sideinput/client.go
pkg/sdkclient/sinker/client.go
pkg/sdkclient/source/client/client.go
pkg/sdkclient/sourcetransformer/client.go
pkg/sdkserverinfo/const.go
pkg/sdkserverinfo/options.go
pkg/sdkserverinfo/sdkserverinfo.go
pkg/sinks/sink.go
pkg/sources/source.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go

fix: https://github.com/numaproj/numaflow/issues/1450

chore: extract sdk server info

---

docs/user-guide/user-defined-functions/map/examples.md
docs/user-guide/user-defined-functions/reduce/examples.md

fixes #1378
Running the website locally, it seems that the issue has been fixed:

fix: bug where dashed line is treated as permalink + spelling/formatting

---

docs/user-guide/sources/kafka.md
pkg/shared/util/saramaconfig_test.go

https://github.com/numaproj/numaflow/issues/925#issuecomment-1901344016

chore: update kafka source doc

---

Makefile
pkg/shared/idlehandler/source_idlehandler_test.go
server/apis/v1/local_user_authn.go
server/authn/local_accounts.go
server/cmd/serversecretinit/start.go
test/fixtures/kafka.go
test/kafka-e2e/kafka_test.go
test/sideinputs-e2e/sideinput-e2e_sink_source_test.go

chore: enable gofmt linter

---

ui/src/components/pages/Namespace/partials/NamespaceListingWrapper/index.tsx

Issue - unknown for ISB details
Fixed -

fix: unknown for ISB details in pipeline card

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
pkg/reconciler/config.go
pkg/reconciler/config_test.go
pkg/reconciler/isbsvc/controller_test.go
pkg/reconciler/isbsvc/installer/installer_test.go
pkg/reconciler/isbsvc/installer/jetstream.go
pkg/reconciler/isbsvc/installer/jetstream_test.go
pkg/reconciler/isbsvc/installer/native_redis.go
pkg/reconciler/isbsvc/installer/native_redis_test.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/pipeline/controller_test.go
pkg/reconciler/test_utils.go
pkg/reconciler/vertex/controller.go
pkg/reconciler/vertex/controller_test.go

Fix controller config auto-reloading concurrency problem.

chore: load controller config with lock

---

pkg/reconciler/pipeline/validate.go
pkg/reconciler/pipeline/validate_test.go

chore: scale.max can not be 0

---

.github/ISSUE_TEMPLATE/bug_report.md

Adding slack link to Bug report template

chore: adding slack link to Bug report template

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
config/base/crds/full/numaflow.numaproj.io_pipelines.yaml
config/base/crds/full/numaflow.numaproj.io_vertices.yaml
config/install.yaml
config/namespace-install.yaml
docs/APIs.md
pkg/apis/numaflow/v1alpha1/openapi_generated.go
pkg/apis/numaflow/v1alpha1/tls.go

fix: incorrect json schema for tls config

---

docs/user-guide/reference/kustomize/numaflow-transformer-config.yaml

fix: https://github.com/numaproj/numaflow/issues/1530
Test `images`
pipeline.yaml
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
name: simple-pipeline
spec:
sideInputs:
- name: dummy
container:
image: numaflow-go:latest
args:
- "side-inputs-example"
trigger:
schedule: "*/15 * * * *"
vertices:
- name: in
source:
udsource:
container:
image: numaflow-go:latest
args:
- "udsource-example"
sideInputs:
- dummy
- name: forward
scale:
min: 1
sidecars:
- name: my-sidecar
image: busybox:latest
command: [ "/bin/sh", "-c", "echo \"my-sidecar is running!\" && tail -f /dev/null" ]
udf:
container:
image: numaflow-python:latest
args:
- python
- starter.py
- "forward-map"
- name: out
sink:
udsink:
container:
image: numaflow-go:latest
args:
- "sink-example"
edges:
- from: in
to: …
```

chore: update numaflow-transformer-config.yaml

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
docs/APIs.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/kafka_source.go
pkg/apis/numaflow/v1alpha1/openapi_generated.go

The right fix should be via #1568

chore: mark kafka include-headers as experimental

---

test/reduce-two-e2e/reduce_two_test.go
test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-go.yaml
test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-java.yaml

test: add simple session reduce e2e for java sdk

---

test/reduce-two-e2e/testdata/session-reduce/simple-session-sum-pipeline.yaml

Add link to sessionreducer sum example, and update tag to `stable`.

chore: add sessionreducer sum example link

---

test/e2e-api/http.go
test/fixtures/http_send.go
test/fixtures/when.go

test: remove unnecessary pod ID lookup

---

.github/workflows/changelog.yml
.github/workflows/ci.yaml
.github/workflows/gh-pages.yaml
.github/workflows/nightly-build.yml
.github/workflows/release.yml
test/sdks-e2e/sdks_test.go

ci: upgrade deprecated actions

---

pkg/daemon/server/service/pipeline_watermark_query.go
pkg/isb/stores/jetstream/reader.go
pkg/reduce/data_forward_test.go
pkg/watermark/fetch/edge_fetcher.go
pkg/watermark/fetch/edge_fetcher_set.go
pkg/watermark/fetch/edge_fetcher_set_test.go
pkg/watermark/fetch/edge_fetcher_test.go
pkg/watermark/fetch/options.go
pkg/watermark/fetch/processor_manager.go
test/e2e/functional_test.go
test/reduce-one-e2e/reduce_one_test.go

fix: watermark progression during pods creation/deletion

---

USERS.md

Adding a new user to the list.

doc: add new user to the list

---

pkg/forwarder/interfaces.go
pkg/isb/stores/jetstream/writer_test.go
pkg/isb/stores/redis/read_test.go
pkg/isb/stores/redis/write_test.go
pkg/reduce/data_forward_test.go
pkg/reduce/pbq/pbq.go
pkg/reduce/pnf/pnf.go
pkg/reduce/pnf/pnf_test.go
pkg/shared/clients/redis/redis_client_test.go
pkg/shared/util/string.go
pkg/shuffle/shuffle.go
pkg/sources/forward/data_forward.go
pkg/sources/forward/data_forward_test.go
pkg/sources/forward/shutdown_test.go
pkg/sources/generator/tickgen_test.go
pkg/sources/http/http_test.go
pkg/sources/kafka/handler_test.go
pkg/sources/nats/nats_test.go
pkg/sources/source.go
pkg/sources/udsource/grpc_udsource.go
pkg/sources/udsource/grpc_udsource_test.go
pkg/sources/udsource/metrics.go
pkg/udf/forward/forward.go
pkg/udf/forward/forward_test.go
pkg/udf/forward/shutdown_test.go
pkg/udf/map_udf.go
pkg/udf/reduce_udf.go

fix: Dedup not working for multi-partitioned edge

---

pkg/sinks/udsink/sink.go

Add headers to custom sinkRequest

fix: add headers to custom sinkrequest

---

config/advanced-install/namespaced-numaflow-server.yaml
config/advanced-install/numaflow-server.yaml
config/cluster-install/rbac/numaflow-server/numaflow-server-cluster-role.yaml
config/install.yaml
config/namespace-install.yaml
config/namespace-install/rbac/numaflow-server/numaflow-server-role.yaml

chore: remove pods/exec from UX server RBAC

---

docs/user-guide/reference/kustomize/numaflow-transformer-config.yaml

chore: kustomization cofigurations support fallback sink

---

ui/package.json
ui/src/App.tsx
ui/src/components/common/Breadcrumbs/index.tsx
ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx
ui/src/components/plugin/Breadcrumbs/Breadcrumbs.tsx
ui/src/components/plugin/NumaflowMonitorApp/App.tsx

- For namespaced scoped and package installation, updated route query with `?namespace={namespaceID}`
- Updated Breadcrumbs to be updated on state changes

fix: routing fixes

---

ui/package.json
ui/yarn.lock

- downgrading editor version in UI for compatibility

fix: version downgrade for monaco-editor 

---

docs/user-guide/sinks/fallback.md
examples/14-simple-fallback-pipeline.yaml

doc: Fallback Sink

---

docs/user-guide/user-defined-functions/reduce/windowing/fixed.md
docs/user-guide/user-defined-functions/reduce/windowing/session.md
docs/user-guide/user-defined-functions/reduce/windowing/sliding.md
pkg/udf/forward/forward_test.go

doc: reduce streaming

---

pkg/sdkclient/serverinfo/serverinfo.go

chore: skip sdk compatibility check if server info does not contain sdk version

---

docs/core-concepts/inter-step-buffer-service.md
docs/core-concepts/inter-step-buffer.md
examples/0-isbsvc-jetstream.yaml

doc: add numaflow-controller-config link

---

pkg/apis/numaflow/v1alpha1/const.go
pkg/sources/forward/data_forward.go
pkg/sources/forward/data_forward_test.go
pkg/sources/forward/options.go
pkg/sources/generator/tickgen.go
pkg/sources/generator/tickgen_test.go
pkg/sources/http/http.go
pkg/sources/http/http_test.go
pkg/sources/kafka/handler.go
pkg/sources/kafka/handler_test.go
pkg/sources/kafka/offset.go
pkg/sources/kafka/options.go
pkg/sources/kafka/reader.go
pkg/sources/kafka/reader_test.go
pkg/sources/nats/nats.go
pkg/sources/nats/nats_test.go
pkg/sources/source.go
pkg/sources/sourcer/sourcer.go
pkg/sources/udsource/user_defined_source.go

chore: Refactor Source to Avoid Implementing Forwarder Interface 

---

ui/src/App.css
ui/src/App.tsx
ui/src/components/common/SummaryPageLayout/index.tsx
ui/src/components/plugin/NumaflowMonitorApp/App.css
ui/src/components/plugin/NumaflowMonitorApp/App.tsx

Renders pipeline view which was invisible due to styling issues

fix: height fixes to render pipeline view

---

.github/workflows/changelog.yml
docs/user-guide/reference/autoscaling.md
pkg/isb/stores/jetstream/reader_test.go
pkg/isb/stores/jetstream/writer_test.go

chore: fix some doc typos and a github action upgrade

---

server/cmd/server/start.go

chore: remove tailing slash from CORS config. Closes #1735

---

pkg/sources/jetstream/jetstream.go

Forward message headers in jetstream source

---

docs/user-guide/reference/configuration/container-resources.md

docs: missing docs for container resources

---

README.md
docs/README.md

doc: update roadmap

---

examples/10-cycle-to-prev.yaml
examples/10-cycle-to-self.yaml
examples/11-join-on-reduce.yaml
examples/11-join-on-sink.yaml
examples/12-simple-session-pipeline.yaml
examples/13-streaming-reduce-pipeline.yaml
examples/14-simple-fallback-pipeline.yaml
examples/2-even-odd-pipeline.yaml
examples/6-reduce-fixed-window-with-pvc.yaml
examples/6-reduce-fixed-window.yaml
examples/7-reduce-sliding-window.yaml
examples/8-reduce-complex-pipeline.yaml

fix: update SDKs to stable image

---

.github/workflows/ci.yaml

test: enable code testing coverage

---

go.mod
go.sum
pkg/shared/util/saramaconfig_test.go

chore: update sarama to fix broker panic

---

config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/controller-manager-deployment.yaml
config/install.yaml
config/namespace-install.yaml
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/pipeline_types_test.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/apis/numaflow/v1alpha1/vertex_types_test.go

chore: expose metrics port for vertex pod and controller

---

.github/workflows/ci.yaml

Run test cases in one job to avoid `codecov` report updating twice in one commit.

test: run test cases in one job

---

pkg/reconciler/vertex/scaling/scaling.go

fix(#1832): scale down to >=min, but not 0 when there's direct back pressure

---

cmd/commands/isbsvc_create.go
cmd/commands/isbsvc_delete.go
cmd/commands/isbsvc_validate.go
examples/15-serving-source-pipeline.yaml
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/pipeline_types_test.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/apis/numaflow/v1alpha1/vertex_types_test.go
pkg/daemon/server/service/pipeline_metrics_query_test.go
pkg/isbsvc/interface.go
pkg/isbsvc/jetstream_service.go
pkg/isbsvc/redis_service.go
pkg/isbsvc/redis_service_test.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/vertex/controller.go

chore: support for multiple serving sources

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
docs/APIs.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go
pkg/apis/numaflow/v1alpha1/openapi_generated.go

fix: api docs for jetstream service

---

pkg/reconciler/isbsvc/installer/installer.go
pkg/reconciler/isbsvc/installer/jetstream.go
pkg/reconciler/isbsvc/installer/native_redis.go
pkg/reconciler/metrics.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/vertex/controller.go

Exposed following metrics:
1. `controller_isbsvc_jetstream_replicas` for JetStream ISB Services
2. `controller_isbsvc_redis_replicas` for Redis ISB Services
3. `controller_vertex_desired_replicas` for Vertices
4. `controller_vertex_current_replicas` for Vertices
examples:
```
controller_isbsvc_jetstream_replicas{isbsvc="default",ns="numaflow-system"} 3
controller_vertex_desired_replicas{ns="numaflow-system",pipeline="simple-pipeline",vertex="cat"} 1
controller_vertex_desired_replicas{ns="numaflow-system",pipeline="simple-pipeline",vertex="in"} 1
controller_vertex_desired_replicas{ns="numaflow-system",pipeline="simple-pipeline",vertex="out"} 1
controller_vertex_current_replicas{ns="numaflow-system",pipeline="simple-pipeline",vertex="cat"} 1 …
```

feat: expose replica metrics for ISB Service and Vertex

---

test/sdks-e2e/sdks_test.go
test/sdks-e2e/testdata/flatmap-batch.yaml

test: enable batchmap java e2e test

---

hack/boilerplate/boilerplate.proto.txt
pkg/apis/proto/map/v1/map.proto
pkg/apis/proto/mapstream/v1/mapstream.proto
pkg/apis/proto/reduce/v1/reduce.proto
pkg/apis/proto/sessionreduce/v1/sessionreduce.proto
pkg/apis/proto/sideinput/v1/sideinput.proto
pkg/apis/proto/sink/v1/sink.proto
pkg/apis/proto/source/v1/source.proto

copied proto files from numaflow-go

chore: update the proto files

---

USERS.md

Add Lockheed to Users.md

---

test/sdks-e2e/sdks_test.go
test/sdks-e2e/testdata/flatmap-stream.yaml

chore: add missed tests for java

---

.codecov.yml
pkg/apis/numaflow/v1alpha1/mono_vertex_types.go
rust/monovertex/src/config.rs
rust/monovertex/src/forwarder.rs
rust/monovertex/src/lib.rs
rust/monovertex/src/metrics.rs
rust/monovertex/src/sink.rs

feat: enable fallback sink for mvtx

---

test/builtin-source-e2e/testdata/http-source-with-auth.yaml
test/builtin-source-e2e/testdata/http-source.yaml
test/builtin-source-e2e/testdata/jetstream-source-pipeline.yaml
test/builtin-source-e2e/testdata/nats-source-pipeline.yaml
test/diamond-e2e/testdata/cycle-backward.yaml
test/diamond-e2e/testdata/cycle-to-self.yaml
test/diamond-e2e/testdata/join-on-map.yaml
test/diamond-e2e/testdata/join-on-reduce.yaml
test/diamond-e2e/testdata/join-on-sink.yaml
test/e2e/testdata/simple-fallback.yaml
test/e2e/testdata/udf-filtering.yaml
test/idle-source-e2e/testdata/idle-source-reduce-pipeline.yaml
test/idle-source-e2e/testdata/kafka-pipeline.yaml
test/monovertex-e2e/testdata/mono-vertex-with-transformer.yaml
test/reduce-one-e2e/testdata/complex-reduce-pipeline.yaml
test/reduce-one-e2e/testdata/complex-sliding-window-pipeline.yaml
test/reduce-one-e2e/testdata/simple-keyed-reduce-pipeline.yaml
test/reduce-one-e2e/testdata/simple-non-keyed-reduce-pipeline.yaml
test/reduce-one-e2e/testdata/simple-reduce-pipeline-wal.yaml
test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-go.yaml
test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-java.yaml
test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-go.yaml
test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-java.yaml
test/sideinputs-e2e/testdata/map-sideinput-pipeline.yaml
test/sideinputs-e2e/testdata/reduce-sideinput-pipeline.yaml
test/sideinputs-e2e/testdata/sideinput-source.yaml
test/transformer-e2e/testdata/source-filtering.yaml

chore: fix broken links

---

Makefile
docs/user-guide/reference/kustomize/numaflow-transformer-config.yaml

chore: kustomize transformation config for MonoVertex

---

rust/monovertex/src/lib.rs

fix: remove coloring in logs

---

ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/index.tsx
ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/style.css

fix: adding not available for negative processing rates

---

config/advanced-install/minimal-crds.yaml
config/base/crds/full/numaflow.numaproj.io_monovertices.yaml
config/base/crds/minimal/numaflow.numaproj.io_monovertices.yaml
config/install.yaml
config/namespace-install.yaml
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/mono_vertex_types.go

chore: enable current/desired replicas

---

pkg/reconciler/cmd/start.go

A quick fix for log format error when loading config in the controller.

fix: log format with config load error

---

pkg/reconciler/util.go

In the case of an ImagePullError we do not mark the monoVertex pod status as unhealthy 
```
{
"data": {
"resourceHealthStatus": "healthy",
"dataHealthStatus": "unknown",
"resourceHealthMessage": "mono vertex \"simple-mono-vertex\" is healthy",
"dataHealthMessage": "MonoVertex data flow is in an unknown state",
"resourceHealthCode": "M1",
"dataHealthCode": "D4"
},
"errMsg": null
} 
- containerID: docker://2b1994e75d7bc05b6f5c25d3a580c9d0f0d2e7f75c4fe33b483b5d1462262dfc
image: quay.io/numaio/numaflow-java/simple-sink:stable
imageID: docker-pullable://quay.io/numaio/numaflow-java/simple-sink@sha256:abef6a0e609266190d1077ae3b711c7fe7f4f35cb6ae6131421793c6b9efbe08
lastState:
terminated:
containerID: docker://4eb708f0610330fb3c7c64d3861c2ca6b3893975f7be58a8e708c2dbb38843e4
exitCode: 143 …
```

chore: mark imageErr as unhealthy

---

rust/monovertex/src/forwarder.rs
rust/monovertex/src/metrics.rs

chore: refactor metric variable names

---

rust/monovertex/src/forwarder.rs
rust/monovertex/src/metrics.rs

This might reduce the performance because of a lot of histograms being added, but I do not think we can avoid this metrics.

fix: add latency metrics for mvtx

---

USERS.md

Added Seekr to the USERS.md file.

chore: added Seekr to USERS.md

---

rust/monovertex/src/metrics.rs

```
numaflow@vigith$ kl simple-mono-vertex-mv-0-nviyw -c numa | grep Pending
+ kubectl logs simple-mono-vertex-mv-0-nviyw -c numa
2024-09-06T20:48:34.398233Z  INFO monovertex::metrics: Pending messages {"15m": 500, "1m": 500, "5m": 500, "default": 500}
2024-09-06T20:48:37.397674Z  INFO monovertex::metrics: Pending messages {"15m": 400, "1m": 400, "5m": 400, "default": 400}
2024-09-06T20:48:40.398373Z  INFO monovertex::metrics: Pending messages {"15m": 400, "1m": 400, "5m": 400, "default": 400}
2024-09-06T20:48:43.397461Z  INFO monovertex::metrics: Pending messages {"15m": 416, "1m": 416, "5m": 416, "default": 416}
2024-09-06T20:48:46.397987Z  INFO monovertex::metrics: Pending messages {"15m": 416, "1m": 416, "5m": 416, "default": 416}
```

chore: improve pending logs to be on single line

---

pkg/reconciler/monovertex/scaling/scaling.go
pkg/reconciler/vertex/scaling/scaling.go
pkg/reconciler/vertex/scaling/scaling_test.go

chore: use readyReplicas to calculate desired replicas

---

pkg/reconciler/pipeline/controller.go

partially fixes https://github.com/numaproj/numaflow/issues/2057

fix: skip updating phase for resource check

---

docs/user-guide/reference/configuration/volumes.md

doc: example for PVC

---

rust/Cargo.lock
rust/monovertex/Cargo.toml
rust/servesink/Cargo.toml

chore: fix numaflow-rs

---

pkg/sdkclient/const.go
pkg/sdkclient/serverinfo/serverinfo.go
pkg/sdkclient/serverinfo/serverinfo_test.go
pkg/sdkclient/serverinfo/types.go

introduces one more dimension when checking version compatibly - container type.

feat: container-type level version compatibility check

---

go.mod
pkg/sinks/sink.go

1. https://github.com/numaproj/numaflow/issues/2093
2.

chore: fix 2 issues found by code scanning

---

rust/numaflow-core/src/lib.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/source/user_defined.rs

This is a prelude before an attempt to write a generic Trait for Source. Only once we have a Trait, we can implement other sources.

chore: merge source_{reader,acker} impl into one

---

rust/Dockerfile

Is there somewhere else we have to fix too? @yhl25 @BulkBeing

chore:  rename monovertex in Dockerfile

---

rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/source.rs
rust/numaflow-core/src/source/user_defined.rs

use inner type if required to bridge read and ack if need be.

chore: separate ack

---

rust/numaflow-core/src/config.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/metrics.rs
rust/numaflow-core/src/shared/utils.rs

mono vertex spec with generator
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
name: simple-mono-vertex
spec:
source:
generator:
rpu: 50
duration: 1s
sink:
udsink:
container:
image: quay.io/numaio/numaflow-go/sink-log:stable
```
```
2024-10-09T16:40:45.253251Z  INFO numaflow_core::monovertex::forwarder: Forwarded 100 messages at time 2024-10-09 16:40:45.253247720 UTC
2024-10-09T16:40:47.249993Z  INFO numaflow_core::monovertex::forwarder: Forwarded 100 messages at time 2024-10-09 16:40:47.249991513 UTC
2024-10-09T16:40:49.248328Z  INFO numaflow_core::monovertex::forwarder: Forwarded 100 messages at time 2024-10-09 16:40:49.248326889 UTC
2024-10-09T16:40:50.255058Z  INFO numaflow_core::monovertex::forwarder: Forwarded 50 messages at time 2024-10-09 …
```

feat: integrate tickgen with monovertex

---

rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/monovertex/metrics.rs
rust/numaflow-core/src/shared/utils.rs
rust/numaflow-core/src/sink.rs
rust/numaflow-core/src/sink/user_defined.rs
rust/numaflow-core/src/source.rs
rust/numaflow-core/src/source/generator.rs
rust/numaflow-core/src/source/user_defined.rs
rust/numaflow-core/src/transformer/user_defined.rs

feat: add actor pattern for forwarder

---

rust/numaflow-core/src/message.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/monovertex/metrics.rs
rust/numaflow-core/src/shared/utils.rs
rust/numaflow-core/src/sink.rs
rust/numaflow-core/src/sink/user_defined.rs
rust/numaflow-core/src/source.rs
rust/numaflow-core/src/source/generator.rs
rust/numaflow-core/src/source/user_defined.rs
rust/numaflow-core/src/transformer/user_defined.rs

feat: actor pattern for forwarder + sink trait

---

cmd/commands/controller.go
config/advanced-install/namespaced-controller-wo-crds.yaml
config/base/controller-manager/numaflow-controller-config.yaml
config/install.yaml
config/namespace-install.yaml
docs/operations/installation.md
docs/operations/numaflow-controller-config.yaml
go.mod
go.sum
pkg/apis/numaflow/v1alpha1/const.go
pkg/reconciler/config.go
pkg/reconciler/config_test.go
pkg/reconciler/isbsvc/controller.go
pkg/reconciler/monovertex/controller.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/vertex/controller.go

feat: support multiple controller with instance config

---

pkg/apis/numaflow/v1alpha1/isbsvc_types.go
pkg/apis/numaflow/v1alpha1/isbsvc_types_test.go
pkg/webhook/validator/isbsvc.go
pkg/webhook/validator/isbsvc_test.go
pkg/webhook/validator/pipeline.go
pkg/webhook/validator/pipeline_test.go
pkg/webhook/validator/test_utils.go

Webhook will block following operations:
1. Creating a Pipeline which references an ISBSvc having different instance annotation
2. Updating instance annotation of a Pipeline
3. Updating instance annotation of an ISBSvc

chore: multi controller awareness on validating webhook

---

rust/numaflow-core/src/error.rs
rust/numaflow-core/src/source.rs

chore: do not unwrap

---

rust/backoff/src/retry.rs
rust/numaflow-core/src/config.rs
rust/numaflow-core/src/message.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/monovertex/metrics.rs
rust/numaflow-core/src/pipeline/isb/jetstream.rs
rust/numaflow-core/src/pipeline/isb/jetstream/writer.rs
rust/numaflow-core/src/shared/server_info.rs
rust/numaflow-core/src/shared/utils.rs
rust/numaflow-core/src/sink.rs
rust/numaflow-core/src/sink/user_defined.rs
rust/numaflow-core/src/source/generator.rs
rust/numaflow-core/src/source/user_defined.rs
rust/numaflow-core/src/transformer/user_defined.rs
rust/servesink/src/lib.rs
rust/serving/src/app.rs
rust/serving/src/app/callback.rs
rust/serving/src/app/callback/state.rs
rust/serving/src/app/callback/store/memstore.rs
rust/serving/src/app/callback/store/redisstore.rs
rust/serving/src/app/jetstream_proxy.rs
rust/serving/src/app/message_path.rs
rust/serving/src/app/tracker.rs
rust/serving/src/config.rs
rust/serving/src/lib.rs
rust/serving/src/metrics.rs
rust/serving/src/pipeline.rs
rust/src/bin/main.rs

chore: organize rust imports

---

rust/numaflow-core/src/config.rs
rust/numaflow-core/src/message.rs
rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/pipeline/isb/jetstream.rs
rust/numaflow-core/src/pipeline/isb/jetstream/writer.rs
rust/numaflow-core/src/sink/user_defined.rs
rust/numaflow-core/src/source/generator.rs
rust/numaflow-core/src/source/user_defined.rs
rust/numaflow-core/src/transformer/user_defined.rs

* Made offset optional in the message.
* Introduced integer and string offset types in enums.
* Used appropriate partition idx and IDs when creating the message.

chore: use enums for offset

---

rust/numaflow-core/src/config.rs
rust/numaflow-core/src/message.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/sink.rs
rust/numaflow-core/src/sink/blackhole.rs

feat: blackhole sink for Monovertex

---

rust/numaflow-core/src/sink/blackhole.rs
rust/numaflow-core/src/sink/log.rs

fix: main branch, offset type got updated

---

pkg/reconciler/cmd/start.go
pkg/shared/util/string.go
pkg/shared/util/string_test.go

When using multiple controllers with leader election is enabled, they should have different lock name.

fix(controller): incorporate instance into lease lock name

---

docs/specifications/side-inputs.md
pkg/reconciler/cmd/start.go
pkg/reconciler/isbsvc/controller.go
pkg/reconciler/isbsvc/controller_test.go
pkg/reconciler/monovertex/controller.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/pipeline/controller_test.go
pkg/reconciler/validator/isbsvc_validate.go
pkg/reconciler/validator/isbsvc_validate_test.go
pkg/reconciler/validator/mvtx_validate.go
pkg/reconciler/validator/mvtx_validate_test.go
pkg/reconciler/validator/pipeline_validate.go
pkg/reconciler/validator/pipeline_validate_test.go
pkg/webhook/validator/isbsvc.go
pkg/webhook/validator/pipeline.go

chore: mono vertex validation

---

test/map-e2e/map_test.go
test/map-e2e/testdata/flatmap-batch.yaml
test/map-e2e/testdata/flatmap-stream.yaml
test/map-e2e/testdata/flatmap.yaml
test/transformer-e2e/transformer_test.go
test/udsource-e2e/testdata/simple-source-python.yaml
test/udsource-e2e/udsource_test.go

chore: re-enable e2e tests

---

README.md
docs/README.md

doc: roadmap update

---

ui/src/utils/fetcherHooks/podsViewFetch.ts

fix: init container logs

---

rust/backoff/src/retry.rs
rust/numaflow-core/src/metrics.rs
rust/numaflow-core/src/monovertex.rs
rust/numaflow-core/src/pipeline/isb/jetstream/writer.rs
rust/numaflow-core/src/transformer.rs
rust/serving/src/app.rs
rust/serving/src/app/callback/store/memstore.rs
rust/serving/src/config.rs
rust/serving/src/lib.rs
rust/serving/src/metrics.rs

- Remove static config for TLS certs in `serving`
- Fixes clippy errors

chore: clippy error fixes

---

rust/numaflow-core/src/message.rs
rust/numaflow-core/src/pipeline.rs
rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs
rust/numaflow-core/src/pipeline/isb/jetstream/writer.rs
rust/numaflow-core/src/shared/forward.rs
rust/numaflow-core/src/sink.rs
rust/numaflow-core/src/sink/blackhole.rs
rust/numaflow-core/src/sink/log.rs
rust/numaflow-core/src/sink/user_defined.rs
rust/numaflow-core/src/source.rs
rust/numaflow-core/src/source/generator.rs
rust/numaflow-core/src/source/pulsar.rs
rust/numaflow-core/src/tracker.rs
rust/numaflow-core/src/transformer.rs
rust/numaflow-core/src/transformer/user_defined.rs

#2267
tps increase for mvtx with source and sink - 262k to 270k
tps increase for mvtx with transformer - 138k to 141k

chore: make Message cheap to clone

---

pkg/sinks/forward/forward.go

chore: always publish watermark to sink OT

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
docs/APIs.md
docs/user-guide/sinks/fallback.md
docs/user-guide/sinks/retry-strategy.md
pkg/apis/numaflow/v1alpha1/generated.proto
pkg/apis/numaflow/v1alpha1/retry_strategy.go
pkg/apis/numaflow/v1alpha1/zz_generated.openapi.go
rust/numaflow-models/src/models/retry_strategy.rs

docs: update fallback sink docs

---

pkg/reconciler/metrics.go
pkg/reconciler/monovertex/controller.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/vertex/controller.go

Expose these metrics per Intuit ask.

chore: expose metrics for min and max replicas

---

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx

- updated the chart labels with AM/PM
- updated tooltip for chart values with complete date (including timezone info)

feat: updating chart lables and tooltip

---

rust/numaflow-core/src/monovertex/forwarder.rs
rust/numaflow-core/src/shared/utils.rs

chore: infinite retry for connecting to UDF server, avoid publishing metrics when there is no data

---

rust/numaflow-core/src/metrics.rs
rust/numaflow-core/src/pipeline.rs
rust/serving/src/app/jetstream_proxy.rs
rust/serving/src/app/message_path.rs

Minor changes I noticed while reading the changes in #2422

chore: Serving source - minor refactoring

---

USERS.md

I added NTT in USERS.md.
This PR is created upon @whynowy request
Since this is a minor change, I didn't create an issue. However, is it necessary?

docs: update USERS.md

---

docs/core-concepts/monovertex.md

doc(typo): explicit callout for map

---

docs/operations/metrics/metrics.md

fix(docs): PodMonitor manifest in metrics

---

pkg/daemon/server/service/rater/pod_tracker.go
pkg/mvtxdaemon/server/service/rater/pod_tracker.go

We are sequentially invoking  HEAD request to a pod/replica and waiting for its timeout(1 sec) to check if a pod is active or not.
```
{"level":"info","ts":"2025-03-19T03:43:20.346524723Z","logger":"numaflow.daemon-server.PodTracker","caller":"rater/pod_tracker.go:173","msg":"Sending HEAD request to pod simple-pipeline-in-0 is successful, treating the pod as active and time: 3.483791ms","pipeline":"simple-pipeline"}
{"level":"info","ts":"2025-03-19T03:43:21.347417474Z","logger":"numaflow.daemon-server.PodTracker","caller":"rater/pod_tracker.go:170","msg":"Sending HEAD request to pod simple-pipeline-in-1 is unsuccessful: Head \"https://simple-pipeline-in-1.simple-pipeline-in-headless.default.svc:2469/metrics\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), …
```

fix: concurrent invocations to update active pods list in rater

---

docs/operations/metrics/metrics.md
pkg/daemon/server/service/rater/pod_tracker_test.go
pkg/mvtxdaemon/server/service/rater/pod_tracker_test.go
pkg/window/strategy/accumulate/accumulate.go

fix: main is broken

---

api/json-schema/schema.json
api/openapi-spec/swagger.json
config/base/crds/full/numaflow.numaproj.io_pipelines.yaml
config/base/crds/full/numaflow.numaproj.io_vertices.yaml
config/install.yaml
config/namespace-install.yaml
docs/APIs.md
examples/13-accumulator-window.yaml
pkg/apis/numaflow/v1alpha1/udf.go
pkg/apis/numaflow/v1alpha1/zz_generated.openapi.go
rust/numaflow-models/src/models/accumulator_window.rs

fix: typo, use timeout instead of ttl

---

docs/user-guide/reference/mvtx-operations.md
mkdocs.yml

docs: pause/resume a mvtx

---

pkg/sinks/sink.go
test/e2e/testdata/simple-pipeline.yaml

completes partially for 1.4 #2516

fix: create a new bidi stream for every partition to avoid race condition in sink

---

.github/workflows/ci.yaml
rust/Cargo.lock
rust/Cargo.toml
rust/extns/numaflow-jetstream/Cargo.toml
rust/extns/numaflow-jetstream/src/lib.rs
rust/extns/numaflow-pulsar/Cargo.toml
rust/extns/numaflow-sqs/Cargo.toml
rust/numaflow-core/Cargo.toml
rust/numaflow-core/src/source/jetstream.rs
rust/numaflow-core/src/tracker.rs
rust/numaflow-core/src/watermark/idle/isb.rs
rust/numaflow-monitor/Cargo.toml
rust/numaflow-pb/Cargo.toml
rust/numaflow-pb/src/clients/map.v1.rs
rust/numaflow-pb/src/clients/mapstream.v1.rs
rust/numaflow-pb/src/clients/reduce.v1.rs
rust/numaflow-pb/src/clients/serving.v1.rs
rust/numaflow-pb/src/clients/sessionreduce.v1.rs
rust/numaflow-pb/src/clients/sideinput.v1.rs
rust/numaflow-pb/src/clients/sink.v1.rs
rust/numaflow-pb/src/clients/source.v1.rs
rust/numaflow-pb/src/clients/sourcetransformer.v1.rs
rust/serving/Cargo.toml
rust/serving/src/app/jetstream_proxy.rs

merge only after https://github.com/numaproj/numaflow-rs/pull/117

chore: upgrade crates

---

pkg/apis/numaflow/v1alpha1/container_builder.go
pkg/apis/numaflow/v1alpha1/monitor_container.go
pkg/apis/numaflow/v1alpha1/mono_vertex_types.go
pkg/apis/numaflow/v1alpha1/mono_vertex_types_test.go
pkg/apis/numaflow/v1alpha1/serving_store.go
pkg/apis/numaflow/v1alpha1/sink.go
pkg/apis/numaflow/v1alpha1/source.go
pkg/apis/numaflow/v1alpha1/udf.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/apis/numaflow/v1alpha1/vertex_types_test.go

chore: mount runtime path to ud containers

---

USERS.md

Adding QualiBooth use case to the user list.

chore: add QualiBooth to USERS.md

---

docs/development/releasing.md

docs: revise release process to include helm chart update

---

pkg/apis/numaflow/v1alpha1/monitor_container.go
pkg/apis/numaflow/v1alpha1/monitor_container_test.go

chore: update resources for monitor container

---

docs/core-concepts/serving.md
mkdocs.yml

doc: User docs for ServingPipeline

---

docs/specifications/autoscaling.md
docs/user-guide/reference/autoscaling.md

chore: aggressive autoscaling

---

docs/development/development.md
pkg/mvtxdaemon/server/service/rater/rater.go

chore: fix lint error

---

pkg/isb/stores/redis/metrics.go

fix: isb_redis_read_error_total's help message

---

Makefile
hack/generate-proto.sh

fix: have `make pre-push -B` pass

---

rust/numaflow-core/src/reduce/wal/segment/compactor.rs

chore: ShouldRetain should be a trait to enforce better type checking

---

config/advanced-install/minimal-crds.yaml
config/base/crds/minimal/kustomization.yaml
config/extensions/webhook/numaflow-webhook-deployment.yaml
config/extensions/webhook/rbac/numaflow-webhook-cluster-role.yaml
config/validating-webhook-install.yaml

fix(manifests): some manifests related to servingpipeline missing

---

docs/user-guide/user-defined-functions/reduce/windowing/accumulator.md

doc: minor typo in accum doc

---

pkg/watermark/timeline/offset_timeline.go

fix: idle watermark severity

---

rust/numaflow/src/main.rs

Searched for all `sleep` calls in Rust code, all other usage seems valid ones.

chore: Remove code added for debugging purposes

---

rust/numaflow-core/src/monovertex.rs

chore: calculate pending on replica 0 only

---

pkg/reconciler/cmd/start.go

Some k8s distro has incorrect minor version like below.
```json
{
"major": "1",
"minor": "30+",
"gitVersion": "v1.30.11-eks-bcf3d70",
"gitCommit": "2fa190a24584e3b061e4c94d3b4d1608e34e5e3b",
"gitTreeState": "clean",
"buildDate": "2025-03-24T21:51:28Z",
"goVersion": "go1.23.6",
"compiler": "gc",
"platform": "linux/amd64"
}
```

fix: potential incorrect k8s minor version

---

pkg/apis/numaflow/v1alpha1/deprecated.go

chore: temporarily hold the sidecar support

---

.github/workflows/release.yml

Follow up from https://github.com/numaproj/numaflow/pull/2657
Fixes: https://github.com/numaproj/numaflow/actions/runs/15133680098/job/42540396995
Tested: https://github.com/numaproj/numaflow/actions/runs/15140426288/job/42562737720

chore: Fix release pipeline

---

rust/numaflow-core/src/config/pipeline.rs

Which contains isbsvc passwords.

chore: do not print env vars

---

rust/numaflow-core/src/shared/create_components.rs
rust/serving/src/app.rs

fix: return 400 if serving ID header contains '.'

---

rust/numaflow-core/src/metrics.rs

chore: reduce pending info logging

---

docs/user-guide/reference/kustomize/numaflow-transformer-config.yaml

fix: typo in transformer config

---

rust/Cargo.lock
rust/extns/numaflow-kafka/Cargo.toml
rust/extns/numaflow-kafka/src/lib.rs

Closes #2642 
Tested with Kafka 4.0 setup with oauth following the guide https://medium.com/art-of-data-engineering/kafka-oauth-bearer-setup-with-openid-connect-oidc-and-keycloak-364e79d76679

feat: Kafka Rust implementation - Oauth authentication

---

rust/extns/numaflow-http/src/lib.rs
rust/numaflow-core/src/source/http.rs

feat: http source should honor response status codes sent to clients

---

docs/user-guide/sinks/user-defined-sinks.md

Fixes #2673
This PR significantly enhances the user-defined sinks documentation with comprehensive details about the message-response contract and implementation patterns.
- **Complete explanation** of all 4 response types (OK, FAILURE, FALLBACK, SERVE)
- **Detailed rules** for response count, matching, and status requirements
- **Practical JSON examples** showing proper input/output formatting
- **Important assumptions** and constraints from the codebase
- **SDK method examples** for Golang, Java, and Python
- **Cross-references** to related documentation (fallback, retry strategy)
- **Idempotency requirements** for retry scenarios
- **Batch processing** guidelines and error handling
- **Related topics section** with links to overview, fallback, and retry strategy
- **SDK example links** …

docs: enhance user-defined sinks docs with message-response contract

---

rust/numaflow-core/src/config/pipeline.rs

fix: vertex type to avoid panics in watermark manager

---

rust/extns/numaflow-jetstream/src/lib.rs

Fixes https://github.com/numaproj/numaflow/issues/2770
I could not recreate the issue. When I stop the Jetstream server, it results in Numaflow source container restart
```log
2025-07-04T04:21:46.767529Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:46.809576Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:46.884907Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:47.025369Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:47.290078Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:47.808787Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:48.841194Z  INFO async_nats: event: client error: nats: IO error
2025-07-04T04:21:50.896736Z  INFO async_nats: …
```

Fix: Jetstream source - Unlimited reconnects

---

rust/numaflow-core/src/pipeline/isb/jetstream/writer.rs
rust/numaflow-sideinput/Cargo.toml
rust/numaflow-sideinput/src/config.rs
rust/numaflow-sideinput/src/lib.rs
rust/numaflow/src/cmdline/sideinput.rs

fixes #2800 
refactor such that envs can be pushed from top

chore(test): Improve testing for side-input

---

rust/numaflow-core/src/watermark/isb.rs

Fetch watermark was failing because the published wmbs were not getting added to the OT because the processor was not found(we were not publishing the heartbeats regularly).
Updated the test to keep publishing the heartbeats and watermarks so that the processor gets added and wmbs will be added in the offset timeline.

fix: flaky fetch head watermark unit test

---

docs/APIs.md
docs/user-guide/reference/pipeline-operations.md
pkg/apis/numaflow/v1alpha1/const.go
pkg/apis/numaflow/v1alpha1/pipeline_types.go
pkg/apis/numaflow/v1alpha1/vertex_types.go
pkg/reconciler/monovertex/controller.go
pkg/reconciler/monovertex/controller_test.go
pkg/reconciler/pipeline/controller.go
pkg/reconciler/pipeline/controller_test.go

feat: unpause pipelines vertices and mvtx from min replicas

---

rust/numaflow-monitor/src/runtime.rs

Enhances gRPC error logging in the numa container during UDF failures to incl. comprehensive info from gRPC Status, including metadata that was prev. missing.
**Before**: Only logged basic gRPC error information
```json
{
"code": "Internal error", 
"message": "UDF_EXECUTION_ERROR(container): Test error",
"details": "raw details"
}
```
**After**: Now includes structured metadata for comprehensive debugging
```json
{
"code": "Internal error",
"message": "UDF_EXECUTION_ERROR(container): Test error", 
"details": "raw details | metadata: error-type=udf-execution, retry-count=3"
}
```
Fixes #2380

Enhance gRPC error logging to include metadata and details

---

README.md
docs/README.md

chore: update roadmap

---

docs/user-guide/reference/configuration/max-message-size.md

Enable compression if users have to increase max-message size.
Document for https://github.com/numaproj/numaflow/pull/2709

doc: document compression

---

.github/workflows/ci.yaml
redis-deployment.yaml
rust/Cargo.lock
rust/Cargo.toml
rust/numaflow-throttling/Cargo.toml
rust/numaflow-throttling/DESIGN.md
rust/numaflow-throttling/src/error.rs
rust/numaflow-throttling/src/lib.rs
rust/numaflow-throttling/src/main.rs
rust/numaflow-throttling/src/state.rs
rust/numaflow-throttling/src/state/store.rs
rust/numaflow-throttling/src/state/store/in_memory_store.rs
rust/numaflow-throttling/src/state/store/lua/deregister.lua
rust/numaflow-throttling/src/state/store/lua/register.lua
rust/numaflow-throttling/src/state/store/lua/sync_pool_size.lua
rust/numaflow-throttling/src/state/store/redis_store.rs

Closes #2887 
Closes #2888
[Design](https://github.com/numaproj/numaflow/blob/759d152f1e1ed703646093aa3bb6c504ac55f7ee/rust/numaflow-throttling/DESIGN.md)

feat: framework for distributed throttling

---

docs/specifications/autoscaling.md
docs/user-guide/reference/mvtx-operations.md

Briefly describe the problem and the solution.
Fixes #
How was this tested (unit/integration/manual)? Include commands, links, or screenshots if applicable.
Anything notable for review (risk, rollout, follow-ups).

docs: refine the formula for autoscaling

---

rust/numaflow-throttling/src/lib.rs

Previously added tests checked for the ability to pull for tokens at each subsequent epoch. 
This PR aims to add the ability to specify, in each test case, the number of epochs after which next set of tokens need to be pulled.
Added test scenarios include:
* Trying to acquire all tokens in the same epoch after all tokens have been fetched already.
* Trying to acquire all pending tokens in the same epoch after some tokens have been fetch already.
* Trying to acquire some tokens in the same epoch after some tokens have been fetch already. 
Verified that the newly added unit tests are passing for both redis and in memory store.

test: Tests for verifying token refill computation

---

pkg/apis/numaflow/v1alpha1/sink.go

SQS was missing in fallback sink validation

fix: fallback sink validation

---

docs/specifications/autoscaling.md

Briefly describe the problem and the solution.
Fixes #
How was this tested (unit/integration/manual)? Include commands, links, or screenshots if applicable.
Anything notable for review (risk, rollout, follow-ups).

chore: fix autoscaling docs
