pkg/isb/jetstream/writer_test.go, pkg/sources/generator/tickgen.go, pkg/sources/http/http.go
`Time.After()` is changed to count from every time it gets called.
=> fix: different behavior for time.After in go 1.18

pkg/apis/numaflow/v1alpha1/const.go, pkg/apis/numaflow/v1alpha1/vertex_type_test.go, pkg/apis/numaflow/v1alpha1/vertex_types.go
I was working on a document for metrics and there was an ask to figure out how to scrape the metrics using the prometheus operator. As part of the exercise I had created some k8s serviceMonitors to monitor services(based on labels) and scrape the corresponding metric. While doing so I figured that the serviceMonitor expected a `name` field on the service spec Port object. Added the same.
This has been tested by running a sample pipeline in my local k3d cluster
=> Added name to service spec

pkg/udf/udf.go, pkg/watermark/generic/generic.go, pkg/watermark/generic/noop.go
Added no-op watermark, we cannot remove the `nil` check yet because in test functions we use it. Going forward we can use this no-op progressor for new additions. Will fix tests to use no-op in subsequent PRs.
Relates to #88
=> feat: no operation watermark progressor

pkg/udf/udf.go
fix: update udf fetchWatermark and publishWatermark initial values
tested using redis isbsvc and simple pipeline with
```yaml
watermark:
disabled: true
```
=> fix: update udf fetchWatermark and publishWatermark initial values

pkg/reconciler/vertex/scaling/scaling.go
If a vertex is in `failed` phase (for example, caused by creating pods failure), autoscaling should skip it.
=> fix(autoscaling): Skip autoscaling if vertex is not in running phase

pkg/isb/stores/redis/read.go, pkg/isb/stores/redis/read_test.go, pkg/isb/stores/redis/write.go, pkg/isb/stores/redis/write_test.go
Closes: #204 
This PR reference the `Payload` directly in `isb.message.body` to avoid extra marshaling in Redis ISB implementation. Note that we need to revisit it when `Body` structure changes for [this](https://github.com/numaproj/numaflow/pull/213#issuecomment-1278016520) reason. 
`Testing`: Unit tests.
Signed-off-by: Hao (xdevxhao@gmail.com)
=> chore: reference the Payload directly when writing to Redis ISB to avoid extra marshaling

mkdocs.yml, pkg/sources/generator/tickgen.go, pkg/watermark/generic/jetstream/generic.go
Fixes 2 issues:
1. Tickgen should not publish watermarks for every message;
2. Sources should not publish wartermarks when it's disabled.
=> fix(watermark): generator should not publish wm for every message

cmd/commands/server.go, server/cmd/start.go
Closes #227
* Adds support for disabling TLS with `--insecure` (server will listen by default at 8080)
* Adds support for overriding the default port with `--port=8081` or `-p 8081`.
=> feat: support disabling TLS and changing port for UX server

cmd/commands/server.go, config/namespace-install.yaml, config/namespace-install/kustomization.yaml, server/apis/v1/handler.go, server/cmd/start.go
Add support for running UX server restricted to a namespace.
=> feat: Support running UX server with namespace scope. Fixes #248

pkg/watermark/fetch/edge_fetcher.go, pkg/watermark/fetch/processor_manager.go, pkg/watermark/fetch/processor_manager_inmem_test.go, pkg/watermark/fetch/processor_manager_test.go, pkg/watermark/fetch/processor_to_fetch.go, pkg/watermark/publish/publisher.go, pkg/watermark/store/inmem/kv_watch.go, pkg/watermark/store/interface.go, pkg/watermark/store/jetstream/kv_watch.go, pkg/watermark/store/noop/kv_watch.go, pkg/window/keyed/keyed_test.go
- fix: https://github.com/numaproj/numaflow/issues/220
- also previous fix for the issue https://github.com/numaproj/numaflow/issues/224 has a bug. fixed again in this PR.
- add a stopped channel for the watermark watcher to guarantee the watcher stops before connection closes.
- update keyed_test.go
When a pod in Vn-1 terminates, the pod is deleted from the Vn-1_Vn heartbeat store.
https://github.com/numaproj/numaflow/blob/3ec5785e0db1bac5be2f7243eb5b45bcf10279b5/pkg/watermark/publish/publisher.go#L178
The Vn pod heartbeat watcher receives the delete op, sets the pod status to _delete, stops the pod offsetTimeline watcher, and removes the pod from heartbeat map (so refreshing heartbeat go routine no longer updates on this deleted pod). …
=> fix: watermark watcher leak

pkg/isb/interfaces.go, pkg/isb/stores/redis/read.go, pkg/isb/stores/simplebuffer/buffer.go, pkg/isb/stores/simplebuffer/buffer_test.go, pkg/isb/testutils/rw.go, pkg/sources/generator/tickgen.go, pkg/sources/http/http.go, pkg/sources/kafka/reader.go, pkg/udf/function/uds_grpc_test.go, pkg/watermark/fetch/edge_fetcher_test.go, pkg/watermark/fetch/offset_timeline_test.go, pkg/watermark/fetch/processor_manager_inmem_test.go, pkg/watermark/fetch/processor_manager_test.go, pkg/watermark/publish/publisher_inmem_test.go, pkg/watermark/publish/publisher_test.go
Offset is a monotonically increasing integer. For most of the internal representations, int64 makes more sense rather than the string representation. We can avoid an unwanted conversion if we have the support of int64. 
This will help when saving the message in WAL (a hot code path) where we can encode/decode the offset as int64.
=> chore: introduce simple int offset

pkg/reduce/pnf/processandforward.go, pkg/reduce/readloop/ordered_test.go, pkg/reduce/reduce_test.go, pkg/udf/function/uds_grpc.go, pkg/udf/function/uds_grpc_test.go, pkg/udf/reducer/reducer.go
Fixes #233 
We need to pass the partition information to the reducer so the return message will have the right `PaneInfo`
=> chore: refactor to include partition.ID for reducer

pkg/watermark/fetch/processor_manager_test.go
Fixes #256 
Adds back build constraint to processor manager test to not require jetstream for basic `make test`
=> fix: re-enable build constraint on processor manager test. Fixes #256

pkg/isb/forward/forward.go, pkg/reduce/pnf/processandforward.go
retry only the failed offsets and use exponential backoff for Ack
=> fix: retry only the failed offsets

.github/workflows/ci.yaml, pkg/isb/forward/forward.go, pkg/pbq/pbqmanager.go, pkg/pbq/pbqmanager_test.go, pkg/reduce/pnf/processandforward.go, pkg/reduce/readloop/readloop.go
- A separate PR to fix main branch make build failure: math.MaxInt64 for int type https://github.com/numaproj/numaflow/actions/runs/3316672732/jobs/5478733505#step:4:2410
ref: https://github.com/numaproj/numaflow/blob/47229e28fe8f13f977f8e5dafcf16c504295a223/pkg/isb/forward/forward.go#L296
- ~~Add make build in the ci~~ remove the build step for now
=> fix: main branch make build failure: math.MaxInt64 for int type

pkg/reconciler/isbsvc/validate.go, pkg/reconciler/isbsvc/validate_test.go
Fixes #269
Validates only one isbsvc implementation type is defined
=> fix: validate only one isbsvc implementation type is defined. Fixes #269

pkg/daemon/server/daemon_server.go, pkg/watermark/fetch/edge_fetcher.go, pkg/watermark/fetch/processor_manager.go, pkg/watermark/publish/publisher.go, pkg/watermark/store/jetstream/kv_watch.go
fix: #251 
All cases use simple pipeline and JetStream isbsvc
initial state: in(1) cat(1) out(1)
scale down: in(0) cat(0) out(0)
scale up: in(1) cat(1) out(1)
scale up: in(2) cat(2) out(2)
Based on above observation, I assume the regular pods in the vertex are working as expected.
Explanation: When a processor exits, we keep the offsetTimeline until all the offset in the offsetTimeline are outdated, and then delete the processor from the processor manager. This operation is executed in the "GetWatermark" function. However, in the UX, we only use GetHeadWatermark function, so the exited processor never gets deleted in the processor manager of the daemon service. When we scale up again and add back the processor, because we only check on `processor is nil`, the new coming back processor is …
=> fix: watermark consumer fix

docs/development.md
Closes #276.
Adds `pandoc` requirement to the development markdown.  Also references CI versions of pandoc and protoc, to help developers ensure CI code gen will match code gen on their local environment.
=> feat: add pandoc to required tools development doc. Closes #276

docs/sources/http.md, pkg/sources/http/http.go
Now that we support millisecond watermark progression, the HTTP event-time header can also be more granular
=> chore: use milliseconds in HTTP event-time header

test/sdks-e2e/sdks_test.go
This change attempts to fix E2E test failure scenario 3 in https://github.com/numaproj/numaflow/issues/210#issuecomment-1293627883
Every once in a while(about one occurrence every ~10 executions) our sdks-e2e tests fail with log validation error. The error is always thrown by VertexPodLogContains check and it's always thrown by the python-udsink, never go-udsink.
Looking at the log, I can see the failure was caused by context being closed before our default timeout. I suspect the reason why it's always python-udsink, could be because python-udsink is the very last check of the E2E test and the github E2E test infrastruct could terminate the test early before tests are done.
To verify my hypothesis, I made this code change to see if I can get a failure from go-udsink. Magically after this …
=> Chore: run in sdks-e2e tests, python-udsink log check before go-udsink

pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go, pkg/apis/numaflow/v1alpha1/jetstream_buffer_service_test.go
Sets `GOMEMLIMIT` environment variable which makes the Go GC be aware of memory limits (go 1.19).
=> chore: set GOMEMLIMIT and increase graceshutdownperiod

pkg/reconciler/cmd/start.go
Vertex controller watches all the managed pod related events including create/delete, etc. When a vertex pod is deleted, the controller sees the event, and then creates a new pod. However, the new pod creating also generates an event, and the controller starts a new reconciliation loop, in this case, you sometimes see the race conditions, that multiple pods are created in a short period of time after a pod termination, then it is eventually stabilized to be running only 1 pod. Even though it's just a short period of time, the multiple new created pods might still have started processing data, and might that cause unexpected behavior especially for a reduce vertex.
This PR makes the controller stop watching pod creating event, which will avoid …
=> chore: vertex controller stop watching pod create events

pkg/pbq/store/wal/metrics.go, pkg/pbq/store/wal/segment.go
We were missing `E` from RED family of metrics.
=> chore: add error metrics for WAL

pkg/isb/stores/jetstream/writer.go, pkg/shared/clients/jetstream/jetstream_context.go
Seeing issue with async publish with errors like below, switching to sync publish by default, and keep the async mode achievable by adding an env variable.
```
"vertex":"xxxxxx","errors":{"nats: stalled with too many outstanding async published messages":500
```
=> chore: switch to sync publish mode for jetstream isb

config/advanced-install/namespaced-controller-wo-crds.yaml, config/base/controller-manager/numaflow-controller-config.yaml, config/base/crds/full/numaflow.numaproj.io_pipelines.yaml, config/install.yaml, config/namespace-install.yaml, docs/user-guide/inter-step-buffer-service.md, docs/user-guide/pipeline-tuning.md, pkg/apis/numaflow/v1alpha1/const.go, pkg/apis/numaflow/v1alpha1/generated.proto, pkg/apis/numaflow/v1alpha1/pipeline_types.go, pkg/daemon/server/service/pipeline_metrics_query_test.go
1. Default max buffer length was not consistent in variable places, defaults it to 30000.
2. Update max ack pending to 25000 - considering default max scaling replicas is 50, and default batch size is 500.
3. Max msgs retention configuration for each stream was 2,000,000, which ended up with around a 5GB file (with around 2KB/msg) that needs to sync up when a jetstream node (pod) recreates, and when there are many streams with this large size files, it might cause issues like OOM, or taking too long to do so. Reducing the the number to 100000 is good enough considering the default max buffer length is 30000.
=> chore: reduce max msgs for jetstream config

pkg/reduce/reduce_test.go, pkg/watermark/fetch/edge_fetcher.go
while fetching watermark return `-1`, if the offset timeline store returns `-1` for any processor.
=> fix: getWatermark to  return-1 if any processor returns -1 

pkg/pbq/store/memory/stores.go, pkg/reduce/reduce_test.go
=> fix: adding lock while discovering partitions, Closes #412

pkg/reduce/pbq/store/wal/stores.go, pkg/reduce/readloop/readloop.go
- We see -ve active WAL count in the metrics dashboard, this is because we do not track reopened files after the restart.
- return early if isLate
=> fix: -ve metrics and return early if isLate

Makefile
`docker buildx build` started to generating [attestation manifests](https://docs.docker.com/build/attestations/attestation-storage/#attestation-manifest-descriptor) by default, which generates extra `unknown/unknown` manifests in the image artifactory. This makes `bom generate -i quay.io/numaproj/numaflow:xxxx` fail because `bom` does not recognize those manifests.
This PR disable the `docker buildx build` generating attestation manifests to workaround the issue.
=> ci: disable docker build attestations

pkg/reduce/pbq/store/wal/bootstrap.go, pkg/reduce/pbq/store/wal/segment.go, pkg/reduce/pbq/store/wal/segment_test.go, pkg/reduce/pbq/store/wal/stores.go
We were abusing the word `entry`. We need to differentiate between WAL header v/s ReadMessage header and its body.
=> chore: rename WAL function names

cmd/commands/isbsvc_buffer_validate.go
Log statement for buffer validation previously was misleading. This validation occurs in the vertex pod's init container. When the vertex pod is being created, this validation happens while the buffers are still being created thus making this log inaccurate. 
New log statement shows that the buffers likely aren't created yet instead of an error.
=> fix: refine log for buffer validation. Fixes #185

pkg/forward/forward.go, pkg/reduce/data_forward_test.go, pkg/reduce/pnf/processandforward.go, pkg/reduce/pnf/processandforward_test.go, pkg/watermark/fetch/offset_timeline.go, pkg/watermark/fetch/offset_timeline_test.go, pkg/watermark/fetch/processor_manager.go, pkg/watermark/fetch/processor_manager_test.go, pkg/watermark/generic/noop.go, pkg/watermark/publish/publisher.go, pkg/watermark/publish/publisher_test.go
In the case when a pod doesn't publish to all the out edges, we send an idle watermark whose watermark is assigned as the read batch's watermark.
Note that this solution is when the read in batch size is > 0. Meaning the reduce vertex is receiving incoming messages.
=> fix: Idle watermark fix for read batch size > 0 and partial idle outgoing edges

pkg/daemon/server/service/pipeline_metrics_query.go, ui/src/components/pipeline/Pipeline.tsx, ui/src/components/pipeline/edgeinfo/EdgeInfo.tsx, ui/src/components/pipeline/graph/Graph.tsx, ui/src/components/pipeline/graph/SinkNode.tsx, ui/src/components/pipeline/graph/SourceNode.tsx, ui/src/components/pipeline/graph/UDFNode.tsx, ui/src/components/pipeline/nodeinfo/NodeInfo.tsx, ui/src/components/pods/Pods.tsx, ui/src/utils/models/pipeline.ts
Fixes metrics api to prevent daemon pod crashes
Fixes UI to render for partial data.
Vertex with some pods not running grays out and shows message on hover, also the processing rates becomes -1.
=> chore: adding nil check for vertex metrics endpoint and rendering UI with partial data

pkg/reduce/readloop/readloop.go
we are not acking the dropped messages and this is resulting in leaked go routines.
=> fix: ack the dropped messages as well

go.mod, go.sum, pkg/shuffle/shuffle.go, pkg/shuffle/shuffle_test.go, pkg/sources/source.go, pkg/udf/map_udf.go, pkg/udf/reduce_udf.go, test/reduce-e2e/testdata/complex-reduce-pipeline.yaml, test/reduce-e2e/testdata/complex-sliding-window-pipeline.yaml
fixes #600 
Move from `fnv` to `mumur3` for randomized keying when there is no rekeying using the vertex name as the seed.
=> feat: use randomized shuffle using vertex name as the seed

docs/specifications/edges-and-buffers.md, docs/user-guide/inter-step-buffer-service.md, docs/user-guide/sources/transformer/builtin-transformers/README.md, docs/user-guide/sources/transformer/builtin-transformers/event-time-extractor.md, docs/user-guide/sources/transformer/builtin-transformers/filter.md, docs/user-guide/sources/transformer/overview.md, mkdocs.yml, pkg/shared/expr/eval_string.go
=> docs: add docs for source data transformer

pkg/isb/stores/jetstream/reader.go, pkg/reconciler/vertex/scaling/scaling.go, pkg/reconciler/vertex/scaling/scaling_test.go
1. Excluding `ackpending` from Pending() will cause unexpected scalding down to 0 when it takes a long time to process a message, and it happens there's no real pending messages in the buffer. Reverted that logic.
2. Let the desired replicas <= pending.
=> fix: desired replicas should not be greater than pending

ui/src/components/pipeline/graph/CustomEdge.tsx, ui/src/components/pipeline/graph/Graph.tsx
For pipeline where vertex branched the watermark for the edge was overlapped by the previous vertex
adding a fix for the same
Previous
Current
=> fix: vertex overlapping watermark

docs/user-guide/environment-variables.md, pkg/apis/numaflow/v1alpha1/const.go, pkg/apis/numaflow/v1alpha1/vertex_types.go, pkg/apis/numaflow/v1alpha1/vertex_types_test.go
Expose the `resources.requests.cpu/memory` and `resources.limits.cpu/memory` to sidecar containers (udf, udsink...) as environment variables.
For example:
```yaml
resources:
requests:
memory: "32Mi"
cpu: "125m"
limits:
memory: "64Mi"
cpu: "250m"
```
will generate:
```
NUMAFLOW_CPU_REQUEST: 1 (roundup to N cores)
NUMAFLOW_CPU_LIMIT: 1 (roundup to N cores)
NUMAFLOW_MEMORY_REQUEST: 33554432
NUMAFLOW_MEMORY_LIMIT: 67108864
```
If `resources.requests.xx` is missing, the corresponding passed in variables will be:
```
NUMAFLOW_CPU_REQUEST: 0
NUMAFLOW_MEMORY_REQUEST: 0
```
If `resources.limits.xx` is missing, the corresponding passed in variables will be:
```
NUMAFLOW_CPU_LIMIT: n (host cpu)
NUMAFLOW_MEMORY_LIMIT: n (host memory)
```
=> feat: expose cpu/mem info to sidecar containers

examples/6-reduce-fixed-window.yaml, pkg/reduce/pbq/store/wal/stores.go
Fixes: #688
`/var/numaflow/pbq/wal` was created with `0644`, there's no issue with it when the vertex pod/containers run as root. If they run as non-root, since it has no `x` permission, there's no way to `cd` to the dir and create wal files.
=> fix: add wal dir x permission

pkg/sources/redisstreams/redisstream_test.go
Fixes: #737 
Unit test was dependent on a golang map having a predictable order, which it doesn't.
=> fix(test): flakey test

pkg/apis/numaflow/v1alpha1/pipeline_types.go, pkg/apis/numaflow/v1alpha1/pipeline_types_test.go, pkg/reconciler/pipeline/controller.go, pkg/reconciler/pipeline/controller_test.go, pkg/reconciler/pipeline/validate_test.go, pkg/udf/function/uds_grpc.go, pkg/watermark/fetch/edge_fetcher.go, pkg/watermark/fetch/edge_fetcher_test.go
`toVertexPartition` in the edge of the `Vertex` object was incorrectly populated to 1 by the pipeline controller because we always set `DeprecatedParallelism` to 1 if it's not set in `pipeline.ListAllEdges()`, which should not be done now.
=> fix: toVertexPartitions for reduce was incorrectly populated to 1

pkg/daemon/server/daemon_server.go, pkg/daemon/server/service/pipeline_metrics_query.go, pkg/daemon/server/service/pipeline_metrics_query_test.go, pkg/daemon/server/service/rater/helper.go, pkg/daemon/server/service/rater/helper_test.go, pkg/daemon/server/service/rater/rater.go, pkg/daemon/server/service/rater/rater_test.go, pkg/daemon/server/service/rater/timestamped_counts.go
Fixes #746 
Showing the processing rate for each of the partitions is important as it helps us identify hot key issue. This change enables the rater to calculate rate for a single pod, such that we can retrieve per-partition rates and display them on UI.
**Before this change**
**After**
=> chore: use metrics to calculate rate for reducer partitions

pkg/watermark/processor/processor_manager_test.go
Processor manager unit test is flaky. [sample run](https://github.com/KeranYang/numaflow/actions/runs/5156561831/jobs/9287719331)
The error message is as follow:
```
=== RUN   TestProcessorManagerWatchForMap
panic: send on closed channel
goroutine 9 [running]:
github.com/numaproj/numaflow/pkg/watermark/store/inmem.(*inMemStore).PutKV(0xc00011f4a0, {0xc0001ea016?, 0xa?}, {0x1425c15, 0x2}, {0xc0001ea020, 0xa, 0x0?})
/home/runner/work/numaflow/numaflow/pkg/watermark/store/inmem/kv_store.go:134 +0x230
github.com/numaproj/numaflow/pkg/watermark/processor.TestProcessorManager.func2()
/home/runner/work/numaflow/numaflow/pkg/watermark/processor/processor_manager_test.go:88 +0x174
created by github.com/numaproj/numaflow/pkg/watermark/processor.TestProcessorManager …
```
=> chore: fix processor manager test goroutine leak

server/cmd/start.go, ui/src/components/common/Breadcrumbs/index.tsx, ui/src/index.tsx
Currently, on refresh we return index.html (default HTML file in your browser when visiting any directory on a web server) content twice when we don't set the baseHref like in this response. This caused all the calls in the UI to be run twice (meaning duplicate logs and API calls). This PR fixes the routing.
Also added a safety check to the Breadcrumbs component, to provide correct navigation for trailing slashes.
(`Unknown -> Namespaces > default (simple-pipeline)`)
=> fix: duplicate ui served from gin Router

README.md, docs/README.md
=> docs: update roadmap

docs/user-guide/reference/autoscaling.md, pkg/apis/numaflow/v1alpha1/const.go, pkg/reconciler/vertex/scaling/scaling.go, pkg/reconciler/vertex/scaling/scaling_test.go
when there is skewness between the partitions, pods won't autoscale which results in a deadlock state (pods not scaling up and the previous vertex not writing because one of the partitions is full). To fix this we need to consider the processing rate and pending information of each partition separately and calculate the desired replicas and take the max desired replicas across all the partitions.
=> chore: consider all the partitions separately while autoscaling

pkg/daemon/server/service/rater/pod_tracker.go, pkg/daemon/server/service/rater/rater.go
go doc
```
// Body represents the response body.
//
// The response body is streamed on demand as the Body field
// is read. If the network connection fails or the server
// terminates the response, Body.Read calls return an error.
//
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body. The default HTTP client's Transport may not
// reuse HTTP/1.x "keep-alive" TCP connections if the Body is
// not read to completion and closed.
//
// The Body is automatically dechunked if the server replied
// with a "chunked" Transfer-Encoding.
//
// As of Go 1.12, the Body will also implement io.Writer
// on a successful "101 Switching Protocols" response, …
```
=> fix: resource leak inside daemon server

pkg/daemon/server/service/rater/pod_tracker.go, pkg/daemon/server/service/rater/pod_tracker_test.go, pkg/daemon/server/service/rater/rater_test.go
What did we fix?
Bug in pod tracking logic, assume we have a vertex with 10 active pods and it scales down to 5, but the active pod list will still have 9 pods (only the pod with index 5 will be removed from the list which is wrong we should remove all the pods from index 5 to 9).
How did we fix?
We delete all the pods one by one if it's inactive. We never skip deletion.
=> fix: pod tracker logic for calculating processing rate

pkg/watermark/timeline/offset_timeline.go
It used to be the case that a given OffsetTimeline could be expected to reliably be published to the K/V store in increasing order of offset. This is no longer the case now that multiple goroutines (each reading from a different partition in a Map vertex) can publish to that OffsetTimeline. For example, take two goroutines G1 and G2 both publishing to the same OffsetTimeline:  
- G1 determines watermark x and publishes to offsets 100-101
- G2 determines watermark y and publishes to offsets 102-103
- G2 publishes watermark y for offset 103
- G1 publishes watermark x for offset 101
This PR addresses the case where watermark x = y. The receiver of the OffsetTimeline in this case will see offset 103 prior to offset 101. This should not be considered an error.
Note this error is seen in the …
=> chore: this is no longer an error messages now that there are multiple goroutines publishing to Offset Timeline

ui/src/components/pages/Namespace/partials/NamespaceRowContent/index.tsx, ui/src/utils/fetcherHooks/pipelineViewFetch.ts
- Querying for pods of a vertex with a 30sec periodic refresh, removes the need to refresh the webpage to see updated pod counts
- Removed multiple pipeline labels seen when searching for a namespace
=> fix: minor ui bugs

ui/src/utils/fetcherHooks/pipelineViewFetch.ts
when buffer is full for any partition of the edge, the edge becomes highlighted
=> fix: highlight edge when buffer is full

go.mod, go.sum, pkg/sideinputs/manager/manager.go, pkg/sideinputs/manager/manager_test.go
=> chore: some initial code for side inputs manager

test/fixtures/e2e_suite.go
This was an oversight from back when the Redis version was updated that this was not updated in turn.
=> updated default version of Redis used for e2e

pkg/reduce/data_forward_test.go
fix #895 
We removed retry on GetProcessor failure in a previous PR. Because our test is very restrictedly designed, the unit test is not always able to complete "AddProcessor" for a new processor (where AddProcessor happens in a go routine) before trying to get this new processor. 
Note: Removing retry is okay in real production usage. Since a new healthy processor keeps sending heart beat and publishing watermark/idleWatermark, the processor will eventually be added to the processor list and will be able to be retrieved (we may have a small delay which is acceptable ATM).
=> fix: Reduce idle WM unit test fix

pkg/daemon/server/service/rater/pod_tracker.go, pkg/daemon/server/service/rater/pod_tracker_test.go, pkg/daemon/server/service/rater/rater.go
This is a small refactor to modularize the pod tracker. The data structure of `UniqueStringList` is the implementation detail of pod tracker, hence should not be exposed to the rater. This makes less work for the rater as rater doesn't need to call `getActivePods` followed by `.Contains` to check if a pod is active. This also removes the risk of the rater directly manipulating the `UniqueStringList`. Lastly, if in the future, we decide to replace `UniqueStringList` with another data structure, no code change needs to be made on the rater side.
=> refactor: avoid exposing internal data structures of pod tracker to the rater

pkg/daemon/server/service/rater/uniq_str_list.go
Fixes #863 
See https://github.com/numaproj/numaflow/issues/863#issuecomment-1658656984 for more details about the root cause.
=> fix: avoid potential deadlocks when operating UniqueStringList

ui/package.json, ui/src/components/pages/Pipeline/partials/Graph/partials/CustomEdge/index.test.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/CustomEdge/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/Spec/index.test.tsx, ui/src/types/declarations/pipeline.d.ts, ui/src/utils/fetcherHooks/pipelineViewFetch.ts, ui/yarn.lock
Fixes #876 
- Shows delay of watermark wrt to `time.now()` when hovering on the edge label
- Shows difference in precision from years (~ 5yr 4mo) up to milliseconds (~ 549ms)
=> feat: watermark delay in tooltip

pkg/shared/kvs/inmem/kv_watch.go, pkg/shared/kvs/jetstream/kv_watch.go, pkg/sources/forward/data_forward_test.go, pkg/sources/nats/nats_test.go
if there are no keys in the store we should not retry while trying to calculate the last updated kv time.
=> fix: retry logic for fetching last updated kv time

docs/user-guide/reference/join-vertex.md
It seems bulleted lists don't reliably work unless there's a blank line before them? https://meta.stackexchange.com/questions/36298/list-markdown-doesnt-work-unless-preceded-by-a-blank-line
see result [here](https://github.com/juliev0/numaflow/blob/join-doc-bullets/docs/user-guide/reference/join-vertex.md)
=> fix bulleted list

ui/src/components/pages/Pipeline/partials/Graph/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/style.css
Fixes #952 
Added a fix for missing edges for some pipelines on UI
- Fixed the overflow attribute to display edges which rendered outside the `svg container` and `overflow:visible` was overridden by parent component
=> fix: missing edges on UI

pkg/reconciler/vertex/controller.go
<details>
<summary>logs</summary>
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18f18bd]
goroutine 575 [running]:
github.com/numaproj/numaflow/pkg/reconciler/vertex.(*vertexReconciler).reconcile(0xc0007139f0, {0x257c138, 0xc000b4eae0}, 0xc0001d7180)
/home/runner/work/numaflow/numaflow/pkg/reconciler/vertex/controller.go:115 +0x9bd
github.com/numaproj/numaflow/pkg/reconciler/vertex.(*vertexReconciler).Reconcile(0xc0007139f0, {0x257c138, 0xc000b4e930}, {{{0xc000c92450?, 0x20d4800?}, {0xc000744198?, 0x30?}}})
/home/runner/work/numaflow/numaflow/pkg/reconciler/vertex/controller.go:75 +0x5c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000cb8370, {0x257c138, …
```
=> fix: seg fault inside controller

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.test.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/style.css
Fixes #794 
Fixes #701 
- Added color support for logs based on log levels - (info, error, warn, debug)
- Added initial timestamp to logs for a consistent view
- Added toggles for logs theme (dark/light mode) and logs order (asc/desc order)
- Used bold text for logs for better visibility
=> feat: colored logs for UI with toggle for logs order

pkg/daemon/server/service/rater/pod_tracker.go, test/e2e/functional_test.go
Before PR
After PR
After we separate the sink forwarder, we changed the readTotal metric name to `sink_read_total`, hence we need to introduce a new vertex type key to the pod tracker such that the type key name "sink" can be used to determine which metric to look for.
=> fix: calculate processing rate for sink vertices

docs/user-guide/reference/edge-tuning.md, docs/user-guide/reference/pipeline-tuning.md, mkdocs.yml
=> doc: kill-switch when buffer is full

pkg/daemon/server/service/rater/helper.go, pkg/daemon/server/service/rater/helper_test.go, pkg/daemon/server/service/rater/pod_tracker.go, pkg/daemon/server/service/rater/rater.go, pkg/daemon/server/service/rater/timestamped_counts.go
* Add one more unit test to cover the case when a single pod is serving multiple partitions.
* Refactor the vertex type key usage by making them const and shared between the pod tracker and rater.
* Fix a TODO to make userSpecifiedLookbackSecond static instead of being figured out dynamically every time getRates gets called.
* Break early when looping through the metric label list to find the partition name.
=> refactor: re-arrange some of the rater implementations

go.mod, go.sum, pkg/sdkclient/source/client/client_test.go, pkg/sources/udsource/grpc_udsource.go, pkg/sources/udsource/grpc_udsource_test.go
Such that we distinguish the PendingNotAvailable scenario from there are not pending messages. Hence auto-scaler knows whether to skip scaling or to scale down.
=> fix: allow udsource pending api to return negative count to indicate PendingNotAvailable

server/apis/v1_1/handler.go, server/routes/routes_v1_1.go
- add get vertices metrics API
- add update vertex API
Tested with basic use case locally.
TODO: improvement and more testing
=== Local Test on get vertices metrics ===
=== Local Test on Update ===
unable to update type
unable to update name
update rpu
update scale min
=> feat: update vertex and get vertices metrics APIs

server/apis/v1_1/handler.go, server/apis/v1_1/response_cluster_summary.go, server/apis/v1_1/response_k8s_events.go
Update K8s Events API response structure
Sort the response by timestamp from newest to oldest 
example payload
```
{
"data": [
{
"timestamp": 1695756111000,
"object": {
"kind": "Pod",
"name": "isbsvc-test-js-0"
},
"reason": "Killing",
"message": "Stopping container reloader"
},
{
"timestamp": 1695756111000,
"object": {
"kind": "Pod",
"name": "isbsvc-test-js-0"
},
"reason": "Killing",
"message": "Stopping container metrics"
},
{
"timestamp": 1695753312000,
"object": {
"kind": "Deployment",
"name": "simple-pipeline-test-daemon"
},
"reason": "ScalingReplicaSet",
"message": "Scaled up replica set simple-pipeline-test-daemon-6d8cc9f6f6 to 1"
},
{
"timestamp": 1695753237000,
"object": {
"kind": "Pipeline",
"name": "simple-pipeline"
},
"reason": "ReconcilePipelineFailed",
"message": "Failed to …
```
=> fix: K8s events API

server/apis/v1_1/handler.go
example payload
the list of metrics for a given vertex is sorted by partition0~n
```
{
"data": {
"cat": [
{
"pipeline": "simple-mp-pipeline",
"vertex": "cat",
"processingRates": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
},
"pendings": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
}
},
{
"pipeline": "simple-mp-pipeline",
"vertex": "cat",
"processingRates": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
},
"pendings": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
}
},
{
"pipeline": "simple-mp-pipeline",
"vertex": "cat",
"processingRates": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
},
"pendings": {
"15m": 0,
"1m": 0,
"5m": 0,
"default": 0
}
}
],
"in": [
{
"pipeline": "simple-mp-pipeline",
"vertex": "in",
"processingRates": {
"15m": 500,
"1m": 500,
"5m": 500,
"default": 500
}
}
],
"out": [
{ …
```
=> chore: update return type for vertex metrics

pkg/daemon/server/service/pipeline_watermark_query.go, pkg/reconciler/isbsvc/validate.go, server/apis/v1/handler.go
1. bug fix
previously, to get the pipeline lag we updated the proto file to have from and to in the watermark response
but we only wet these two fields when watermark is enabled
when watermark is disabled, we also need to set the from and to in the query response
2. bug fix
UpdateISBSVC API doesn't use the new request body to udpate
3. update isbsvc validate to have min 3 replicas
3. add TODO
4. use c.BindJSON
5. update kube rest config fetch logic in NewHandler
=> fix: PR review actions

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodInfo/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx
- added CPU row for `used / spec` utilization
- updated the CPU row with millicores (instead of nanocores default)
- update the Memory row with `Mi` for both denominator and numerator
- spaced the pod logs for readability
=> fix: updated pods view tab for vertices

pkg/forward/metrics.go, pkg/sinks/forward/metrics.go, pkg/sources/forward/metrics.go
=> chore: adjust buckets for histogram metrics

pkg/client/clientset/versioned/typed/numaflow/v1alpha1/pipeline.go, server/apis/v1/handler.go
because of https://github.com/kubernetes/kubernetes/issues/80609 
get pipeline doesn't return "kind" and "apiVersion"
since we know the value for these two fields, set the fields in handler manually
test result:
=> fix: get pl kind apiversion

cmd/commands/root.go, cmd/commands/side_inputs_synchronizer.go, pkg/apis/numaflow/v1alpha1/const.go, pkg/apis/numaflow/v1alpha1/vertex_types.go, pkg/shared/kvs/jetstream/kv_store.go, pkg/sideinputs/initializer/initializer.go, pkg/sideinputs/synchronizer/synchronizer.go, pkg/sideinputs/synchronizer/synchronizer_test.go
Fixes: https://github.com/numaproj/numaflow/issues/1160
=> fix: incorrect side inputs watch logic

server/apis/v1/handler.go
Get all the pipelines and isbsvcs at once instead of individual calls.
fixes:#1161
Example Response payload
```
{
"data": [
{
"namespace": "numaflow-system",
"pipelineSummary": {
"active": {
"Healthy": 1,
"Warning": 0,
"Critical": 0
},
"inactive": 0
},
"isbServiceSummary": {
"active": {
"Healthy": 1,
"Warning": 0,
"Critical": 0
},
"inactive": 0
}
},
{
"namespace": "default",
"pipelineSummary": {
"active": {
"Healthy": 2,
"Warning": 0,
"Critical": 0
},
"inactive": 1
},
"isbServiceSummary": {
"active": {
"Healthy": 2,
"Warning": 0,
"Critical": 0
},
"inactive": 0
}
}
]
}
```
=> chore: API cluster summary improvement

docs/core-concepts/inter-step-buffer-service.md, pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go, pkg/apis/numaflow/v1alpha1/jetstream_buffer_service_test.go, pkg/isbsvc/jetstream_service.go, pkg/reconciler/isbsvc/installer/assets/jetstream/nats-cluster.conf, pkg/reconciler/isbsvc/installer/jetstream.go, pkg/reconciler/isbsvc/validate.go, test/api-e2e/api_test.go, test/api-e2e/testdata.go
Fixes #944
This allows for Jetstream event buses to have a replica set 1 instead of the minimum required 3. Modifications taken mostly from the same change done to Argo Events.
Tested this locally by modifying the numaflow install to set the bufferConfig to have replica of 1 for each (instead of the default 3) and then set my ISBS to explicitly have a replica of 1. Then verified I could run the example simple pipeline on the website. Verified in the ISBS that if replicas are not set that it defaults to 3
=> feat: Jetstream support for replica of 1 Fixes #944

ui/src/App.tsx, ui/src/components/common/ErrorIndicator/index.tsx, ui/src/components/common/ErrorIndicator/style.css, ui/src/components/common/SlidingSidebar/index.tsx, ui/src/components/common/SlidingSidebar/partials/Errors/index.tsx, ui/src/components/common/SlidingSidebar/partials/Errors/style.css, ui/src/components/common/SlidingSidebar/partials/PipelineCreate/index.tsx, ui/src/components/pages/Cluster/index.tsx, ui/src/components/pages/Cluster/partials/ClusterNamespaceListing/index.tsx, ui/src/components/pages/Namespace/index.tsx, ui/src/components/pages/Namespace/partials/NamespacePipelineListing/index.tsx, ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx, ui/src/components/pages/Pipeline/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/index.tsx, ui/src/types/declarations/app.d.ts, ui/src/types/declarations/cluster.d.ts, ui/src/types/declarations/graph.d.ts, ui/src/types/declarations/namespace.d.ts, ui/src/utils/fetchWrappers/clusterSummaryFetch.ts, ui/src/utils/fetchWrappers/fetch.ts, ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts, ui/src/utils/fetchWrappers/pipelineFetch.ts, ui/src/utils/fetchWrappers/pipelineUpdateFetch.ts, ui/src/utils/fetcherHooks/pipelineViewFetch.test.ts, ui/src/utils/fetcherHooks/pipelineViewFetch.ts
- Error handling and display for all pages.
- Pipeline load blocking until ready
=> feat: error handling/display for all pages and pipeline load block

docs/user-guide/user-defined-functions/reduce/examples.md
Updated the prerequisite step of the reduce/example.md
This PR is related to the issue #1170
=> fix: updating example.md

config/base/dex/numaflow-dex-server-configmap.yaml, config/install.yaml, config/namespace-install.yaml, server/apis/v1/dexauth.go, server/cmd/start.go, server/routes/routes.go, server/routes/routes_test.go
Local Test
Numaflow Dex Server deployment
```yaml
redirectURIs: 
- https://localhost:8443/numaflow/login
```
Numaflow Server deployment
```yaml
- name: main
image: quay.io/numaproj/numaflow:latest
args:
- "server"
- "--base-href=/numaflow"
```
```yaml
- name: server-init
image: quay.io/numaproj/numaflow:latest
args:
- "server-init"
- "--base-href=/numaflow"
```
https://github.com/numaproj/numaflow/assets/19543684/8e6236e7-31d1-4e09-9fd1-b29bdf797b6e
=> fix: update dex to work with basehref

ui/package.json, ui/src/components/common/SlidingSidebar/partials/ISBCreate/index.test.tsx, ui/src/setupTests.ts, ui/yarn.lock
- ISBCreate component unit test
- Fetch mock setup for unit testing w/ example usage in ISBCreate test
=> fix: ISBCreate test and fetch mock setup

docs/user-guide/user-defined-functions/map/examples.md, mkdocs.yml
Added `examples.md` for the `map` section for the documentation website.
This Pr is in response to the issue #1172
=> docs: adding examples.md for the map section

pkg/reconciler/isbsvc/controller.go, pkg/reconciler/isbsvc/installer/external_redis.go, pkg/reconciler/isbsvc/installer/external_redis_test.go, pkg/reconciler/isbsvc/installer/installer.go, pkg/reconciler/isbsvc/installer/jetstream.go, pkg/reconciler/isbsvc/installer/jetstream_test.go, pkg/reconciler/isbsvc/installer/native_redis.go, pkg/reconciler/isbsvc/installer/native_redis_test.go
When jetstream is not in cluster mode, automatically sets the stream/KV replica to 1. @joelcomp1 
```golang
if r.isbSvc.Spec.JetStream.GetReplicas() < 3 {
// Replica can not > 1 with non-cluster mode
v.Set("otbucket.replicas", 1)
v.Set("procbucket.replicas", 1)
v.Set("stream.replicas", 1)
}
```
=> chore: set stream.replicas=1 when in non-cluster mode

ui/src/components/pages/Pipeline/partials/Graph/index.tsx
Modified minimum and maximum zoom view for the pipeline (Min % = 0, Max % = 150)
Fixes view for graph with large height, prevents the overflow beyond screen boundaries
Ex - 11 udf pods merging into a single sink - shown in a single view
=> fix: graph overflow with large height

ui/src/components/pages/Pipeline/partials/Graph/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/style.css, ui/src/utils/fetcherHooks/pipelineViewFetch.ts
- Added container around generator vertices
- Enabled graph blur while hovering over side inputs
- Added tooltip to generator vertices for operation clarity
=> feat: container for generator vertices

server/common/consts.go
=> chore: increase cookie age to 8 hours

server/apis/v1/handler.go, server/authz/rbac.go
Fix validation for single vertex update, does not update pipeline when validation requested.
Add mutex to permCount map
=> chore: fix update vertex validation

webhook/validator/isbsvc.go, webhook/validator/isbsvc_test.go, webhook/validator/test_utils.go
Don't allow updating an existing isbsvc's persistence strategy. This includes removing, adding and modifying.
=> fix: disallow updating an existing isbsvc's persistence strategy

pkg/sources/forward/data_forward.go
* dropped messages event time will be set to -1, so we should exclude them from watermark propagation
=> fix: dropped messages should not be considered for watermark propagation

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-deployment.yaml, config/install.yaml, config/namespace-install.yaml, server/routes/routes.go, ui/src/App.tsx, ui/src/components/common/SlidingSidebar/partials/ISBCreate/index.tsx, ui/src/components/common/SlidingSidebar/partials/ISBUpdate/index.tsx, ui/src/components/common/SlidingSidebar/partials/PipelineCreate/index.tsx, ui/src/components/common/SlidingSidebar/partials/PipelineUpdate/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/VertexUpdate/index.tsx, ui/src/components/pages/Namespace/partials/DeleteModal/index.tsx, ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx, ui/src/utils/fetchWrappers/clusterSummaryFetch.ts, ui/src/utils/fetchWrappers/namespaceFetch.ts, ui/src/utils/fetchWrappers/namespaceK8sEventsFetch.ts, ui/src/utils/fetchWrappers/namespaceSummaryFetch.ts, ui/src/utils/fetchWrappers/pipelineFetch.ts, ui/src/utils/fetchWrappers/pipelineUpdateFetch.ts, ui/src/utils/fetchWrappers/systemInfoFetch.ts, ui/src/utils/fetcherHooks/pipelineViewFetch.ts, ui/src/utils/fetcherHooks/podsViewFetch.ts
Fixes #1368 
- updated `api/v1` calls to go the access path configured from both backend and frontend
- updated configMap name used in deployment specs
TODO - access path for dex server
=> fix: access path for api/v1 route

go.mod, go.sum, pkg/sources/forward/data_forward.go, pkg/udf/forward/forward.go
* update the numaflow-go version hence the built-in source transformer uses the latest SDK.
* for messages dropped by the source transformer, use the original event time to calculate the source watermark.
The rationale is that a dropped message is also a processed message, it should be included in the watermark calculation.
To be determined: if a user chooses to use the source transformer to assign event time and filter, should we require assigning event time to dropped messages? (I think we should because it gives user the full control of event time. However it will be a breaking change for existing pipelines.)
=> fix: update numaflow-go version

ui/src/utils/index.test.ts, ui/src/utils/index.tsx
Setting "/" as baseHref was not working as expected while configuring the access path, due to incorrect URL creation.
=> fix: updated access path config for root path

docs/user-guide/sources/transformer/overview.md, go.mod, go.sum, pkg/sources/forward/data_forward.go, pkg/sources/transformer/builtin/filter/filter.go, pkg/sources/transformer/builtin/time_extraction_filter/time_extraction_filter.go
=> fix: include dropped messages in source watermark calculation

go.mod, go.sum, pkg/sdkclient/source/client/client.go, pkg/sdkclient/source/client/client_test.go, pkg/sdkclient/source/client/interface.go, pkg/sources/forward/data_forward.go, pkg/sources/forward/data_forward_test.go, pkg/sources/generator/tickgen.go, pkg/sources/http/http.go, pkg/sources/kafka/reader.go, pkg/sources/nats/nats.go, pkg/sources/sourcer/sourcer.go, pkg/sources/udsource/grpc_udsource.go, pkg/sources/udsource/grpc_udsource_test.go, pkg/sources/udsource/user_defined_source.go, pkg/sources/udsource/utils/offset.go, pkg/sources/udsource/utils/offset_test.go, test/idle-source-e2e/idle_source_test.go, test/idle-source-e2e/testdata/idle-source-reduce-pipeline.yaml
=> chore: introducing partitions for udsource

pkg/sdkclient/const.go, pkg/sdkclient/grpc_resolver/client_resolver.go, pkg/sdkclient/mapper/client.go, pkg/sdkclient/mapstreamer/client.go, pkg/sdkclient/options.go, pkg/sdkclient/reducer/client.go, pkg/sdkclient/sessionreducer/client.go, pkg/sdkclient/sourcetransformer/client.go, pkg/shared/util/grpc_utils.go
Updates the grpc client to use multiple sockets for TCP connections instead of a single port with reuse
=> feat: update tcp client connections

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-deployment.yaml, config/install.yaml, config/namespace-install.yaml
- added env variable for namespace for accessing secrets and configMap for the `server-secrets-init` container
- enabled access to UI by completing initialization for the server
=> fix: server-secrets-init container restart 

ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx, ui/src/types/declarations/pipeline.d.ts
Quentin Faidide from numaflow slack channel:
> The units are not shown in the Processing Rates panel. It's not the end of the world since it's easy to check against the 1m one with the unit in the graph, but it's free lunch to add it and have users figuring out instantly what the numbers means
=> chore: add the unit for vertex processing rates on ui

pkg/sources/kafka/reader.go
fix: #1408 
https://github.com/IBM/sarama/blob/4b9e8f6681955d56471eafa1b43b62085a58e1c6/consumer_group.go#L687-L689
```
// To follow upstream conventions, you are expected to mark the offset of the
// next message to read, not the last message read. Thus, when calling `MarkOffset`
// you should typically add one to the offset of the last consumed message.
```
https://github.com/IBM/sarama/blob/4b9e8f6681955d56471eafa1b43b62085a58e1c6/consumer_group.go#L823-L825
```
func (s *consumerGroupSession) MarkMessage(msg *ConsumerMessage, metadata string) {
s.MarkOffset(msg.Topic, msg.Partition, msg.Offset+1, metadata)
}
```
=> fix: Kafka source reads duplicated messages

ui/src/components/pages/Namespace/partials/NamespaceListingWrapper/PipelineListing/index.tsx
fix: #1443
Fixes the UI filter by status for pipelines which was earlier broken.
**Previously:**
**With Change:**
=> fix: UI Filter by status for pipelines doesn't work as expected

pkg/apis/numaflow/v1alpha1/pipeline_types.go, pkg/apis/numaflow/v1alpha1/pipeline_types_test.go
fix: #1446
- Explained the problem in the issue linked.
- The fix is pretty straight forward, we keep track of visited vertexes in a map.
- Updated the unit test to capture the issue reported.
Thanks for reviewing! open for comments and improvements
=> fix: GetDownstreamEdges is not cycle safe

test/sdks-e2e/sdks_test.go, test/sdks-e2e/testdata/simple-keyed-reduce-pipeline.yaml
Https://github.com/numaproj/numaflow-java/pull/90 fixed the test. I haven't merged the sdk changes but updated the image in quay.io.
=> chore: enable reduce java sdk e2e test

pkg/apis/numaflow/v1alpha1/pipeline_types.go, pkg/apis/numaflow/v1alpha1/redis_buffer_service.go, pkg/apis/numaflow/v1alpha1/side_inputs.go, pkg/apis/numaflow/v1alpha1/vertex_types.go
The default `resource` is used as a reference to all the places that need to have a resource setting (for example, a vertex numa container), once there's a customization on the particular container resource, it updates all, which is wrong. 
Fix it by referencing to a new instance of the default resource.
=> fix(controller): incorrect cpu/mem resources calculation

test/reduce-sdk-e2e/testdata/reduce-stream/reduce-stream-go.yaml, test/reduce-sdk-e2e/testdata/reduce-stream/reduce-stream-java.yaml
Address comment in https://github.com/numaproj/numaflow/pull/1476#discussion_r1464421083
=> chore: use longer window to verify the reduce streamer return early before window gets closed

pkg/shared/idlehandler/idlehandler.go, pkg/udf/map_udf.go
Add idle handler offset nil check to fix the panic.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1d493cc]
goroutine 369 [running]:
github.com/numaproj/numaflow/pkg/watermark/publish.(*publish).PublishIdleWatermark(0xc000598120, {0xc00064c640?, 0x41?, 0x3bb0be0?}, {0x0, 0x0}, 0x1)
/home/runner/work/numaflow/numaflow/pkg/watermark/publish/publisher.go:207 +0x16c
github.com/numaproj/numaflow/pkg/shared/idlehandler.PublishIdleWatermark({0x294e5e8, 0xc0007dc300}, {0x294ed20, 0xc000222310}, {0x294eee0, 0xc000598120}, {0x294ef18, 0xc00065eb60}, 0xc00061e0a0?, {0x258897f, ...}, ...)
/home/runner/work/numaflow/numaflow/pkg/shared/idlehandler/idlehandler.go:62 +0x645 …
```
=> fix: add idle handler offset nil check

pkg/isbsvc/jetstream_service.go
Closes #820
Now that we have https://github.com/nats-io/nats-server/pull/5079 we should remove the sleep
=> chore: remove sleep now that we have fix in jetstream

pkg/sources/kafka/handler.go, pkg/sources/kafka/reader.go
Closes #1541
Initialize inflightAcks channel to not nil channel to avoid hanging on cleanup function when there are no messages to acknowledge.
How to Test/Reproduce:
1. setup a Kafka client and a Kafka topic with 10 partitions
2. in a bash script, set Kafka client to send 10 messages per second
3. setup a Numaflow pipeline with source vertex to consume from the Kafka client (disable autoscaling)
4. manually scale source vertex to 12 or more pods (`kubectl scale vtx <vtx_name> --replicas=12`)
5. manually delete pod-0
6. wait for a new pod-0 to restart
7. verify it has no topics assigned to it in the metrics: `kafka_source_read_total`
8. scale down to 1 pod
9. at this point, before the fix, the messages flow to the log sink would stop. After the fix, pod-0 is not stuck in the cleanup state …
=> fix: initialize inflightAcks channel to not nil channel

ui/src/components/common/SpecEditor/index.tsx
This PR fixes the text over flow from the error message in the specEditor from the issue here https://github.com/numaproj/numaflow/issues/1413
=> fix: error message that cause Buttons overflow in the UI

test/diamond-e2e/testdata/cycle-backward.yaml, test/diamond-e2e/testdata/cycle-to-self.yaml, test/diamond-e2e/testdata/join-on-reduce-pipeline.yaml, test/diamond-e2e/testdata/join-on-sink.yaml, test/e2e/testdata/even-odd.yaml, test/idle-source-e2e/testdata/idle-source-reduce-pipeline.yaml, test/idle-source-e2e/testdata/kafka-pipeline.yaml, test/reduce-one-e2e/testdata/complex-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/complex-sliding-window-pipeline.yaml, test/reduce-one-e2e/testdata/simple-keyed-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/simple-non-keyed-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/simple-reduce-pipeline-wal.yaml, test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-go.yaml, test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-java.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-go.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-java.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-sum-pipeline.yaml, test/sdks-e2e/testdata/flatmap-stream.yaml, test/sdks-e2e/testdata/flatmap.yaml, test/sdks-e2e/testdata/simple-keyed-reduce-pipeline.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-go.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-java.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-python.yaml, test/sideinputs-e2e/testdata/reduce-sideinput-pipeline.yaml, test/udsource-e2e/testdata/simple-source-go.yaml, test/udsource-e2e/testdata/simple-source-java.yaml, test/udsource-e2e/testdata/simple-source-python.yaml
To be consistent with the recent CI improvements, as per [#1363](https://github.com/numaproj/numaflow/issues/1363)
=> chore: update example image tags to use stable

cmd/commands/server.go, config/advanced-install/namespaced-controller-wo-crds.yaml, config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-deployment.yaml, config/base/shared-config/numaflow-cmd-params-config.yaml, config/install.yaml, config/namespace-install.yaml, server/cmd/server/start.go, server/routes/routes.go, server/routes/routes_test.go, ui/LICENSE, ui/package.json, ui/src/App.tsx, ui/src/components/common/SlidingSidebar/partials/ISBUpdate/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/VertexUpdate/index.tsx, ui/src/components/common/SpecEditor/index.tsx, ui/src/components/pages/Namespace/partials/NamespaceListingWrapper/ISBServiceCard/ISBServiceCard.tsx, ui/src/components/pages/Namespace/partials/NamespaceListingWrapper/index.tsx, ui/src/components/pages/Namespace/partials/PipelineCard/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/CustomNode/style.css, ui/src/components/pages/Pipeline/partials/PipelineSummaryStatus/index.tsx, ui/src/components/plugin/NumaflowMonitorApp/App.tsx, ui/src/types/declarations/app.d.ts, ui/src/utils/fetchWrappers/readOnlyInfoFetch.ts, ui/src/utils/models/readOnlyInfo.ts, ui/yarn.lock
- Added support to toggle Read Only View for Numaflow UI
- Update boolean `server.readonly` in `numaflow-cmd-params-config` to toggle view
- Added new endpoint - `/api/v1/readonlyinfo` to be used in the UI
=> feat: read only view for UI

test/diamond-e2e/testdata/cycle-backward.yaml, test/diamond-e2e/testdata/cycle-to-self.yaml, test/diamond-e2e/testdata/join-on-reduce-pipeline.yaml, test/diamond-e2e/testdata/join-on-sink.yaml, test/e2e/testdata/even-odd.yaml, test/idle-source-e2e/testdata/idle-source-reduce-pipeline.yaml, test/idle-source-e2e/testdata/kafka-pipeline.yaml, test/reduce-one-e2e/testdata/complex-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/complex-sliding-window-pipeline.yaml, test/reduce-one-e2e/testdata/simple-keyed-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/simple-non-keyed-reduce-pipeline.yaml, test/reduce-one-e2e/testdata/simple-reduce-pipeline-wal.yaml, test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-go.yaml, test/reduce-two-e2e/testdata/reduce-stream/reduce-stream-java.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-go.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-java.yaml, test/sdks-e2e/testdata/flatmap-stream.yaml, test/sdks-e2e/testdata/flatmap.yaml, test/sdks-e2e/testdata/simple-keyed-reduce-pipeline.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-go.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-java.yaml, test/sdks-e2e/testdata/transformer/event-time-filter-python.yaml, test/udsource-e2e/testdata/simple-source-go.yaml, test/udsource-e2e/testdata/simple-source-java.yaml
Set the `imagePullPolicy` to `Always`. This is because an issue arises when testing locally, where if changes are made and pushed to the same tag, i.e. `stable`, the cached image is used, and so the changes will not be reflected. This is because, the default image pull policy when the `imagePullPolicy` is not set and the tag `latest` is not used, is `IfNotPresent`. This is not the behaviour we would like, i.e. we want to pull the new image each time we overwrite the `stable`, `test`, etc. tag.
=> chore: set image pull policies to always

test/e2e/functional_test.go
We hash the message ID and distribute the messages to different partitions based on that hash value. Now messages can end up in any partition, not just the first one
=> fix: flaky TestDropOnFull 

pkg/sinks/blackhole/blackhole.go, pkg/sinks/blackhole/blackhole_test.go, pkg/sinks/kafka/kafka.go, pkg/sinks/kafka/kafka_test.go, pkg/sinks/logger/log.go, pkg/sinks/logger/log_test.go, pkg/sinks/sink.go, pkg/sinks/sinker.go, pkg/sinks/udsink/sink.go
Now that we have a separate forwarder for the sink, our sinks don't need to implement the forwarder interface.
=> chore: Refactor Sinks to Avoid Implementing Forwarder Interface

cmd/commands/server_secrets_init.go, config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-deployment.yaml, config/install.yaml, config/namespace-install.yaml
Stop initializing secrets for local user auth during UX server starts when auth is disabled, so that we don't always need to have secret read/write privileges for `numaflow-server-sa`.
=> chore: do not create init-secrets when auth is disabled

docs/user-guide/sinks/overview.md, mkdocs.yml
fix the following warning and make the doc accessible
```
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- user-guide/sinks/fallback.md
```
=> doc: add "nav" for fallback-sink

pkg/sdkclient/const.go, pkg/sdkclient/grpc/grpc_utils.go, pkg/sdkclient/grpc_resolver/client_resolver.go
This transitions the multiproc client to use a UDS socket instead of TCP.
We will receive the number of clients to start in the ServerInfo metadata 
And we will use UDS sockets in the format
```
unix:///var/run/numaflow/multiproc#serv_num.sock
```
Client side changes for [this](https://github.com/numaproj/numaflow-python/issues/161)
=> chore: UDS based multiproc server

pkg/reduce/pbq/pbq.go
* fixes flaky reduce-e2e tests
=> chore: avoid no-ack when ctx is canceled

ui/src/App.css, ui/src/App.tsx, ui/src/components/common/SummaryPageLayout/index.tsx, ui/src/components/plugin/NumaflowMonitorApp/App.css, ui/src/components/plugin/NumaflowMonitorApp/App.tsx
Summary bar was overlaying over other components because of higher zIndex.
This PR fixes that.
=> fix: summary bar overlay fix for plugin

test/sdks-e2e/sdks_test.go, test/sdks-e2e/testdata/transformer/event-time-filter-rust.yaml
This PR introduces a new test for the Rust SDK aimed at ensuring the functionality of the source transformer module. By integrating this test, we aim to maintain high code quality and reliability of the transformations performed by this module.
Fixes -https://github.com/numaproj/numaflow-rs/issues/56
- Added Rust SDK test for source transformer to verify its correctness and stability.
The added tests were executed locally to confirm their effectiveness. Results confirm that the new Rust SDK test for the source transformer runs successfully without introducing regressions.
=> test: added rust sdk test for source transformer 

.github/workflows/ci.yaml
This solves the problem that codecov does not work for some scenarios.
=> test: reconfigure codecov settings

.github/workflows/ci.yaml
Image registry is actually not in-use during e2e tests - we use `make start` to install the manifests which set the image pull policy to `ifNotPresent`, and during image build, we always import the built image to the cluster.
Closes: https://github.com/numaproj/numaflow/issues/1802
=> test: disable image registry creation in e2e test

.github/workflows/ci.yaml, .github/workflows/release.yml, cmd/commands/server.go, config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-deployment.yaml, config/base/shared-config/numaflow-cmd-params-config.yaml, config/install.yaml, config/namespace-install.yaml, pkg/daemon/client/grpc_daemon_client_test.go, pkg/daemon/client/restful_daemon_client_test.go, pkg/daemon/server/service/health_status.go, pkg/daemon/server/service/health_status_test.go, pkg/shared/clients/nats/client_pool_test.go, pkg/shared/clients/nats/nats_client_test.go, pkg/shared/clients/nats/options_test.go, pkg/shared/clients/nats/test/server.go, pkg/shared/ewma/simple_ewma_test.go, pkg/shared/idlehandler/idlehandler_test.go, server/apis/v1/handler.go, server/cmd/server/start.go, server/cmd/server/start_test.go, server/routes/routes.go
Added an option to use RESTful client to access daemon service.
```
```
This is useful when there's a breaking change on daemon service protobuf, while the pipeline can not run the same version of code as the UX server (e.g. UX server is installed in cluster scope, while controllers are in namespace scope, UX server and controllers do not follow the same release cadence). In this case, using RESTful client will have better UX experience, which will not display errors.
=> feat: enable restful daemon client option for UX server

pkg/reconciler/vertex/scaling/scaling.go
=> fix: should never scale down to < min

pkg/reconciler/isbsvc/controller.go, pkg/reconciler/isbsvc/installer/installer.go, pkg/reconciler/pipeline/controller.go
This PR moved setting `ObservedGeneration` at the beginning of the reconciliation process for pipeline and ISBService.  Currently, `ObservedGeneration` is setting at the end which can cause problems when we exit the reconciliation process early.
=> chore: move setting ObservedGeneration at the beginning of the reconciliation process

serving/Cargo.lock, serving/source-sink/Cargo.toml, serving/source-sink/src/config.rs, serving/source-sink/src/main.rs, serving/source-sink/src/metrics.rs, serving/source-sink/src/sink.rs
=> chore: mono-vertex code review

examples/21-simple-mono-vertex.yaml
Based on user request on the ex.
=> chore: add transformer to MonoVertex example

rust/monovertex/src/forwarder.rs, rust/monovertex/src/lib.rs, rust/monovertex/src/metrics.rs
=> chore: avoid partial acks

pkg/apis/numaflow/v1alpha1/container_builder.go, pkg/apis/numaflow/v1alpha1/vertex_types_test.go
=> fix: default resources mutated when applying templates

.dockerignore, Dockerfile, Makefile, rust/Cargo.lock, rust/numaflow-models/Cargo.toml, rust/numaflow-models/templates/Cargo.mustache, rust/servesink/Cargo.toml
closes #1924 
- Builds Rust static binaries
- Uses `scratch` as base for final image
=> chore: switch to scratch base image

pkg/daemon/server/service/rater/helper.go, pkg/daemon/server/service/rater/helper_test.go, pkg/mvtxdaemon/server/service/rater/helper.go, pkg/mvtxdaemon/server/service/rater/helper_test.go
fixes https://github.com/numaproj/numaflow/issues/1960
When the rater cannot calculate the processing rate due to any missing data, we should send a negative value to indicate that the rate is not available instead of 0
This helps with a corner case where the scaler can consider this as the TPS to be 0 and cause unnecessary scale downs.
=> chore: send negative value rateNotAvailable

test/fixtures/redis_check.go, test/reduce-two-e2e/reduce_two_test.go
We use a 5s ticker to retry redis check in e2e, the check start with waiting for 5s before the first check, adding a lot of unnecessary wait time. Especially in test cases where we call multiple redis checks. This change immediately checks to reduce the 5 second wait.
Before the change:
```
--- PASS: TestDiamondSuite (482.58s)
--- PASS: TestDiamondSuite/TestCycleBackward (119.63s)
--- PASS: TestDiamondSuite/TestCycleToSelf (118.82s)
--- PASS: TestDiamondSuite/TestJoinOnMapPipeline (69.46s)
--- PASS: TestDiamondSuite/TestJoinOnReducePipeline (71.50s)
--- PASS: TestDiamondSuite/TestJoinOnSinkVertex (69.61s)
```
After:
```
--- PASS: TestDiamondSuite (365.96s)
--- PASS: TestDiamondSuite/TestCycleBackward (69.73s)
--- PASS: TestDiamondSuite/TestCycleToSelf (68.09s)
--- PASS: …
```
=> chore: reduce 5 second wait time every time redis sink check runs in e2e

hack/update-codegen.sh
`make codegen` has the following warning,
```
WARNING: generate-internal-groups.sh is deprecated.
WARNING: Please use k8s.io/code-generator/kube_codegen.sh instead.
```
which can cause similar permission denied issue as https://github.com/numaproj/numaplane/pull/214
=> chore: use `kube_codegen.sh` instead in codegen.

api/json-schema/schema.json, api/openapi-spec/swagger.json, config/base/crds/full/numaflow.numaproj.io_pipelines.yaml, config/install.yaml, config/namespace-install.yaml, docs/APIs.md, examples/1-simple-pipeline.yaml, pkg/apis/numaflow/v1alpha1/generated.proto, pkg/apis/numaflow/v1alpha1/openapi_generated.go, pkg/apis/numaflow/v1alpha1/pipeline_types.go, pkg/reconciler/monovertex/controller.go, pkg/reconciler/monovertex/scaling/scaling.go, pkg/reconciler/pipeline/controller.go, pkg/reconciler/pipeline/controller_test.go, pkg/reconciler/vertex/scaling/scaling.go, rust/numaflow-models/src/models/pipeline_status.rs
=> chore: minor pipeline controller refactor

pkg/apis/numaflow/v1alpha1/const.go, pkg/reconciler/isbsvc/controller.go, pkg/reconciler/isbsvc/controller_test.go, pkg/reconciler/monovertex/controller.go, pkg/reconciler/monovertex/scaling/scaling.go, pkg/reconciler/pipeline/controller.go, pkg/reconciler/pipeline/controller_test.go, pkg/reconciler/vertex/controller.go, pkg/reconciler/vertex/scaling/scaling.go
Closes: #2054
1. Patch instead of update for finalizers change to avoid some of the fields getting updated unexpectedly (e.g. `cpu: 2000m` is updated to `cpu: 2`)
2. Use explicit spec change to patch for pipeline pause/resume, scale replicas, etc.
3. Fixed a bug for pipeline vertex, that every time there's a spec change, it updates the replica to `min`.
4. Fixed a corner case bug, that somehow replicas goes to 0 (might have manually scaled to 0, or some weird testing case), and `updateHash != currentHash`, it then it gets stuck.
=> chore: patch instead of update and bugfix

pkg/reconciler/pipeline/controller.go
It seems if you create a Pipeline with no `metadata.annotations` set (at least if you are using minimized CRDs), then trying to do [this](https://github.com/numaproj/numaflow/blob/v1.3.1/pkg/reconciler/pipeline/controller.go#L827) json patch operation fails with the error "the server rejected our request due to an error in our request". 
This does not happen if a Merge Patch is used instead.
I tested this in the case of:
- an annotation already existed in the Pipeline when the Pipeline was created
- annotations not defined when the Pipeline was created
For both cases, I experimented with adding `lifecycle.desiredPhase: Paused` and also with removing it.
For both, I observed the proper annotation set:
```
metadata:
annotations:
numaflow.numaproj.io/pause-timestamp: "2024-09-20T20:31:47Z" …
```
=> Fix: Use Merge patch rather than json patch for `pause-timestamp` annotation apply

.github/workflows/ci.yaml, Makefile
The Go unit tests are intermittently getting terminated due to the 10 minute timeout we set in Github CI. Tried setting 8 minute timeout with `go test -timeout 8m`. However, even before the Go's test runner timing out, Github timeout was reached. Github UI shows that the `go test` command ran for 9m35sec. https://github.com/numaproj/numaflow/actions/runs/11158574065/job/31015137527
When successful, the unit tests finishes in less than 4minutes. Since we are not able to recreate the issue consistently, this PR adds `-v -timeout 7m` to Go's test runner.
=> Debugging unit test timeout in CI

pkg/reconciler/pipeline/controller.go
Fixes #2083 
I simply swapped 1. the Job creation to occur prior to 2. the creation/deletion/Update of the Vertex CRs. 
Previously the creation of the Jobs was dependent on the Vertex specs ([newBuffers and newBuckets](https://github.com/numaproj/numaflow/blob/v1.3.2/pkg/reconciler/pipeline/controller.go#L325) are [calculated](https://github.com/numaproj/numaflow/blob/v1.3.2/pkg/reconciler/pipeline/controller.go#L254-L282) based on Vertex specs).
So if there's a transient error that occurs after or in the middle of creating/updating the Vertex CRs, the next reconciliation will incorrectly calculate the Jobs it needs to perform, as some or all of the Vertex specs have changed.
=> fix: create buffers and buckets before updating Vertices

docs/user-guide/sinks/kafka.md, pkg/sinks/kafka/kafka.go
partially solves: #2142 
we will be adding `__key_len` in the header to indicate how many keys are going to be in the header. `__key_%d` will have the value at an index.
=> feat: add keys into kafka header while producing

rust/numaflow-core/src/config.rs, rust/numaflow-core/src/error.rs, rust/numaflow-core/src/lib.rs, rust/numaflow-core/src/message.rs, rust/numaflow-core/src/monovertex.rs, rust/numaflow-core/src/monovertex/forwarder.rs, rust/numaflow-core/src/monovertex/metrics.rs, rust/numaflow-core/src/shared/server_info.rs, rust/numaflow-core/src/shared/utils.rs, rust/numaflow-core/src/sink/user_defined.rs, rust/numaflow-core/src/source/user_defined.rs, rust/numaflow-core/src/transformer/user_defined.rs
Fixes the `clippy` warnings for all the variants of the `Error` enum.
```sh
➜  cd rust/numaflow-core
➜  cargo clippy -- --no-deps
warning: variant name ends with the enum's name
--> numaflow-core/src/error.rs:8:5
|
8 |     MetricsError(String),
|     ^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
= note: `#[warn(clippy::enum_variant_names)]` on by default
```
=> chore: Refactor - Rename Error variants

USERS.md
=> chore: add beumer group to USERS

Makefile, rust/build.sh
Allows building multi arch image from Mac using: `make image-multi`
=> chore: Support multi arch image build on Mac hosts

pkg/reconciler/monovertex/controller.go, pkg/reconciler/vertex/controller.go
In some edged cases, e.g. the scaling operations on vertex/mvtx are too frequent (multiple times in 1 second, not caused by human, but some other issue like [this](https://github.com/numaproj/numaplane/issues/353)), the controller can not catch up with each change, and then it can end up with uncleaned up pods running (e.g. the mvtx only has 1 replica, but there are extra pods 3 and 4 running).
This PR fixes the problem.
=> fix: refine vertex/mvtx pod clean up logic

docs/quick-start.md
`even-odd` example in quick-start is broken due to the gRPC protocol change.
Switch to using `main` branch manifests for installation and quick-start examples, which should be always working.
=> fix(docs): use manifests from main branch in quick-start

Makefile
To build multi-platform images, developers may have enabled parallel multi-platform builder using buildx on their laptop. In such cases, the `build-rust-in-docker` stage that is part of the `make start` fails. The `build-rust-in-docker` tries to create a container to copy the binary from the image to host machine. Since the image was built inside the buildx runner, this container creation fails. The `--load` flag should load the image from buildx runner so that container creation will not fail. Also, this flag is ignored if the image build happens natively (without multi-platform buildx runner).
=> chore: Load docker image from buildx runner

config/base/crds/full/numaflow.numaproj.io_interstepbufferservices.yaml, config/install.yaml, config/namespace-install.yaml, pkg/apis/numaflow/v1alpha1/isbsvc_types.go, pkg/reconciler/isbsvc/controller.go, pkg/reconciler/isbsvc/installer/installer.go, pkg/reconciler/isbsvc/installer/installer_test.go
This should sort of fix the problem in https://github.com/numaproj/numaflow/issues/1956.
=> feat: block isbsvc deleting when there is linked pipeline

pkg/apis/numaflow/v1alpha1/container_builder.go, pkg/apis/numaflow/v1alpha1/container_builder_test.go, pkg/apis/numaflow/v1alpha1/container_supplier.go, pkg/apis/numaflow/v1alpha1/mono_vertex_types.go, pkg/apis/numaflow/v1alpha1/mono_vertex_types_test.go, pkg/apis/numaflow/v1alpha1/sink.go, pkg/apis/numaflow/v1alpha1/sink_test.go, pkg/apis/numaflow/v1alpha1/source.go, pkg/apis/numaflow/v1alpha1/source_test.go, pkg/apis/numaflow/v1alpha1/udf.go, pkg/apis/numaflow/v1alpha1/udf_test.go, pkg/apis/numaflow/v1alpha1/vertex_types.go, pkg/apis/numaflow/v1alpha1/vertex_types_test.go, pkg/reconciler/monovertex/controller_test.go, pkg/reconciler/vertex/controller_test.go
Use [Sidecar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) to run ud containers, to make sure they will be started before and terminated after numa container.
=> feat: use sidecar for ud containers [Breaking k8s < v1.29]

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-metrics-proxy-config.yaml, config/install.yaml, config/namespace-install.yaml, server/apis/v1/promql_service_test.go, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/common/FiltersDropdown/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/utils/constants.ts, ui/src/types/declarations/pods.d.ts
Changes in the UI to support visualisation of counter metrics for a pipeline.
1. Metrics added in the config: **forwarder_data_read_total** [ read processing rates ]
2. Placement: **Metrics** tab adjacent to **Logs**. [going forward, placement can be adjusted based on context to enhance debugging experience]
=> feat: counter metrics visualizer for pipeline

pkg/apis/numaflow/v1alpha1/mono_vertex_types.go, rust/numaflow-core/src/config/components.rs, rust/numaflow-core/src/config/monovertex.rs, rust/numaflow-core/src/config/pipeline.rs, rust/numaflow-core/src/metrics.rs, rust/numaflow-core/src/pipeline.rs, rust/numaflow-core/src/shared/metrics.rs
Currently  if the lookbackSeconds is specified in the spec, the metric lag reader does not honor that value and keeps using default 
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
name: simple-mono-vertex
spec:
scale:
lookbackSeconds: 90
```
Before change
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-fovym -f | grep MYDEBUG
2024-12-05T01:01:55.057650Z  INFO numaflow_core::metrics: MYDEBUG LABEL "default" 120
2024-12-05T01:02:04.057950Z  INFO numaflow_core::metrics: MYDEBUG LABEL "default" 120
```
After
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-pfevp -f | grep MYDEBUG
2024-12-05T01:02:55.514563Z  INFO numaflow_core::metrics: MYDEBUG LABEL "default" 90
2024-12-05T01:02:58.514440Z  INFO …
```
=> fix: honor lookbackSeconds in monovertex and rust pipeline

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-metrics-proxy-config.yaml, config/install.yaml, config/namespace-install.yaml, server/apis/v1/promql_service_test.go, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/common/FiltersDropdown/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/utils/constants.ts
=> feat: mvtx gauge metrics support

rust/numaflow-core/src/monovertex.rs, rust/numaflow-core/src/pipeline.rs, rust/numaflow-core/src/shared/utils.rs
We were accidentally setting `max_encoding_message_size` twice instead of setting `max_encoding_message_size` and `max_decoding_message_size` 😅
=> fix: set max decode size of proto message

rust/numaflow-core/src/shared/server_info.rs
Currently our ServerInfo log doesnt show which container is it corresponding to
```
skohli@macos-JQWR9T560R numaflow % kubectl logs simple-mono-vertex-mv-0-oq2s8 -f
2024-12-13T18:25:01.707148Z  INFO numaflow_core: Starting monovertex forwarder with config: MonovertexConfig { name: "simple-mono-vertex", batch_size: 500, read_timeout: 1s, replica: 0, source_config: SourceConfig { source_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/source.sock", server_info_path: "/var/run/numaflow/sourcer-server-info" }) }, sink_config: SinkConfig { sink_type: UserDefined(UserDefinedConfig { grpc_max_message_size: 67108864, socket_path: "/var/run/numaflow/sink.sock", server_info_path: "/var/run/numaflow/sinker-server-info" }), retry_config: …
```
=> chore: add container type to server info log

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-metrics-proxy-config.yaml, config/install.yaml, config/namespace-install.yaml, server/apis/v1/promql_service_test.go, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/utils/constants.ts
Fixes #2243 
- Updates gauge pattern for mono-vertices
- Enhances labels for gauge metrics
- Adds pending lag metrics for pipeline vertices
=> feat: pipeline gauge metrics

pkg/daemon/server/daemon_server.go, pkg/daemon/server/metrics.go, pkg/metrics/metrics.go, pkg/mvtxdaemon/server/daemon_server.go, pkg/mvtxdaemon/server/metrics.go
```
build_info{component="daemon",component_name="simple-pipeline",platform="linux/arm64",version="latest+7450e16.dirty"} 1
pipeline_build_info{pipeline="simple-pipeline",platform="linux/arm64",version="latest+7450e16.dirty"} 1
```
=> chore: use same metric to expose binary build info

examples/21-simple-mono-vertex.yaml, rust/numaflow-core/src/config/components.rs, rust/numaflow-core/src/config/monovertex.rs, rust/numaflow-core/src/config/pipeline.rs, rust/numaflow-core/src/monovertex.rs, rust/numaflow-core/src/monovertex/forwarder.rs, rust/numaflow-core/src/pipeline.rs, rust/numaflow-core/src/pipeline/forwarder/source_forwarder.rs, rust/numaflow-core/src/shared/create_components.rs, rust/numaflow-core/src/source.rs
Using the below env, we can disable the read ahead in source for both Monovertex and async pipeline
```
containerTemplate:
env:
- name: READ_AHEAD
value: "false"
```
=> chore: Expose env to disable read ahead in source

pkg/reconciler/isbsvc/controller.go, pkg/reconciler/pipeline/controller.go
Using non domain-qualified finalizer name might cause a warning.
https://github.com/kubernetes/kubernetes/blob/f836773540cc83488250a12637e7d924078ef284/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L89
=> chore: use domain-qualified finalizer name

pkg/apis/numaflow/v1alpha1/deprecated.go, pkg/apis/numaflow/v1alpha1/jetstream_buffer_service.go, pkg/apis/numaflow/v1alpha1/jetstream_buffer_service_test.go, pkg/apis/numaflow/v1alpha1/redis_buffer_service.go, pkg/apis/numaflow/v1alpha1/redis_buffer_service_test.go, pkg/reconciler/isbsvc/installer/jetstream.go, pkg/reconciler/isbsvc/installer/native_redis.go
Starting from k8s v1.27, [PVC auto deletion](https://kubernetes.io/blog/2023/05/04/kubernetes-1-27-statefulset-pvc-auto-deletion-beta/) was introduced, became stable in v1.32. Hence we don't need to handle it any more.
Backward compatible with k8s < v1.27, verified in v1.26.
=> chore: cascade deletion on isbsvc pvc

rust/Cargo.lock, rust/numaflow-core/Cargo.toml, rust/numaflow-core/src/lib.rs, rust/numaflow-core/src/source/serving.rs, rust/numaflow/Cargo.toml, rust/numaflow/src/main.rs, rust/serving/src/app/jetstream_proxy.rs, rust/serving/src/lib.rs, rust/serving/src/pipeline.rs
The `rustls` crate is used to generate SSL certs for metrics server of the monovertex.  The metrics server handles `/metrics` and all the k8s health check endpoints (`/livez`, `/readyz` and `/sidecar-livez`). Since the `CryptoProvider` was not initialized, `rustls` was crashing:
```
2025-01-08T07:00:47.475519Z  INFO numaflow_core::source: Started streaming source with batch size: 500
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.19/src/crypto/mod.rs:249:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at …
```
=> fix: Initialize rustls's CryptoProvider early in the code

.github/workflows/nightly-build.yml, .github/workflows/release.yml
> Artifact actions v3 will be closing down by January 30, 2025. You are receiving this email because you have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact.
It looks like for our usage, all we need to do is change the version tag https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> chore: Migrate from upload/download artifacts action v3 to v4

test/fixtures/expect.go, test/fixtures/util.go, test/fixtures/when.go, test/monovertex-e2e/monovertex_test.go
=> test: more e2e test for monovertex

pkg/reconciler/monovertex/controller.go, pkg/reconciler/vertex/controller.go
=> fix: lastScaledAt not updated during autoscaling down

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx, ui/src/types/declarations/pods.d.ts
enhanced numaflow logs to: 
- added monospacing
- updated logs font, removed colours for log level
- allow wrapping lines (preventing horizontal scroll)
- ability to download logs (format - "{pod_name}-{container_name}.txt")
- ability to add / remove timestamps from the beginning of logs
- add filters for log levels (info, error, warn, debug)
=> feat: logs enhancements

pkg/reconciler/isbsvc/controller.go, pkg/reconciler/isbsvc/controller_test.go, pkg/reconciler/monovertex/controller.go
Closes: #2336
1. Clean up mvtx related metrics with best effort
2. Always use finalizer for ISBSvc regardless of pvc used or not, so that it can be used to do all the clean up.
=> fix: clean up metrics for deleted mvtx

rust/numaflow-core/src/monovertex.rs, rust/numaflow-core/src/monovertex/forwarder.rs, rust/numaflow-core/src/pipeline.rs, rust/numaflow-core/src/pipeline/forwarder/source_forwarder.rs, rust/numaflow-core/src/shared/create_components.rs, rust/numaflow-core/src/source.rs, rust/numaflow-core/src/transformer.rs
* Makes source transformer a sub-component of source.
* Removes streaming functionality for transformer, since source transformer is not meant for long running requests.
=> chore: make transformer sub component of source

ui/src/components/common/MetricsModalWrapper/index.tsx, ui/src/components/common/MetricsModalWrapper/partials/MetricsModal/index.tsx, ui/src/components/common/MetricsModalWrapper/style.css, ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/Buffers/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx
- adds the framework for contextual redirection of metrics
- covers vertex pending metrics flow
=> feat: contextual flow for metrics

pkg/reconciler/pipeline/controller.go
=> fix: more criteria to detect lifecycle changes, fixes: #2331

ui/src/components/common/SlidingSidebar/partials/K8sEvents/index.tsx
Fixes https://github.com/numaproj/numaflow/issues/1764. Created rows per page option so events being displayed is not fixed at 6.
_Edit:_  Changed style of dropbox:
=> feat: rows/page dropbox. Fixes #1764

.github/workflows/ci.yaml
From [2.10.24](https://github.com/bitnami/containers/pull/76503/files), there's no way to run `bitnami/nats` for JetStream in Github Action Services any more, have to use a different approach to do it.
The problem is there's no way to run `/nats-server -js` with Github Services - can not specify args, can specify endpoint but can not specify endpoint with args.
=> fix(test): use different approach to start jetstream service

rust/numaflow-core/src/sink.rs, rust/numaflow-core/src/source.rs
@yhl25 and I were debugging a scenario where udsink panics. We observed that numa container wasn't restarting as it should. Fixed the error handling in this case.
Before PR:
```
2025-01-28T05:21:06.974698Z ERROR numaflow_core::source: Nak received for offset offset=String(StringOffset { offset: b"MTczODA0MTY2Njk0NzEwODU2NC0x", partition_idx: 0 })
2025-01-28T05:21:06.974694Z ERROR numaflow_core::source: Nak received for offset offset=String(StringOffset { offset: b"MTczODA0MTY2Njk0NzEwODU2NC0w", partition_idx: 0 })
2025-01-28T05:21:06.974628Z ERROR numaflow_core::sink: Error writing to sink e=Grpc("status: Unknown, message: \"panic inside sink handler: sink fn panicked on multiple of 3\", details: [], metadata: MetadataMap { headers: {} }")
```
With this PR:
```
2025-01-28T06:50:48.818759Z …
```
=> fix: error handling in case of udsink failures

server/apis/v1/handler.go, server/apis/v1/handler_test.go, ui/src/utils/fetcherHooks/podsViewFetch.ts
In the call to `pods-info` API for UI, get status of sidecar containers (udsink, udsource etc) as well.
=> fix: get status of init containers in pods-info API call

server/apis/v1/handler.go, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx
Timestamp is added to all logs from K8S API. 
'All' filter will show all logs and only logs with level info / name will come under respective filter.
Fixes #2354 
Fixes #2341 
Fixes #2342
=> fix: timestamp and level filter fix for logs

ui/src/utils/fetcherHooks/podsViewFetch.ts
=> feat: moving ud containers logs as default in pods view

config/advanced-install/namespaced-numaflow-server.yaml, config/advanced-install/numaflow-server.yaml, config/base/numaflow-server/numaflow-server-metrics-proxy-config.yaml, config/install.yaml, config/namespace-install.yaml, ui/src/components/common/MetricsModalWrapper/index.tsx, ui/src/components/common/MetricsModalWrapper/partials/MetricsModal/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/Buffers/index.tsx, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/ProcessingRates/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/ContainerInfo/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/common/Dropdown/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/common/FiltersDropdown/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/utils/constants.ts, ui/src/types/declarations/pods.d.ts, ui/src/utils/fetchWrappers/metricsFetch.ts
Fixes #2315 
- adding contextual flow for processing rates and cpu/memory metrics
=> feat: contextual flow for remaining metrics

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx
1. In case logs API returns an error mssg, add/remove timestamp wouldn't work. Show the error message as it is.
2. Fixes search and negate search functionality in case of previous terminated container logs.
=> fix: error state & search/negate search in case of prev terminated logs

ui/src/components/common/MetricsModalWrapper/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx
- Remove hyperlink for contextual navigation when metrics is not in config map
- Remove `default` label for pending metrics
- Sorted tooltip for metrics charts in descending order based on value
- Fixed tooltip spacing
=> fix: sorting metrics chart tooltip values

rust/Cargo.lock, rust/numaflow-core/src/config/monovertex.rs, rust/serving/Cargo.toml, rust/serving/src/app.rs, rust/serving/src/app/callback.rs, rust/serving/src/app/callback/state.rs, rust/serving/src/app/callback/store.rs, rust/serving/src/app/callback/store/memstore.rs, rust/serving/src/app/callback/store/redisstore.rs, rust/serving/src/app/jetstream_proxy.rs, rust/serving/src/app/message_path.rs, rust/serving/src/app/response.rs, rust/serving/src/app/tracker.rs, rust/serving/src/callback.rs, rust/serving/src/config.rs, rust/serving/src/consts.rs, rust/serving/src/error.rs, rust/serving/src/lib.rs, rust/serving/src/pipeline.rs, rust/serving/src/source.rs
Fixes https://github.com/numaproj/numaflow/issues/2350
APIs:
----
- `POST /v1/process/sync`
- `POST /v1/process/async`
- `GET /v1/process/fetch?id=req_id`
- `GET /v1/process/status?id=req_id`
The responsibilty of generating a unique request id is moved to the Store implementation if the user doesn't provide one with `X-Numaflow-Id` header. If one is provided and if it already exist in the Store, we return 409 conflict status.
Since request id is generated by Store (or validated if user provides it), we use different tid for tracing (logs).
A request (`/sync` and `/async`) is registered in the store as the first step. With Redis store implementation, this adds an entry:
```
request:${request_id}:status  = 'pending'
``` 
When the processing is completed and all callbacks are received, the …
=> feat: Serving as a builtin source with Monovertex

pkg/reconciler/monovertex/scaling/scaling.go, pkg/reconciler/pipeline/controller.go, pkg/reconciler/vertex/controller.go, pkg/reconciler/vertex/scaling/scaling.go
=> fix(controller): replicas calculation for paused pipeline

rust/numaflow-core/src/pipeline.rs, rust/serving/src/app/callback/cbstore/jetstreamstore.rs
Use `create` ([atomic operation](https://docs.nats.io/nats-concepts/jetstream/key-value-store#atomic-operations-used-for-locking-and-concurrency-control)) when registering request
=> Use atomic operation when registering a request in Jestream KV store

pkg/reconciler/util.go, pkg/reconciler/util_test.go
If there's container restart in the last 2 mins, mark it unhealthy.
Closes: #2446
=> chore: mark unhealthy if there is recent container restart

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx, ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/style.css
Fixes #2452 
- Removed legends from the charts
- Made the tooltip scrollable to avoid overflow
- Added an ability to pin the metrics displayed in the tooltip
=> fix: legends overlapping metrics charts

.github/workflows/ci.yaml, test/e2e-api/main.go, test/e2e-api/serving.go, test/fixtures/e2eapi.go, test/fixtures/serving.go, test/serving-e2e/serving_test.go, test/serving-e2e/testdata/serving-pipeline-cat.yaml
Couldn't make it part of `builtin-sources-e2e` since we need to:
```
kubectl -n numaflow-system set env deploy/numaflow-controller NUMAFLOW_EXECUTE_RUST_BINARY=true
```
The e2e test uses a pipeline with `serving source -> cat vertex -> serve sink`
- Sends a `/sync` request and validates the response
- Sends an `/async` request and validates the response
- Fetches the result of the request sent over `/async` and validates the result.
=> chore: E2E tests for Serving source

rust/serving/src/app.rs, rust/serving/src/app/jetstream_proxy.rs, rust/serving/src/app/orchestrator.rs, rust/serving/src/app/store/cbstore/jetstreamstore.rs
We were not handing the error returned through `notify` channel. We were only handling the [channel receive error](https://github.com/numaproj/numaflow/blob/751f34288c24ee77fa15482c9a90d867040dfd23/rust/serving/src/app/jetstream_proxy.rs#L246), but not the `Result` value sent over the channel. 
Recreate the KV watcher if the watcher for doesn't return any events. Noticed this happening consistently when I sent 10K request (100 connections in parallel). For around 5 requests out of 10K, the `watcher.next()` returns `None`.  With current changes (see `Watcher for Jetstream key didn't return any events`): 
```
$ rg '0195a677-e9ce-77f3-8dc6-e1e06d24a161' serving.log
58658:2025-03-17T23:37:11.374493Z  INFO request{tid="0195a677-e9ce-77f3-8dc6-e1e06d24a161"}: serving::app: Received request …
```
=> fix: Recreate KV watcher if it never returns any events

pkg/daemon/server/service/runtime/pod_tracker.go, pkg/daemon/server/service/runtime/runtime.go, pkg/mvtxdaemon/server/service/runtime/pod_tracker.go, pkg/mvtxdaemon/server/service/runtime/pod_tracker_test.go, pkg/mvtxdaemon/server/service/runtime/runtime.go, rust/numaflow-monitor/src/app.rs, rust/numaflow-monitor/src/runtime.rs
We were not checking if the index was already present in the slice before appending it to the slice.
Code:
```
func (pt *PodTracker) addActivePod(index int) {
pt.activePodsMutex.Lock()
defer pt.activePodsMutex.Unlock()
pt.activePods = append(pt.activePods, index)
}
```
Logs:
```
{"level":"info","ts":"2025-04-01T08:31:46.191147193Z","logger":"numaflow.mvtx-daemon-server.RuntimePodTracker","caller":"runtime/pod_tracker.go:121","msg":"Added active pod 0 for MonoVertex simple-mono-vertex","mvtx":"simple-mono-vertex"}
{"level":"info","ts":"2025-04-01T08:31:46.191175475Z","logger":"numaflow.mvtx-daemon-server.RuntimePodTracker","caller":"runtime/pod_tracker.go:122","msg":"Active Pods Slice now: [0]","mvtx":"simple-mono-vertex"}
{"level":"info","ts":"2025-04-01T08:32:16.185663895Z","logger":"numa …
```
=> fix: add active pod function for runtime errors

rust/numaflow-monitor/src/runtime.rs
We are writing error files from ud containers as well. To avoid race conditions on files, we are appending `-udf` to timestamp in udf. Similarly, `-numa` when writing from numa container.
=> chore: append numa to filename being persisted for runtime errors

pkg/reconciler/servingpipeline/controller.go, test/fixtures/e2e_suite.go, test/fixtures/given.go, test/fixtures/util.go, test/fixtures/when.go, test/serving-e2e/serving_test.go, test/serving-e2e/testdata/serving-pipeline-cat.yaml
Serving E2E test is failing in https://github.com/numaproj/numaflow/pull/2468. This PR fixes it.
```bash
➜  VERSION=serving-e2e-tests ISBSVC=jetstream make start
➜  VERSION=serving-e2e-tests ISBSVC=jetstream SKIP_IMAGE_BUILD=true make test-serving-e2e
<--- snipped --->
go test -v -timeout 15m -count 1 --tags test -p 1 ./test/serving-e2e
=== RUN   TestServingSuite
e2e_suite.go:122: Creating ISB svc numaflow-e2e
e2e_suite.go:124: ISB svc is ready
Forwarding from 127.0.0.1:8378 -> 8378
Forwarding from [::1]:8378 -> 8378
/usr/bin/sh -c kubectl delete -k ../../config/apps/redis -n numaflow-system --ignore-not-found=true
/usr/bin/sh -c kubectl apply -k ../../config/apps/redis -n numaflow-system
configmap/redis-config created
service/redis created
statefulset.apps/redis created
e2e_suite.go:133: …
```
=> fix ServingPipeline E2e tests

.github/workflows/nightly-build.yml
Nightly builds are failing Rust binary building stages: https://github.com/numaproj/numaflow/actions/runs/14554004245/job/40828487229
```
Run RUSTFLAGS='-C target-feature=+crt-static -C linker=aarch64-linux-gnu-gcc' cargo build --release --target aarch64-unknown-linux-gnu
error: process didn't exit successfully: `sccache /home/runner/.rustup/toolchains/1.84-x86_64-unknown-linux-gnu/bin/rustc -vV` (exit status: 2)
--- stderr
sccache: error: Server startup failed: cache storage failed to read: Unexpected (permanent) at read => {"$id":"1","innerException":null,"message":"This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset","typeName":"Microsoft.Azure.DevOps.ArtifactCache.WebApi.ArtifactCacheServi …
```
=> chore: Upgrade sccache action to fix nightly build failures

pkg/daemon/server/daemon_server.go, pkg/daemon/server/service/runtime/pod_tracker.go, pkg/daemon/server/service/runtime/runtime.go, pkg/mvtxdaemon/server/daemon_server.go, pkg/mvtxdaemon/server/service/runtime/pod_tracker.go, pkg/mvtxdaemon/server/service/runtime/runtime.go
Even though we immediately call `fetchAndPersistErrors` function when we start runtime cache refresher, we do not see errors in the UI for sometime.
We are starting `podTracker` (which updates active pods) and `persistRuntimeErrors` go routines at the same time. Since initially active pods are not updated, we do not update the daemon local cache. We have to wait for another 60 seconds, for the next API call in `fetchAndPersistErrors`. In the UI, we will see no errors (even if they are persisted in shared store) until then.
Run `persistRuntimeErrors` go routine just after we receive first update for active pods.
```
{"level":"info","ts":"2025-04-13T03:39:35.34904206Z","logger":"numaflow.mvtx-daemon-server.RuntimePodTracker","caller":"runtime/pod_tracker.go:120","msg":"pods …
```
=> fix: start persisting errors after first active pods update

rust/numaflow-core/src/metrics.rs, rust/numaflow-core/src/sink.rs, rust/numaflow-core/src/transformer.rs
fixes #2383 
fixes #1791 
1. Sink write errors - this will cover Response.Failure cases
2. Sink Dropped total - this will cover drop retry strategy in sink
3. Transformer dropped total - this will cover Drop tag sent in response
4. Fb Sink time - this will cover latency for fallback sink
1. Read total
2. Read time
3. Ack total
4. Ack time
5. E2E time
6. Transformer time
7. Sink time
8. Sink Write Total
9. Fb Sink Write Total
10. Dropped total at MonoVertex level - **Removed**
=> feat: add missing metrics for mvtx

go.mod, pkg/apis/numaflow/v1alpha1/mono_vertex_types.go, pkg/apis/numaflow/v1alpha1/vertex_types.go, pkg/reconciler/cmd/start.go, pkg/reconciler/isbsvc/controller.go, pkg/reconciler/monovertex/controller.go, pkg/reconciler/monovertex/controller_test.go, pkg/reconciler/pipeline/controller.go, pkg/reconciler/pipeline/controller_test.go, pkg/reconciler/servingpipeline/controller.go, pkg/reconciler/vertex/controller.go, pkg/reconciler/vertex/controller_test.go
1. No logger set for the controller runtime, nil pointer error on controller startup;
2. There are cases that the CR status not being updated, which are caused by client-side update. Switch to [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to address the problem. [More](https://kubernetes.io/blog/2022/10/20/advanced-server-side-apply/) to read.
3. Fixed a bug introduced by https://github.com/numaproj/numaflow/pull/2499, that the generated headless object has inconsistent spec (ports in different orders).
=> chore: use server side apply for status update and more

rust/numaflow-core/src/reduce/wal/segment.rs, rust/numaflow-core/src/reduce/wal/segment/append.rs, rust/numaflow-core/src/reduce/wal/segment/compactor.rs, rust/numaflow-core/src/reduce/wal/segment/replay.rs
To avoid an extra read after replay on bootup, we can replay while compacting.
=> chore: extend compactor to write to tx on replay

rust/numaflow-core/src/reduce/wal/segment/replay.rs
path could have `_` in the dirname.
=> fix: take only the base filename while sorting

rust/numaflow-core/src/config/pipeline.rs
fixes #2637 
```
- name: out
containerTemplate:
env:
- name: NUMAFLOW_RUNTIME
value: "rust"
scale:
min: 1
sink:
retryStrategy:
backoff:
interval: 1s
steps: 100
udsink:
```
```
vertex_type_config: Sink(
SinkVtxConfig {
sink_config: SinkConfig {
sink_type: UserDefined(
UserDefinedConfig {
grpc_max_message_size: 67108864,
socket_path: "/var/run/numaflow/sink.sock",
server_info_path: "/var/run/numaflow/sinker-server-info",
},
),
retry_config: Some(
RetryConfig {
sink_max_retry_attempts: 100,
sink_retry_interval_in_ms: 1000,
sink_retry_on_fail_strategy: Retry,
sink_default_retry_strategy: RetryStrategy {
backoff: Some(
Backoff {
interval: Some(
1ms,
),
steps: Some(
65535,
),
},
),
on_failure: Some(
"retry",
),
},
},
),         
},
fb_sink_config: None,
serving_store_config: None,
},
),
```
=> fix: honour retry config in case of Pipeline in Rust

.github/workflows/ci.yaml, .github/workflows/nightly-build.yml, .github/workflows/release.yml
Fix release pipeline: https://github.com/numaproj/numaflow/actions/runs/15129096355/job/42526511087
- Use docker container to build binaries instead of running directly on github action runner.
- Use arm action runner for building arm binary
Copied from nightly build pipeline which was changed in https://github.com/numaproj/numaflow/pull/2636
=> chore: Use arm runner for building arm binary in release pipeline

docs/user-guide/FAQ.md, rust/numaflow-core/src/shared/server_info.rs, ui/src/components/common/SlidingSidebar/partials/VertexDetails/partials/Errors/partials/CollapsableError/index.tsx
fixes #2634 
1. Error message mentions that the server is not started correctly
2. Include `http/s` protocols, line anchors in URLs, and file paths without extensions as well while highlighting in the UI
```
2025-05-19T06:49:53.043111Z ERROR numaflow_core: Error running monovertex e=ServerInfo("Server info file \"/var/run/numaflow/sinker-server-info\" is not ready. This indicates that the server is not started correctly in the user-code. Eg (simple sink in Java, similarly you can refer language specific SDK examples) https://github.com/numaproj/numaflow-java/blob/2aeaafff1c6dec7fd66e018b142ef6fe4ffcf0a9/examples/src/main/java/io/numaproj/numaflow/examples/sink/simple/SimpleSink.java#L23")
2025-05-19T06:49:53.043491Z INFO numaflow_core: Gracefully Exiting...
2025-05-19T06:49:53.043598Z …
```
=> chore: enhance error logging when the server is not started in `udcontainer`

pkg/apis/numaflow/v1alpha1/vertex_types.go, pkg/apis/numaflow/v1alpha1/vertex_types_test.go
At the start, MonoVertex was targeted for surfacing application errors. 
But the functionality was developed for pipeline as well, so runtime path had to be mounted for surfacing the errors in case of vertices of pipelines.
Below is screenshot when `udf` vertex is in panic state.
=> fix: mount runtime path for pipeline/vertex

rust/extns/numaflow-jetstream/Cargo.toml, rust/extns/numaflow-jetstream/src/lib.rs, rust/numaflow-core/src/source/jetstream.rs
fixes https://github.com/numaproj/numaflow/issues/2723
We only allow specifying stream name as a user option when Jetstream source is used. We expect a consumer with same name as the stream name to be present.
Tested by running the pipeline:
```yml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
name: simple-pipeline
spec:
vertices:
- name: in
scale:
min: 1
containerTemplate:
image:
env:
- name: NUMAFLOW_RUNTIME
value: "rust"
source:
jetstream:
url: host.lima.internal
stream: test-stream
- name: out
containerTemplate:
image:
env:
- name: NUMAFLOW_RUNTIME
value: "rust"
scale:
min: 1
sink:
log: {}
edges:
- from: in
to: out
```
Created stream and consumer:
```sh
nats str add test-stream
nats con add test-stream test-stream
```
Published messages:
```sh
nats pub test.abcd …
```
=> fix: Wrong usage of get_consumer_from_stream

rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs, rust/numaflow-core/src/watermark/isb/wm_publisher.rs
- move error to warn for retryable errors during ISB restarts
- double ack for EOS
=> chore: minor clean up before 1.5 release

docs/core-concepts/message-headers.md, mkdocs.yml
Fixes: #1598 
This documentation introduces how Message Headers work in Numaflow, including:
- Overview and use cases
- Access patterns in Go and Python SDKs
- Header lifecycle within a pipeline
- Real application references (Kafka, HTTP)
- Example YAML pipeline
Feedback and suggestions are welcome!
=> docs: Added documentation for Message Headers in Numaflow

ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/Metrics/partials/LineChart/index.tsx
Issue occurs in UI only for:
- MonoVertex
- Pod CPU/Memory utilization metric
- More than 1 mono vertices are there and name of one mono vertex is contained in the other
-  eg: `consumer-mvtx`, `consumer-mvtx-old`
- In this case `consumer-mvtx` end up showing pod utilization metric data for `consumer-mvtx-old` as well.
Fix:
By adding `-mv-` to the mono vertex identifier to get pods only for that particular mono vertex.
=> fix: add `-mv-` in mvtx name for pod memory/cpu metrics

Makefile, rust/numaflow/src/cmdline.rs
Fix(Makefile): remove dash(`-`) before `go test` to ensure e2e failures are not ignored
introduced in #2529 
```
--- FAIL: TestMonoVertexSuite (281.14s)
--- FAIL: TestMonoVertexSuite/TestExponentialBackoffRetryStrategy (122.49s)
--- FAIL: TestMonoVertexSuite/TestMonoVertexWithAllContainers (122.46s)
FAIL
FAIL	github.com/numaproj/numaflow/test/monovertex-e2e	281.150s
FAIL
make: [Makefile:138: test-monovertex-e2e] Error 1 (ignored)
make cleanup-e2e
```
=> fix: failures in e2e tests ignored

rust/numaflow-core/src/shared.rs, rust/numaflow-core/src/shared/server_info.rs
I removed the `pub use` (which was hack to keep it going) and now is directly referencing the shared mod. I forgot to delete this in the previous PR.
=> chore: delete unused server_info

rust/numaflow-core/src/pipeline.rs, rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs, rust/numaflow-core/src/reduce/reducer/aligned/reducer.rs, rust/numaflow-core/src/reduce/reducer/unaligned/reducer.rs, rust/numaflow-core/src/reduce/reducer/unaligned/user_defined/session.rs, rust/numaflow-core/src/reduce/reducer/unaligned/windower/session.rs, rust/numaflow-core/src/watermark/isb.rs, rust/numaflow-core/src/watermark/isb/wm_publisher.rs, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-go.yaml, test/reduce-two-e2e/testdata/session-reduce/simple-session-keyed-counter-pipeline-java.yaml
* Update last publish offset to larger value even when the watermark is -1 to avoid watermark regression
* Fix session merge edge cases
* Add keys to message id to avoid duplicates in session windows
* Refactored aligned and unaligned reducer to make it more readable
* Close windows when there is no input data(idling)
=> fix: aligned and unaligned reduce in Rust runtime

pkg/reconciler/monovertex/controller.go, pkg/reconciler/util.go, pkg/reconciler/util_test.go, pkg/reconciler/vertex/controller.go
Fixes: #2853
When container detects if there's any container restart due to OOM in the last 2 mins, it marks the vertex/mvtx as unhealthy. However, after that unless there's any controller watches objects change (e.g. pod creation/deletion), it will not re-check the status.
This PR explicitly requeue the request after detecting container restart.
=> fix: requeue reconciliation after seeing container restart

rust/Cargo.lock, rust/extns/numaflow-kafka/src/source.rs, rust/extns/numaflow-nats/Cargo.toml, rust/extns/numaflow-nats/src/jetstream.rs, rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs, rust/numaflow-core/src/shared/create_components.rs, rust/numaflow-core/src/source/jetstream.rs, rust/numaflow-shared/src/server_info.rs, rust/numaflow/build.rs
* We will see potential duplicate messages in JetStream source if the pod restarts.
* Infinite retries in JetStream source didn't honor the cancellation signal.
* Use `double_ack()` instead of `ack()` when acknowledging the messages back to JetStream source to avoid duplicates.
* Added a conditional to retry backoff to stop when the cancellation token is cancelled.
=> chore: improvements for js source 

rust/numaflow-sideinput/src/manager.rs, test/map-e2e/map_test.go, test/monovertex-e2e/monovertex_test.go
Unit test fails locally if nats server is not running 
N/A
Ran the test locally
N/A
=> fix: `side_input_operations` test should be behind `nats-tests` feature

pkg/daemon/server/service/rater/helper.go, pkg/daemon/server/service/rater/helper_test.go, pkg/mvtxdaemon/server/service/rater/helper.go, pkg/mvtxdaemon/server/service/rater/helper_test.go
Since, we didn't have a nil check to avoid storing the nil metric data points in the tracked counts, we were seeing sudden spikes in processing rate when we redeploy the pipeline or MonoVertex.
```
CalculateRate: lookbackSeconds: 120, partitionName: default-even-odd-sum-compute-counter-0,
counts: [
{timestamp: 1758206641, podPartitionCount: map[]} 
{timestamp: 1758206642, podPartitionCount: map[]} 
{timestamp: 1758206643, podPartitionCount: map[]} 
{timestamp: 1758206644, podPartitionCount: map[]} 
{timestamp: 1758206645, podPartitionCount: map[even-odd-sum-compute-counter-0:map[default-even-odd-sum-compute-counter-0:4263] even-odd-sum-compute-counter-1:map[default-even-odd-sum-compute-counter-1:1827]]} 
{timestamp: 1758206646, podPartitionCount: …
```
=> fix: rater should not consider nil metric data points
